### ISSUE TITLE
Using dnx with an unsupported framework gives an error about package restore

### ISSUE THREAD

**Issue by rynowak** [aspnet/dnx#1695] opened 2015-04-23 06:10 UTC
Create a console project that only targets dnx451

Try to run at the commandline with coreclr dnx

You get this error, instead of being told that the framework isn't supported for the project:
```
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNXCore,Version=v5.
0':
   <name of your project> 1.0.0

Searched Locations:
  C:\git\DocAsCode\BackEnd\{name}\project.json
  C:\git\DocAsCode\wrap\{name}\project.json
  C:\Users\rynowak\.dnx\packages\{name}\{version}\{name}.nuspec

Try running 'dnu restore'.
```

**Comment by davidfowl** [comment] 2015-04-23 07:14
Dupe of https://github.com/aspnet/dnx/issues/1467

**Closed by davidfowl** 2015-04-23 07:14 UTC
