### ISSUE TITLE
XRE gives poor experience when multiple users log into the same machine

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#1315] opened 2015-03-04 19:55 UTC
I've encountered this issue multiple times... generally when using VMM servers that only I have access to to create a VM, then share it with latest ASP.NET VNext and VS appropriately set up, with partner teams.

If I have done KVM upgrade and have a project that depends on some specific version of XRE, generally due to the build of VIsual Studio I'm using or the versions of packages I'm using, there's no way for another user logging into the box to pick that up as it's under C:\Users\mattgal\.k\runtimes\, which the new user lacks access to.

It would be useful to either specify a specific path to store the runtime for a given project in (that way, if someone wanted to and wasn't using GIT, the could check in their XRE AND package cache to their source control system), or just make the experience of a new user logging in and using the same solution better in some other way.

**Comment by davidfowl** [comment] 2015-03-04 20:01
Isn't this a dupe of #1030.

**Comment by muratg** [comment] 2015-03-17 17:31
Moving to 1.0.0 milestone for now. We'll retriage in RTM timeframe.

**Comment by sayedihashimi** [comment] 2015-05-20 18:26
@MattGal in your case is Visual Studio being used by all users? In VS for the next release we are working on a feature that when you open a project that has SDK version specified in global.json, but it's not available we will install it. I think that will help for the cases where VS is being used.

For command line/CI scenarios I think we still have some gaps.

**Comment by MattGal** [comment] 2015-06-24 20:58
@sayedihashimi  Yes.  Back when I created the issue, I was specifically setting up machines for partners to use for co-development of porting their apps to ASP.NET 5.  Back then things were a bit more finicky so I would make sure the environment and Web Tools bits were good before handing it over to the partner team.

I imagine the main reason folks would hit this is when adding other users to their machine to connect and help debug / fix build issues.    For the purposes of what I was doing, and likely a majority of actual users, what you describe is sufficient to make their scenario work.

**Comment by muratg** [comment] 2015-06-24 21:08
Closing per @MattGal's last comment. We can revisit later if there's more feedback.

**Closed by muratg** 2015-06-24 21:08 UTC
