### ISSUE TITLE
Dnvm error with space in path (RC1)

### ISSUE THREAD

**Issue by plitwin** [aspnet/dnx#3234] opened 2015-12-04 21:30 UTC
![rc1-bug](https://cloud.githubusercontent.com/assets/1145843/11601834/ed210ecc-9a8a-11e5-88bc-d41d7c1f965a.PNG)

After upgrading to RC1 and then installing the updated-1, I still get this error any time I use a DNX command:
'C:\Users\Paul' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

**Comment by davidfowl** [comment] 2015-12-04 23:02
dnx list isn't a thing.

**Comment by plitwin** [comment] 2015-12-05 01:27
Sorry I mistyped. I meant dnvm list! It still produces the error!
Paul Litwin


From:  David Fowler <notifications@github.com>
Reply-To:  aspnet/dnx
<reply+00117bf3b83c91a1ac76de2b97d2f5a13038e0267adb548592cf000000011279dda59
2a169ce072e8792@reply.github.com>
Date:  Friday, December 4, 2015 at 3:03 PM
To:  aspnet/dnx <dnx@noreply.github.com>
Cc:  Paul Litwin <paul@litwinconsulting.com>
Subject:  Re: [dnx] Dnx error with space in path (RC1) (#3234)


dnx list isn't a thing.


Reply to this email directly or view it on GitHub
<https://github.com/aspnet/dnx/issues/3234#issuecomment-162105666> .

**Comment by BrennanConroy** [comment] 2015-12-05 02:41
run ```dnvm update-self```

**Comment by davidfowl** [comment] 2015-12-05 17:40
Closing this.

**Comment by plitwin** [comment] 2015-12-05 18:39
Sorry but I missed the resolution?

Regards,
Paul

**Comment by davidfowl** [comment] 2015-12-05 18:42
@BrennanConroy just said it `dnvm update-self`

**Comment by plitwin** [comment] 2015-12-05 20:02
David, 

I think it would make sense first to check with the bug reporter whether or not the supposed fix actually fixed the bug before closing the issue. It did NOT fix the issue.
![dnvm_3](https://cloud.githubusercontent.com/assets/1145843/11609902/f624f9d0-9b47-11e5-93b6-aeeed8dd2eff.PNG)

**Comment by plitwin** [comment] 2015-12-05 20:03
And if you want more details: This is VMWare fusion VM on a macbook pro. The O/S is Windows 7 in the VM.

**Comment by BrennanConroy** [comment] 2015-12-05 20:09
You'll need to manually update the dnvm then. Replace your dnvm.cmd with https://github.com/aspnet/Home/blob/dev/dnvm.cmd

**Comment by davidfowl** [comment] 2015-12-05 20:16
Either way this bug should be filed on dnvm. I'll leave it open.

**Comment by GZidar** [comment] 2016-04-14 01:04
The issue is fixed with the latest dnvm.cmd file but the package cannot update itself to correct the issue. I manually edited the dnvm.cmd file using notepad to add the quotes around the path update:

change

do set DNVM_CMD_PATH_FILE=%%i.cmd

to 

do set DNVM_CMD_PATH_FILE="%%i.cmd"

then run the dnvm update-self command as has previously been suggested to get anything else that might have been changed and now this error has gone away.

**Closed** 2017-12-17 19:50 UTC
