### ISSUE TITLE
Strong name everything

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx#2615] opened 2015-09-02 16:44 UTC
We should OSS/fake strong name our assemblies  -https://github.com/aspnet/EntityFramework/issues/999

**Comment by muratg** [comment] 2015-09-22 15:22
Moving this to RC1. @moozzyk feel free to bring it back if you have time at the end of the week.

cc: @rowanmiller

**Comment by moozzyk** [comment] 2015-09-22 18:07
:+1:

**Comment by hkoestin** [comment] 2015-09-30 11:04
@moozzyk & @muratg does this mean, that we do not get strong named assemblies of EntityFramework with beta 8?

I am asking, because I would need to come up with a huge workaround otherwise :-1:

**Comment by muratg** [comment] 2015-09-30 14:37
@hkoestin That's true. We just couldn't fit it in with all the other work that needed to happen in Beta 8. We'll do this in RC1.

**Comment by hkoestin** [comment] 2015-09-30 14:47
@muratg Thanks for the information. This is really unfortunate news for me now, as I would need signed assemblies :disappointed: You see any workaround for this? The problem is not the actual signing of the assembly, that I can do myself. It is more about the used [InternalsVisibleTo] attributes in the assemblies.

See https://github.com/aspnet/EntityFramework/issues/999#issuecomment-143674933

**Comment by muratg** [comment] 2015-09-30 15:22
@hkoestin Unfortunately, I don't know of any workaround. You can wait for this bug to be resolved, and work with RC1 dev packages before RC1 goes out if that helps.

**Comment by hkoestin** [comment] 2015-09-30 15:25
@muratg would be great if someone could ping me, if this is fixed. Then I would get a nightly build asap. When can I expect it to be fixed? A week? Two weeks? A month?

**Comment by muratg** [comment] 2015-09-30 16:19
@hkoestin Please subscribe to this issue if you haven't already (click "Subscribe" on top right) and you should get a notification when the status changes.  We can try pinging you on GitHub but also we could forget :)    I don't have an estimation at the moment when this will be closed, but it would be more than a week (as actual RC1 coding starts next week only) and ideally less than a month.

**Comment by muratg** [comment] 2015-10-13 16:06
See more details about OSS signing [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/oss-signing.md)

**Comment by natemcmaster** [comment] 2015-11-05 21:24
@cesarbs VS Intellisense doesn't recognized InternalsVisibleTo with a strong name. Compilation still works. Anyway around this in VS?

**Comment by moozzyk** [comment] 2015-11-05 22:22
@natemcmaster This is a tooling issue that was fixed very recently.

**Comment by natemcmaster** [comment] 2015-11-05 22:23
@moozzyk awesome, thank.

**Closed** 2015-11-09 19:03 UTC
Labels: 3 - Done, task
