### ISSUE TITLE
NuPkgs which depend on System.Runtime <= 4.0.10.0 have dependency issues on K projects and may fail to run on machines with only 4.5.1

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#1063] opened 2015-01-12 19:45 UTC
When a user adds a reference to a NuPkg that references System.Runtime 4.0.10.0 to a K Project, they are first presented with this error message:

![error](https://cloud.githubusercontent.com/assets/7862010/5709605/180b104c-9a50-11e4-85ce-7710ae58625e.png)

... unfortunately, adding a reference under the "frameworkAssemblies" tab to System.Runtime 4.0.10.0 doesn't work.  The only version that successfully resolves via intellisense and fixes the build-time error is System.Runtime 4.0.20.0.  However, this assembly does not exist on machines running only .NET 4.5.1, which is a supported platform for ASP.NET 5.   

Thus, applications built this way will not run on downlevel platforms with only 4.5.1 without some kind of change.  This behavior should be brought in line with what MSBuild does today to prevent this sort of problem.

**Comment by davidfowl** [comment] 2015-01-13 16:47
Does msbuild automagically correct the problem, or does it give you a better error message?

**Comment by davidfowl** [comment] 2015-03-30 16:26
@MattGal This is by design.

**Comment by muratg** [comment] 2015-06-26 17:16
@anurse @davidfowl is this still an issue?

**Comment by davidfowl** [comment] 2015-06-26 17:16
Yes, it'll be fixed in the re-architecting of dnx

**Comment by davidfowl** [comment] 2015-06-26 17:16
Moved to beta7

**Comment by davidfowl** [comment] 2015-09-21 21:31
Closing as dupe of https://github.com/aspnet/dnx/issues/726

**Closed by davidfowl** 2015-09-21 21:31 UTC
Labels: 1 - Ready, bug
