### ISSUE TITLE
DNU build give a error about missing namespace on command line, but VS2015RC does not display the error in the Error List

### ISSUE THREAD

**Issue by Anderman** [aspnet/dnx#2667] opened 2015-09-10 08:04 UTC
DNU build give this error:
`C:\git\DBC\src\DBC\Controllers\UserController.cs(77,24): DNX,Version=v4.5.1 error CS0118: 'DataTables' is a namespace but is used like a type`

for this line
```
            return new DataTables().GetJSonResult(
                z
                , dTRequest);
```
This can be fixed with adding a namespace
```
            return new Mvc.JQuery.Datatables.DataTables().GetJSonResult(
                z
                , dTRequest);

```
```
C:\git\DBC\src\DBC>dnu build
Microsoft .NET Development Utility CLR-x86-1.0.0-beta7-15532
```

This bug is in  my repro see the commits in [DBC](https://github.com/Medella/DBC/commits/master) 
`3cedf0de134730f7213f756b5ed650acb45ee8fc`
and
'a16136000372649505e7aff36bd025c6d3234a1d'

**Comment by muratg** [comment] 2015-09-10 15:57
Is there a class `DataTables` at all? Not sure why you call new with `DataTables()`

**Comment by Anderman** [comment] 2015-09-10 16:05
Yes there is. I use a different project for datatables. See [Datatables](https://github.com/Anderman/Mvc.JQuery.Datatables/blob/dev/src/Mvc6.JQuery.Datatables/DataTables.cs)
Do you have problems with the source?

```
using System.Linq.Dynamic;
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Mvc.JQuery.Datatables;
using UserManagement.Models;
using System.Linq.Expressions;
using System;
using System.Collections;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace UserManagement.Controllers
{

    public class role
    {
        public string Name { get; set; }
    }
    public class roles : List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
    {
    }

    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        public UserController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            DbContext = context;
            _userManager = userManager;

        }

        public ApplicationDbContext DbContext { get; }
        [HttpGet]
        [AllowAnonymous]
        public ViewResult Index()
        {
            //var x = DbContext.Users.Include(u => u.Logins).Select(l => l.Logins).ToArray();
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public JsonResult Index([FromBody]DataTablesRequest dTRequest)
        {
            var q = DbContext.Users.Include(u => u.Logins).ToArray();
            var yy = DbContext.UserRoles.Join(DbContext.Roles, ur => ur.RoleId, r => r.Id, (ur, r) => new { r.Name, ur.UserId });
            var z = (from u in DbContext.Users//.Include(l => l.Logins).Include(r => r.Roles)
                     select new
                     {
                         u.Id,
                         u.Email,
                         u.EmailConfirmed,
                         u.UserName,
                         u.TwoFactorEnabled,
                         u.LockoutEnd,
                         Logins = u.Logins.Select(l => new { LoginProvider = l.LoginProvider }),
                         Roles = yy.Where(ur => ur.UserId == u.Id),
                         //Roles = u.Roles.Join(DbContext.Roles, ur => ur.RoleId, rr => rr.Id, (ur, role2) => role2).Select(rr => rr),
                     });
            var zz = z.ToArray();
            return new Mvc.JQuery.Datatables.DataTables().GetJSonResult(
                z
                , dTRequest);
        }
        [HttpGet]
        [AllowAnonymous]
        public PartialViewResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Create(ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                await _userManager.CreateAsync(model);

                return new EmptyResult();
            }
            return PartialView(model);
        }


        [HttpGet]
        [AllowAnonymous]
        public PartialViewResult Edit(string Id)
        {
            //var dummy = DbContext.Users.Include(u => u.Logins).ToArray();
            var user = DbContext.Users.Include(u => u.Logins).Include(u => u.Claims).Include(u => u.Roles).FirstOrDefault(u => u.Id == Id);
            return PartialView(user);
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Edit(ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);
                user.AccessFailedCount = model.AccessFailedCount;
                user.Email = model.Email;
                user.EmailConfirmed = model.EmailConfirmed;
                user.LockoutEnabled = model.LockoutEnabled;
                user.LockoutEnd = model.LockoutEnd;
                user.PhoneNumber = model.PhoneNumber;
                user.PhoneNumberConfirmed = model.PhoneNumberConfirmed;
                user.TwoFactorEnabled = model.TwoFactorEnabled;
                user.UserName = model.UserName;
                await _userManager.UpdateAsync(user);

                DbContext.SaveChanges();
                return new EmptyResult();
            }
            return PartialView(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public PartialViewResult Delete(string Id)
        {
            var user = DbContext.Users.Single(u => u.Id == Id);
            return PartialView(user);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Delete(ApplicationUser model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);
            await _userManager.DeleteAsync(user);
            return new EmptyResult();
        }
    }
}
```

**Comment by Anderman** [comment] 2015-09-10 19:23
The problem is a little different. VS2015 'Error list' window doesn't give any errors when rebuild te solution. But the VS2015 'output' window give the same error. So I think it is more VS2015 related.

![image](https://cloud.githubusercontent.com/assets/1858745/9798539/df304bf0-5801-11e5-8b21-f99686347763.png)

![image](https://cloud.githubusercontent.com/assets/1858745/9798552/fc748e7e-5801-11e5-8c0b-533b11dffa27.png)

**Comment by muratg** [comment] 2015-09-11 06:17
OK thanks. So build was actually failing on VS as well. Could you file a bug on the http://github.com/aspnet/tooling repo?

**Comment by davidfowl** [comment] 2015-09-11 06:53
We need to look at drh

**Comment by Anderman** [comment] 2015-09-11 07:12
Ok, I also made a new issue on [tooling](https://github.com/aspnet/Tooling/issues/175)

**Comment by muratg** [comment] 2015-09-11 15:18
@troydai

**Comment by troydai** [comment] 2015-09-11 22:21
I'll take a look

**Comment by troydai** [comment] 2015-09-15 23:31
Hi @Anderman , I'd like to point out you're using the VS2015 RC. Can you try the same scenario with VS 2015 RTM?

**Comment by troydai** [comment] 2015-10-02 16:56
@Anderman I found this issue is tracked by tooling team. I'll close this issue for now. Please feel free to open if there is anything more directly point the root cause to runtime. Thanks.

**Closed by troydai** 2015-10-02 16:56 UTC
Labels: Investigate
