### ISSUE TITLE
Support consuming and producing nuget packages with native binaries

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#402] opened 2014-07-01 04:32 UTC
We need a convention for both consuming and adding native binaries to nuget packages. 

When you're developing a project and need to take a dependency on a native binary,  you need to put it in a path that is loadable. This scenario needs to take bitness and OS into account.

You also need to be able to produce a package that has these native binaries inside of it.

**Comment by nathanaeljones** [comment] 2015-03-20 16:12
Is there any documentation of this model? If I submit a PR to paket that enables this workflow, I'd like to keep the nuget syntax compatible or consistent with what you guys are doing.

**Comment by jbrwn** [comment] 2015-06-15 23:00
Is there any more information on this?   Seems like there are a few issues out there about this but no resolution. 

https://github.com/aspnet/dnx/issues/990
https://github.com/NuGet/Home/issues/300

 An update would be much appreciated.

**Comment by jbrwn** [comment] 2015-06-16 23:09
pinging @davidfowl and @yishaigalatzer

Would love to get a quick status report on this topic.

**Comment by yishaigalatzer** [comment] 2015-06-17 01:07
We should have something out within a week or so. Still working on documenting the details

**Comment by yishaigalatzer** [comment] 2015-06-17 01:43
I will try to post a sample today or tomorrow

**Comment by yishaigalatzer** [comment] 2015-06-17 01:49
https://www.myget.org/F/dotnet-core/api/v2/package/System.IO.Compression/4.0.0-beta-22927

**Comment by jbrwn** [comment] 2015-06-17 15:59
@yishaigalatzer - thanks for the response and posting the sample package.  I'll be keeping my eye out for documentation.  In the mean time, is it possible for you to elaborate a little on how this all works?   I see an "any" TFM directory and a runtime.json file in the root of the package.  It would be great to hear about how this all comes together so i can start experimenting with it even if complete documentation is not ready.

**Comment by yishaigalatzer** [comment] 2015-06-17 17:02
The any folder is going to probably be renamed before we are done. The runtimes is about bringing implementation that are runtime target appropriate. We can probably post more preliminary info here to get you going, let me see if we have something useful

**Comment by glennc** [comment] 2015-06-17 18:36
We are talking about a package that has a managed assembly that needs to invoke stuff from a native assembly that it carries, right? If that's the case then the current plan, as far as I understand it, is to be able to create a package like the following:

```
MyLib
  lib
    dotnet
      `MyLibrary.dll`
  runtimes
    win-x86
        native
            `MyNativeLib.dll`
    win-x64
        native
            `MyNativeLib.dll`
```

The build system responsible for consuming this package would need to know to copy the native assembly to your build output when building for the given runtime. You could put `linux-x86`, `linux-64`, etc as well. The key is that there is a runtimes folder with a runtime id. The runtime Id is how you pivot on things like os and architecture. The native folder is for assets that need to be copied to the applications output directory to be consumed by my library.

@davidfowl or @anurse might have more detailed comments. There should be more docs on how it all fits together coming at some point soon.

**Comment by nathanaeljones** [comment] 2015-06-17 18:40
@glennc Any news on which build systems will be supporting this? Will native package support be exclusive to VS2015 and dnx-based systems? 

Also, have there been corresponding changes in the .NET full framework to allow native libraries to be located even when the managed libraries are loaded with shadow-copying?

**Comment by jbrwn** [comment] 2015-06-17 20:15
@glennc Thanks for your input.  
>We are talking about a package that has a managed assembly that needs to invoke stuff from a native assembly that it carries, right?

That's right.

>The build system responsible for consuming this package would need to know to copy the native assembly to your build output when building for the given runtime.

I think this is the primary question for me and others - how will dnx/dnu handle native assemblies in a nuget package? 

 In the past we could always just make up our own convention for including native dlls in a nuget package and then copy them wherever we want  using a Install.ps1/init.ps1 script or a .props file.  However, the game is changing because, as far as i know, there is no "output directory" in dnx - everything is loaded into memory from the dependent nuget packages.

**Comment by davidfowl** [comment] 2015-06-18 00:39
> I think this is the primary question for me and others - how will dnx/dnu/visual studio handle native assemblies in a nuget package?

In vs2015 there's a new NuGet aware msbuild task that will copy the relevant assets into the project's output directory so that should just work.

In the DNX, there will be no copying but the runtime will discover the appropriate assets and setup the runtime so that loading those dlls will just work (via Dll import or via an API).

> In the past we could always just make up our own convention for including native dlls in a nuget package and then copy them wherever we want using a Install.ps1/init.ps1 script or a .props file.

Yea, we're moving away from ps1 files altogether in the next nuget and in the dnx. However props files will still work in msbuild based projects in the next version of NuGet.

**Comment by jbrwn** [comment] 2015-06-18 02:13
@davidfowl Thanks for taking the time to respond. 

>In vs2015 there's a new NuGet aware msbuild task that will copy the relevant assets into the project's output directory so that should just work.

Your talking about a plain old .net framework project (e.g., csproj) and not an asp.net 5.0/dnx project (xproj) right?  If so, i am right there with you.  This is not an issue for me.  

> In the DNX, there will be no copying but the runtime will discover the appropriate assets and setup the runtime so that loading those dlls will just work (via Dll import or via an API).

This is what i am after.  I understand that this may not be fully documented but even just some preliminary info as @yishaigalatzer suggested would be greatly appreciated and go a long way to providing some clarity on how this will all fit together for developers who support projects with a native component.  Thanks!

**Comment by yishaigalatzer** [comment] 2015-06-18 03:39
I think you care about both scenarios. We want the new packages to work for both projects with csproj files and dnx. Infact in some of the new csproj files its going to be a requirement

**Comment by jbrwn** [comment] 2015-06-18 05:01
>I think you care about both scenarios. We want the new packages to work for both projects with csproj files and dnx. Infact in some of the new csproj files its going to be a requirement

Yep, you're totally right.  The csproj side just seems like less of a mystery to me.   I'm looking forward to seeing how this will all come together.  Again, any details bring clarity to how this will all work would be greatly appreciated.  Thanks again.

**Comment by davidfowl** [comment] 2015-07-04 09:23
A simple way to think about it is, the csproj will copy the native binaries from packages to the bin folder. The dnx will load the native binaries in place without copying them.

**Comment by nathanaeljones** [comment] 2015-07-07 15:48
@davidfowl Hopefully more is happening than just a /bin copy for .csproj? That's not enough for .NET to locate them when you're using a test runner or other external host that uses [`ShadowCopyFiles=true` ](https://msdn.microsoft.com/en-us/library/system.appdomain.shadowcopyfiles(v=vs.110).aspx) on the AppDomain.

**Comment by davidfowl** [comment] 2015-07-07 17:07
Nothing in .NET Framework 4.6 is changing if that's what you're asking

**Comment by jbrwn** [comment] 2015-07-07 17:17
>The dnx will load the native binaries in place without copying them.

@davidfowl Can you provide any more details on how this works?  e.g., how do we set up a nuget package or kproj that will allow dnx to load the native binaries?   Thanks in advance.

**Comment by jbrwn** [comment] 2015-07-07 17:18
@nathanaeljones Interesting question but it does seem a little off topic for this issue.  Not trying to be rude but it seems like you may get some more traction on this by creating a new issue somewhere.

**Comment by davidfowl** [comment] 2015-07-07 17:30
@jbrwn The dnx hasn't implemented anything as yet (that's what this issue is for) but the current plan is to modify either the dll search paths or the PATH env variable to take into account packages that contain native code.

**Comment by jbrwn** [comment] 2015-07-07 17:39
@davidfowl Got it.  Do you have a target date for when this feature will be implemented?

**Comment by muratg** [comment] 2015-07-10 16:54
@moozzyk

**Comment by xanather** [comment] 2015-07-13 07:46
Right now using native libraries on the DNX (which is packaged based) is a pain without this.

**Comment by davidfowl** [comment] 2015-07-13 07:53
@xanather CoreCLR right? What happens if you drop the native binary in the application root? (just curious)

**Comment by xanather** [comment] 2015-07-13 08:01
@davidfowl Yes I am using CoreCLR. When debugging it works fine in the app root, however last time I tried when the app was published (by using DNU) I needed to put the native library in the runtime folder.

**Comment by davidfowl** [comment] 2015-07-13 08:02
@xanather Nope, there's always an application root, when you publish it's just somewhere different. Doesn't it copy all files from your application root anyways?

**Comment by xanather** [comment] 2015-07-13 08:17
Yes it copies everything, but DNX is unable to load native libraries unless I move them to the runtime folder of the published app

**Comment by xanather** [comment] 2015-07-13 08:28
Pretty sure it just has something to do with windows probing the current directory. Debug would have the correct current directory while running it from the published .cmd won't.

**Comment by davidfowl** [comment] 2015-07-13 08:30
At the very least we should probably set this https://github.com/aspnet/dnx/blob/dev/src/dnx.coreclr/dnx.coreclr.cpp#L236 to the appbase.

**Comment by xanather** [comment] 2015-07-13 08:32
Just tested, I can confirm it is because of the current directory.

**Comment by davidfowl** [comment] 2015-08-22 00:20
Prototype here https://github.com/aspnet/dnx/commit/afb29037e8c9aa21cdd9138cf3de74d30e39dc7f

**Comment by muratg** [comment] 2015-09-22 15:24
@moozzyk I think you wanted to do this in beta 8, but let me know if it won't fit.

**Comment by moozzyk** [comment] 2015-09-22 15:48
Let's leave it for now. This is small so I might be able to get this in.

**Comment by muratg** [comment] 2015-09-28 16:58
Move now? :)

**Comment by davidfowl** [comment] 2015-09-28 17:01
@natemcmaster @bricelam what is SQLite doing for native dependencies right now?

**Comment by natemcmaster** [comment] 2015-09-28 17:09
@davidfowl On Windows, we are redistributing sqlite3.dll with the nupkg. The makefile.shade manually downloads the dll and adds it to the nupkg. We then search for this assembly and load it into the appdomain. (see [NativeLibraryLoader](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs)).

For OSX/Linux, we use whichever version of libsqlite3 the system has installed in LD_LIBRARY_PATH.

**Comment by bricelam** [comment] 2015-09-28 17:37
For SQL Server, we currently rely on `sni.dll` being distributed as part of the `dnx-coreclr-win` packages.

**Comment by moozzyk** [comment] 2015-09-28 17:39
Changing milestone to RC. Still waiting for CoreClr to merge the API we would use to load dlls/so/dylibs.

**Comment by natemcmaster** [comment] 2015-10-07 17:41
@moozzyk are their issues/PRs on the dotnet repos we can follow to track this?

**Comment by moozzyk** [comment] 2015-10-07 17:43
@natemcmaster - I think the change on the CoreClr side went in last week so is no longer blocking.

**Comment by natemcmaster** [comment] 2015-10-07 17:46
@moozzyk awesome.

**Comment by nathanaeljones** [comment] 2015-10-07 18:01
Can someone writeup the status of native binary packages across all 2015 platforms (full .NET framework, VS 2105, VS code, DNX, etc)?

**Comment by moozzyk** [comment] 2015-10-07 18:08
@nathanaeljones - the support in DNX is scheduled for RC. Can you elaborate more on what your expectations are with regards to "VS 2015 and VS Code" ?

**Comment by nathanaeljones** [comment] 2015-10-07 18:54
* [ ] Is there documentation or tooling to guide creation of valid native packages?
* [ ] Can a VS2015 user install a native package into a classic .NET 4.6 full project, and have unit tests 'just work', I.e, test runners will locate the appropriate native binary at runtime? 
* [ ] Does install and test work under DNX environments?
* [ ] Will native packages ever work on VS2013?

**Comment by moozzyk** [comment] 2015-10-07 19:45
@nathanaeljones - I see. No. This bug is only about being able to consume packages containing native dlls in `dnx` - i.e. we need to make sure that if you have a package that depends on a package that contains native binaries you can just use the `DllImportAttribute` and `dnx` is able to find and load the native library so that you don't have to do it manually. This also should work on other platforms - Linux and Mac OS

Side note - it is possible to create nuget packages containing native binaries even today (examples:[cpprestsdk](https://www.nuget.org/packages/cpprestsdk/), [SignalR C++ client](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client.Cpp.v120.WinDesktop), some [documentation](https://docs.nuget.org/consume/support-for-native-projects)). I have not tried creating a NuGet package containing both native and managed dlls nor have I tried creating a package that contains a native dll that is being consumed by managed code but I think you can make it work just by adding a build step that copies the native dll to the same folder where the managed dll is copied. I believe CLR (`LoadLibrary` invoked by CLR) will try searching for the native dll in the folder where the managed dll with the `DllImportAttributes` is so things should work. This should also work in VS2013. However, the packages with native dlls we will use in dnx will have a different structure - I am not sure if it has been documented yet. As always you can create a package just be creating the right structure in a folder and runing the `nuget pack` command. Again, I assume that you can just add a build step to copy the native lib to the same folder as the managed lib to consume this dll by a manged assembly in non-dnx projects.

**Comment by natemcmaster** [comment] 2015-10-22 19:36
@moozzyk Any updates on this?

**Comment by moozzyk** [comment] 2015-10-22 19:39
@natemcmaster - https://github.com/aspnet/dnx/pull/3049

**Comment by nathanaeljones** [comment] 2015-10-22 19:40
Build steps do not work for ASP.NET or projects with unit tests (which should be all of them!), as those assemblies get left behind by the shadow copier.

**Comment by moozzyk** [comment] 2015-10-26 06:26
Fixed in b9f0af9512fb87f3af89974ff277cd509552be56 and cba17e017ddc118626d7d9e7f99899d3a3782255. 
Related issue #3073

**Closed by moozzyk** 2015-10-26 06:26 UTC
Labels: 2 - Working, design:done, enhancement

**Comment by oryol** [comment] 2016-02-08 12:33
Finally, I didn't understand what should I do to make it works? For example I reference Gtk# package (https://www.nuget.org/packages/GtkSharp.Win32) and target dnx46. When I run project Gtk.Application.Init complains that native library wasn't loaded. May be this package hasn't upgraded to the some new conventions for DNX (as I see it has only old plain MSBuild steps to copy native dll-s). I can update it myself but I need to understand how it can be done?

**Comment by moozzyk** [comment] 2016-02-08 17:40
@oryol - [this](http://blog.3d-logic.com/2015/11/10/using-native-libraries-in-asp-net-5/) might be useful for you (though things are changing in RC2 with dnx being replaced by dotnet)

**Comment by davidfowl** [comment] 2016-02-08 17:42
That will still work in RC2.

**Comment by rmarskell** [comment] 2016-11-09 16:38
@davidfowl Does this still work? I'm trying to create a wrapper library (netstandard1.6) for a C++ dll from another company. I've put the dll files in the appropriate folders (`{project root}/runtimes/win-x64/native/mylib.dll`) and then attempted to reference methods in the library using `[DllImport( "mylib" )]` but it doesn't seem to be finding it. It works if I specify the full path instead of just `"mylib"`, but that's obviously not helpful. Not sure if I'm missing something here or if it has been changed.

**Comment by davidfowl** [comment] 2016-11-09 16:52
No this doesn't work. You need to put it in a package. Or copy it to the output folder on build

**Comment by rmarskell** [comment] 2016-11-09 17:14
Oh, that's a shame, but at least it explains why I couldn't get it to work. Forgive my ignorance, but is there an optimal way to make a post-publish copy script that will have access to the publish architecture (x86/x64) and platform (windows/linux/etc.)?

**Comment by paolo8417** [comment] 2016-11-14 11:27
> You need to put it in a package

@davidfowl , can you explain how ?!

Thanks

**Comment by moozzyk** [comment] 2016-11-14 17:32
@paolo8417 - take a look at [the post](https://blog.3d-logic.com/2015/11/10/using-native-libraries-in-asp-net-5/) I wrote some time ago. This was written before RC1 shipped and some things no longer work the same way but it should give you the general idea. Then look at how we build the libuv package: https://github.com/aspnet/libuv-package
