### ISSUE TITLE
Deploying a project (packed using dnu publish) to IIS fails

### ISSUE THREAD

**Issue by kirthik** [aspnet/dnx#1554] opened 2015-03-31 18:18 UTC
Rutime version: `dnx-clr-win-x86.1.0.0-beta4-11431`
`dnu publish -o C:\ProjectK\PackedProj1 --runtime dnx-clr-win-x86.1.0.0-beta4-11431` to pack the project.
Create a new site in IIS and point its physical location to `wwwroot` of packged project (`C:\ProjectK\PackedProj1\wwwroot`)
Browse to the site and I see following error 
![image](https://cloud.githubusercontent.com/assets/1267650/6925859/5beb22f0-d797-11e4-8ecf-ebc77540e9b9.png)

when I run `dnx . web` from packed project's source(`C:\ProjectK\PackedProj1\approot\src\WebApplication2`), everything works fine.

**Comment by kirthik** [comment] 2015-03-31 18:18
cc @wendywei345, @davidfowl , @muratg

**Comment by davidfowl** [comment] 2015-03-31 18:37
Dupe of https://github.com/aspnet/dnx/issues/1523?

**Comment by ChengTian** [comment] 2015-03-31 18:42
No, this is on **IIS** and there is **no** `--no-source` used

**Comment by davidfowl** [comment] 2015-03-31 18:43
The exception message is the same. I think it's fair to say it's the same bug.

**Comment by ChengTian** [comment] 2015-03-31 18:46
Makes sense. Will add a reminder to test this scenario after #1523 is fixed.

**Closed by ChengTian** 2015-03-31 18:46 UTC
Labels: bug
