### ISSUE TITLE
`kpm.cmd build --quiet` hides real errors and warnings

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#828] opened 2014-10-29 23:17 UTC
This mode should not affect errors and warnings.  For example `--quiet` currently hides warnings about unresolved dependencies.

**Comment by muratg** [comment] 2015-03-10 00:05
What's the error/warning output of other similar tools with "quiet" option? 

/cc: @lodejard @davidfowl

**Comment by dougbu** [comment] 2015-03-10 15:15
@muratg the normal `--quiet` behaviour is to display minimal information but still warnings and errors.  this makes those errors and warnings much more visible.

many tools support distinct `--nologo`, `--quiet`, and `--silent` options for different output levels.  e.g. the latest xUnit runner has [two](https://github.com/aspnet/aspnet.xunit/blob/dev/src/xunit.runner.aspnet/Program.cs#L154-L155) of these.

**Comment by ChengTian** [comment] 2015-07-09 18:12
This was fixed in some previous changes. Couldn't reproduce with latest DNX:
![capture](https://cloud.githubusercontent.com/assets/1383883/8603081/d5a7de80-262a-11e5-972e-86b6d9e952dc.PNG)

We might want to add `--nologo`, which can hide the header print by `dnu`:
```
Microsoft .NET Development Utility CLR-x86-1.0.0-beta6-12189
```
However, as we currently don't find it useful, let's close this for now and reopen the issue when users ask for it explicitly.

**Closed by ChengTian** 2015-07-09 18:12 UTC
Labels: discussion
