### ISSUE TITLE
Issue deleting packages

### ISSUE THREAD

**Issue by sethreidnz** [aspnet/dnx#3401] opened 2016-04-17 21:30 UTC
I get errors during deployments at times when deploying to Azure WebApps:

```
Error: An error was encountered when processing operation 'Delete Directory' on 'D:\home\site\wwwroot\App_Data\jobs\Continuous\****\packages\***\1.1.3'.
Error: The error code was 0x80070091.
Error: The directory is not empty.
at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
at Microsoft.Web.Deployment.DirectoryEx.Delete(String path)
at Microsoft.Web.Deployment.DirPathProviderBase.Delete(Boolean whatIf)
Error count: 1.
```

This can happen with my own packages and also third party ones. Generally restarting the site works but sometimes it doesn't and I get stuck where I cannot delete the folder. I have tried mannually doing it through Azure Kudu tools but to no avail. I found this issue on the Kudu github:

[https://github.com/projectkudu/kudu/issues/1697](https://github.com/projectkudu/kudu/issues/1697)

Which sounds similar and the person there mentioned it sounded like a DNX issue.

I understand that the new aspnet stuff is not fully supported on Azure yet but I'm wondering if this is a known issue or if I am doing something wrong?

**Comment by sethreidnz** [comment] 2016-04-17 21:55
To add to this I have figured out the root problem I think. I am deploying WebJobs as well. My deployment will turn off the web app slot but that does not kill the process that the webjobs are running under. Therefore the files are locked. 

I think that means its not really a DNX issue..

**Comment by muratg** [comment] 2016-04-21 16:26
Closing based on the root cause.

**Closed as completed by muratg** 2016-04-21 16:26 UTC

**Comment by philmh-isams** [comment] 2016-09-07 09:15
@justsayno How do you kill the process the WebJobs are running under - we have the same issue trying to remove some WebJobs; we had to turn on DoNotDelete flag in the interim to get our releases working.

If you redeploy a failed deployment, it works.

**Comment by PrashanthReddyAnnedla** [comment] 2016-09-09 22:45
If we set the DoNotDelete flag then unnecessary files are not being removed, this is causing reference issues for one of my website. Hope there is some solution for this.

**Comment by muratg** [comment] 2016-09-13 17:08
Why are you guys still using DNX? It's obsolete,

**Comment by sethreidnz** [comment] 2016-09-13 22:52
@philmh-isams what @muratg said. However to answer your question more fully. What I did was just put the webjobs into the correct file location (in my web project output) as part of my build process and then published the whole website as a package. This seemed to work.

**Comment by philmh-isams** [comment] 2016-09-26 07:14
@justsayno and @muratg
I am using .NET Core not DNX - sorry for the confusion.
Thanks for the response.

**Comment by steve-warwick** [comment] 2017-01-05 16:23
I'm experiencing the same issue. We are .Net Core. Also, we deploy our web jobs separately from the primary app service they are hosted in. Our VSTS release management deployment attempts to stop the web jobs, stops the app service, deploys the app service, deploys the web jobs, starts the app service and web jobs. During the app service deploy we get this error. I verified the app service isn't running and the web jobs are not running when it attempts the deploy. Has anyone found a solution or workaround for this issue?

**Comment by philmh-isams** [comment] 2017-01-06 07:44
@steve-warwick We have not found one, but DoNotDelete is a suitable workaround for us at present. I would be interested if anyone else has a solution too ;o)
