### ISSUE TITLE
Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' on running project on IIS server.

### ISSUE THREAD

**Issue by 4nonym0us** [aspnet/dnx#2834] opened 2015-09-26 09:06 UTC
The following issue occurs when I try to run the project in VS2015 (OS is Win10, latest dnx tools and .NET framework installed). I've discovered the problem 2-3 days ago. Disregarding this error, I can successfully run my application via `dnx web` command. Any thoughts?
StackTrace is below and screenshot is attached as well.
```
[TypeLoadException: Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9924184
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261
```
![image](https://cloud.githubusercontent.com/assets/2701409/10116715/19563c40-6446-11e5-8450-07f8085200bc.png)
Here is my project.json:
```
{
  "userSecretsId": "***removed***",
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "AutoMapper": "4.0.0-*",
    "MyProject.Core": "1.0.0-*",
    "EntityFramework.Commands": "7.0.0-beta8-*",
    "EntityFramework.Core": "7.0.0-beta8-*",
    "EntityFramework.Relational": "7.0.0-beta8-*",
    "EntityFramework.SqlServer": "7.0.0-beta8-*",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta8-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta8-*",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta8-*",
    "Microsoft.AspNet.Hosting": "1.0.0-beta8-*",
    "Microsoft.AspNet.Identity": "3.0.0-beta8-*",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta8-*",
    "Microsoft.AspNet.Mvc": "6.0.0-beta8-*",
    "Microsoft.AspNet.Mvc.Core": "6.0.0-beta8-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta8-*",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta8-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta8-*",
    "Microsoft.Dnx.Runtime.Abstractions": "1.0.0-beta8-*",
    "Microsoft.Dnx.Tooling": "1.0.0-beta8-*",
    "Microsoft.Dnx.Host.Clr": "1.0.0-beta8-*",
    "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta8-*",
    "Microsoft.Framework.Configuration": "1.0.0-beta8-*",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta8-*",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta8-*"
  },
  "scripts": {
    "postrestore": [ "npm install" ],
    "prepare": [ "grunt dev" ]
  },
  "commands": {
    "ef": "EntityFramework.Commands",
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000",
    "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004"
  },

  "frameworks": {
    "dnx451": { }
  },

  "publishExclude": [
    "node_modules",
    "bower_components",
    "grunt",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components",
    "grunt"
  ]
}
```

**Comment by davidfowl** [comment] 2015-09-26 10:32
Dupe of https://github.com/aspnet/dnx/issues/2790

**Closed by davidfowl** 2015-09-26 10:32 UTC

**Comment by jl32** [comment] 2015-11-20 05:56
In this Dupe of #2790 you said that problem is in Beta8, but I installed 1.0.0-rc1-final and I have the same error:
Can not load type 'Microsoft.Dns.Host.Clr.EntryPoint' the assembly .Dnx.Host.Clr, Version = 1.0.0.0, Culture = neutral, PublicKeyToken = adb9793829ddae60 '.

I put this 
"commands": {
    "web": "Microsoft.AspNet.Server.Kestrel --config hosting.ini",
    "ef": "EntityFramework.Commands" 
  },

**Comment by xblader** [comment] 2015-12-03 23:28
some solution to this? I am facing same error.

**Comment by jl32** [comment] 2015-12-04 02:02
Yes.
I installed WebToolsExtensionsVS14  and this resolved the problem.
You have to select version of dnx.
https://www.microsoft.com/en-us/search/result.aspx?q=WebToolsExtensionsVS14++&form=dlc
good lucky
