### ISSUE TITLE
Issues with System.Net.NetworkInformation on Linux CoreCLR

### ISSUE THREAD

**Issue by roji** [aspnet/dnx#3262] opened 2015-12-15 15:27 UTC
Some users of Npgsql & EF7 have run into issues adding migrations on Linux with CoreCLR, I've managed to narrow it down. I'm not sure how specific this is to System.Net.NetworkInformation or if I'm simply doing something silly...

Basically I have a simple DNX command as follows:

``` c#
namespace Test
{
    public class Program
    {
        public static void Main(string[] args) {}

        static Program() {
            new PhysicalAddress(null);
        }
    }
}
```

The project.json:

``` json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "commands": {
    "test": "Test",
  },

  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Data.Common": "4.0.1-*",
        "System.Runtime": "4.0.21-*",
        "System.Threading": "4.0.11-beta-23516",
        "System.Net.NetworkInformation": "4.1.0-beta-*"
      }
    }
  }
}
```

Running the command with `dnx test` throws the following exception:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.NetworkInformation, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Net.NetworkInformation, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.NetworkInformation'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Test.Program..cctor()
   at Test.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.NetworkInformation'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

On Windows CoreCLR this works great. Any ideas?

**Comment by natemcmaster** [comment] 2015-12-21 19:39
This could be yet-another manifestation of RID-hell. Look in the project.lock.json and see if "runtime.linux.System.Net.NetworkInformation" is present in "libraries"

**Comment by muratg** [comment] 2015-12-21 19:47
What's the DNX version that you're using?  Also, what's in your nuget.config (where are your packages restored when you do `dnu restore`?)

**Comment by friism** [comment] 2015-12-21 20:20
Adding `"runtime.linux.System.Net.NetworkInformation": "4.1.0-beta-*"` in project.json fixes this for me

**Comment by friism** [comment] 2015-12-21 20:31
Here's a repo with full repro: https://github.com/friism/dnx-3262-repro

**Comment by thmulvany** [comment] 2016-01-01 00:15
After adding what friism added I get
`fail: Microsoft.Data.Entity.Query.Internal.NpgsqlQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

**Comment by snissim** [comment] 2016-01-04 01:43
I was able to get it working by explicitly adding this dependency to dnxcore50:

`"runtime.unix.System.Net.Security": "4.0.0-beta-23516"`

Note that it's the `unix` runtime. I know nothing about how these JIT runtime-specific dependencies are resolved, but I assume that `runtime.linux.System.Net.Information` is looking for the equivalent `runtime.linux.System.Net.Security`, which doesn't exist.

**Comment by muratg** [comment] 2016-01-04 18:18
Is this one of the "move to CLI" candidates @anurse?  Or should we close this as no more work is planned on DNX...

**Comment by anurse** [comment] 2016-01-04 18:48
@snissim can you try removing that dependency and adding a dependency on `Microsoft.NETCore.Platforms` instead?

**Comment by muratg** [comment] 2016-01-04 19:41
@anurse right, now that you remind me :)

@snissim I'm pretty sure this would fix your issue.

**Comment by thmulvany** [comment] 2016-01-04 20:54
@anurse , @muratg so are you saying that nothing (no dependency tree) should ever use Sysetm.Net.NetworkInformation or System.Net.Security? Because that is the problem here. @friism was able to repro with a one-line app on Linux but the problem is that other nuget pkgs (e.g. NpgSql for EF7 provider for PostgreSQL) clearly add this dependency to their project.json files. Are you saying they (and everyone) should just add dep for Microsoft.NETCore.Platforms instead and stop using the others? This seems odd since those others are in fact nuget packages and part of base class libraries for .NET Core right?

**Comment by anurse** [comment] 2016-01-04 22:51
You need both, `Microsoft.NETCore.Platforms` and `System.Net.Security` (and/or `System.Net.NetworkInformation`). The "Platforms" package is a special NuGet package that contains additional data used to locate platform-specific implementations.

**Comment by friism** [comment] 2016-02-01 17:05
@anurse adding those dependencies doesn't solve the problem for me: https://github.com/friism/dnx-3262-repro/tree/try-fix

**Comment by DanWahlin** [comment] 2016-02-15 01:55
I'm seeing the same issue as @friism (running 1.0.0-rc2-16357). Everything runs fine on my Mac but breaks going to Linux. I added the `Microsoft.NETCore.Platform`,  `System.Net.NetworkInformation` and `System.Net.Security` references mentioned above in project.json and still get an error about loading NetworkInformation on Linux:

`System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.NetworkInformation, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`

Added "runtime.linux.System.Net.NetworkInformation": "4.1.0-beta-*" and then I get this error:

```
File name: 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Security'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Open()
   ....
```

Tried adding all of these into project.json but still get the System.Net.Security error above.

```
"runtime.linux.System.Net.NetworkInformation": "4.1.0-beta-*",
"Microsoft.NETCore.Platforms": "1.0.1-beta-*",
"System.Net.Security": "4.0.0-beta-*",
"System.Net.NetworkInformation": "4.1.0-beta-*"
```

Any ideas on how to get this going (hoping I need to do something simple or that I'm just missing something simple)? Appreciate it...been hitting wall after wall on this one. App can be found here:

https://github.com/DanWahlin/AspNetCorePostgreSQLDockerApp

**Comment by DanWahlin** [comment] 2016-02-15 02:06
Right after posting I realized I missed @snissim's comment about adding `runtime.unix.System.Net.Security`. Had to add that plus `runtime.linux.System.Net.NetworkInformation`. That fixes it for me. None of the other stuff added above (such as `Microsoft.NETCore.Platforms`) worked though.

Hoping this gets a lot easier in the near future - burned a bunch of time trying to it going on Linux. But, happy I now have that option. :-)

**Closed** 2017-12-17 19:50 UTC
