### ISSUE TITLE
Cannot compile empty project

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2644] opened 2015-09-05 06:28 UTC
We had this in server tests. An empty project.json `{ }`

This used to compile until today. now it fails:

```
info:   commandline: /C dnu pack src\Placeholder --configuration Debug
info:   workingdir: D:\aspnet\servertests
Microsoft .NET Development Utility CLR-x86-1.0.0-beta8-15584


Building Placeholder for DNX,Version=v4.5.1
  Unable to resolve dependency Placeholder 1.0.0

  Using Assembly dependency fx/mscorlib 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\mscorlib.dll

  Using Assembly dependency fx/System 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.dll

  Using Assembly dependency fx/System.Core 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Core.dll

  Using Assembly dependency fx/Microsoft.CSharp 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Microsoft.CSharp.dll


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.5767832
Total build time elapsed: 00:00:00.6055037
Total projects built: 1
warn: Exit code -1 from cmd
```

@davidfowl @anurse  you two had checkins in DNX. One of them might have broken this

**Comment by victorhurdugaci** [comment] 2015-09-05 06:48
This seems to cause some breaks in Entropy too:

https://github.com/aspnet/Entropy/blob/5389de646e0821820df7a7659c6e774ae3396386/samples/Project.Dependencies/project.json

Error:

```
23:40:16][Step 3/5]   Using Package dependency System.Runtime.InteropServices 4.0.20
[23:40:16][Step 3/5]     Source: D:\b\work\9e9b04ab779a9ae1/packages\System.Runtime.InteropServices\4.0.20
[23:40:16][Step 3/5] D:\b\work\9e9b04ab779a9ae1\samples\Project.Dependencies\project.json(5,32): error: The dependency Project.SharedFiles 1.0.0 in project Project.Dependencies does not support framework DNXCore,Version=v5.0.
[23:40:16][Step 3/5]     File: ref\dotnet\System.Runtime.InteropServices.dll
[23:40:16][Step 3/5] 
[23:40:16][Step 3/5]   Using Package dependency System.Text.Encoding 4.0.10
[23:40:16][Step 3/5] D:\b\work\9e9b04ab779a9ae1\samples\Project.Dependencies\Program.cs(8,15): DNXCore,Version=v5.0 error CS0234: The type or namespace name 'SharedFiles' does not exist in the namespace 'Project' (are you missing an assembly reference?)
[23:40:16][Step 3/5]     Source: D:\b\work\9e9b04ab779a9ae1/packages\System.Text.Encoding\4.0.10
[23:40:16][Step 3/5]     File: ref\dotnet\System.Text.Encoding.dll
[23:40:16][Step 3/5] D:\b\work\9e9b04ab779a9ae1\samples\Project.Dependencies\Program.cs(26,13): DNXCore,Version=v5.0 error CS0103: The name 'TaskAsyncHelpers' does not exist in the current context
[23:40:16][Step 3/5] 
[23:40:16][Step 3/5]   Using Package dependency System.Text.Encoding.Extensions 4.0.10
[23:40:16][Step 3/5] Build failed.
```

**Comment by BrennanConroy** [comment] 2015-09-05 06:50
Configuration too: https://github.com/aspnet/Configuration/blob/dev/test/Microsoft.Framework.Configuration.FunctionalTests/project.json

**Comment by davidfowl** [comment] 2015-09-05 06:52
Closing this, it's a braking change but it's by design

**Closed by davidfowl** 2015-09-05 06:52 UTC
