### ISSUE TITLE
Writing breadcrumbs appears to have threading bug

### ISSUE THREAD

**Issue by Eilon** [aspnet/dnx#1771] opened 2015-05-03 06:50 UTC
I'm seeing a lot of errors for several different repos on the internal CI machine with call stacks in the breadcrumb code:

```
[12:15:50] :		 [xunit-test] System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
[12:15:50] :		 [xunit-test]    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
[12:15:50] :		 [xunit-test]    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
[12:15:50] :		 [xunit-test]    at System.Collections.Generic.List`1.Enumerator.MoveNext()
[12:15:50] :		 [xunit-test]    at Microsoft.Framework.Runtime.Servicing.Breadcrumbs.WriteAllBreadcrumbsInternal()
[12:15:50] :		 [xunit-test]    at Microsoft.Framework.Runtime.Servicing.Breadcrumbs.<WriteAllBreadcrumbs>b__13_0(Object _)
[12:15:50] :		 [xunit-test]    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
[12:15:50] :		 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[12:15:50] :		 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[12:15:50] :		 [xunit-test]    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[12:15:50] :		 [xunit-test]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[12:15:50] :		 [xunit-test]    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Looking at the code that manages the breadcrumbs and the data types (e.g. https://github.com/aspnet/dnx/blob/e937e25ab3453ea86bda13c1297c41011dfda9de/src/Microsoft.Framework.Runtime/Servicing/Breadcrumbs.cs#L21), it appears that the code *needs* be thread safe, but isn't.

@victorhurdugaci can you take a look?

(Of course, I'm happy to be wrong about this, but it looks suspicious. I have no particular explanation as to why this would start failing just now.)

**Comment by davidfowl** [comment] 2015-05-03 06:52
Dupe of https://github.com/aspnet/dnx/issues/1733?

**Comment by victorhurdugaci** [comment] 2015-05-03 07:02
That code is not threadsafe because it is not supposed to run on multiple threads. First we build the collection of breadcrumbs to write and only then we write them. Otherwise, we might not write all of them.

I'll investigate on Mon what's wrong and why the writer is running before all adds are done.

Sent from my phone
________________________________

**Comment by Eilon** [comment] 2015-05-03 07:07
@davidfowl Hmm looks similar to that but totally different callstack. The other bug is a file system locking issue, while this is just collection enumeration. The underlying cause might be the same, though.

**Comment by Eilon** [comment] 2015-05-03 07:08
@victorhurdugaci thanks! The only theoretical thing I can think of is that our builds do a lot more in parallel now. However, the parallelization we do is by process (e.g. run multiple builds at the same time), so that might explain the other bug, but wouldn't explain this bug quite so well...

**Closed** 2015-05-06 17:49 UTC
Labels: 2 - Working, bug

**Comment by danroth27** [comment] 2015-06-30 03:55
#1733
