### ISSUE TITLE
project.json should support a way to specify that a dependency must be resolved as a project \ source.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#2249] opened 2015-07-10 23:21 UTC
I ran into this issue as part of the version pinning. `Microsoft.AspNet.Http.Core` had been renamed, but the rename was not captured in a test project (https://github.com/aspnet/HttpAbstractions/blob/release/test/Microsoft.AspNet.WebUtilities.Tests/project.json#L5). This should have caused the test to fail compilation. However since earlier builds of this package are available on nuget.org, the package continued to be restored and the tests succeeded. 

It would be much more reliable if a convention of `"dependency": { 'version': 'version-number', type: 'src' }"` was introduced that takes away the guessing involved in knowing where the contents you're working with came from. We can leave the current behavior as is, but using this would remove packages as a source of resolution for that dependency.

**Comment by davidfowl** [comment] 2015-07-10 23:23
Dupe of https://github.com/aspnet/dnx/issues/438

**Closed by davidfowl** 2015-07-10 23:23 UTC
