### ISSUE TITLE
After Beta 6 Install, New MVC6 Project Fails to Start with "Incompatible Runtime Target Framework"

### ISSUE THREAD

**Issue by MisterJames** [aspnet/dnx#2367] opened 2015-07-28 21:55 UTC
I have installed Beta 6, dnvm is updated and `dnvm upgrade` has been called. My active/default runtime is 1.0.0-beta6. I installed the Visual Studio Beta 6 tooling and rebooted.

I create a new MVC 6 project in VS 2015. Run it...works. 

I modify the project.json to the following:

````
  "frameworks": {
    "dnx46": { }
  },
````

When I save, all the packages happily restore. If I attempt to debug, I get a 500. I get the following error when trying to run without debug:

````
The current runtime target framework is not compatible with 'WebApplication7'.

Current runtime Target Framework: 'DNX,Version=v4.5.1 (dnx451)'
  Type: CLR
  Architecture: x86
  Version: 1.0.0-beta6-12256

Please make sure the runtime matches a framework specified in project.json 
````
I get the same message running `dnx . run` from the solution directory.

From a PS console in my project directory, I get the following when I run `dnu list`:
````
PS C:\Users\James\Documents\Visual Studio 2015\Projects\WebApplication7\src\WebApplication7> dnu list
Microsoft .NET Development Utility CLR-x86-1.0.0-beta6-12256

Listing dependencies for WebApplication7 (C:\Users\James\Documents\Visual Studio 2015\Projects\WebApplication7\src\WebApplication7\project.json)

[Target framework DNX,Version=v4.6 (dnx46)]

Framework references:
(snipped)
````

Here are my installed runtimes (via `dnvm list`):
![image](https://cloud.githubusercontent.com/assets/1197383/8944982/59bfc188-3549-11e5-9c2a-7b419bf614e7.png)

Expected: with the release of Beta6, I thought that dnx46 was supported via an update to the `frameworks` entry in `project.json`, but this does not seem to be working.

Note: This is an easier repro from what I thought I was seeing in #2365

**Comment by anurse** [comment] 2015-07-28 22:06
It's expected that you would see that issue in the web application scenario. There is a Known Issue that the VS Tooling has where it doesn't set an environment variable needed to tell IIS what to launch as. @danroth27 is working on documenting it. Until that is fixed in the tooling you can use the workaround I posted in this [StackOverflow question](http://stackoverflow.com/a/31687529/29813) to launch IIS with the correct framework.

> I get the same message running dnx . run from the solution directory.

This is odd to me because there are two things confusing me about this :). First, you can't run `dnx` from the solution directory, you have to run it from the **project** directory (alongside the `project.json`). Second, the default Web Application template doesn't define the `run` command, it defines `web` and `ef` so you'd have to use `dnx . web` to try this from the command line and WebListener.

It definitely _should_ work in the command line (when you are using `dnx.exe` to boot the runtime). In that case, we have control over the CLR hosting and can launch the correct version.

**Comment by MisterJames** [comment] 2015-07-28 22:10
@anurse Thanks for looking into this. 

When I run `dnx . web` from the command line work, not sure why I had used `run` (other than habit from console apps).

But, `dnx . run` does give the error above :) It's the same error message I get in the browser when I run without debugging.

I'm going to try your workaround now. Thanks again.

**Comment by MisterJames** [comment] 2015-07-28 22:13
@anurse Setting the environment variable `DNX_IIS_RUNTIME_FRAMEWORK` to `dnx46` worked here as well.

I *knew* that there was something along these lines, because everything else seemed to align. Thanks for these tips.

**Comment by jods4** [comment] 2015-07-30 15:56
I have exactly the same problem. 
Running from the command line and `dnx . web` works.
Running in IISExpress from VS 2015 does not (with the exact error message above).
I tried to set the environment variable `DNX_IIS_RUNTIME_FRAMEWORK` to `dnx46` but it makes no difference at all. I checked that the env. variable is set properly using Process Explorer:
![capture](https://cloud.githubusercontent.com/assets/3832820/8988031/45f76600-36e4-11e5-9958-c5b089c63dfb.PNG)

**Comment by anurse** [comment] 2015-07-30 18:54
Have you installed the Beta6 Tooling package? (see http://blogs.msdn.com/b/webdev/archive/2015/07/27/announcing-availability-of-asp-net-5-beta-6.aspx)

**Comment by jods4** [comment] 2015-07-30 20:08
@anurse Yes I did.

**Comment by jods4** [comment] 2015-07-31 16:15
@anurse My project was created in VS Code before VS 2015 RTM, so I figured that maybe there was 
some default value somewhere in the official template that I hadn't gotten right.

And with a brand new ASP.NET project created from VS it worked. 

So I spent a lot of time trying to figure out what was different... not much! In the end, inside `project.json` I changed all my references from `X.0.0-beta6-*`  to `X.0.0-beta6` and after the packages were restored it worked.

**Comment by anurse** [comment] 2015-07-31 16:41
Ah yeah, I think there is a small issue there that `beta6-*` means you'll only get releases from the dev feed (because the released version is `1.0.0-beta6` which is treated as **lower** than `1.0.0-beta6-[anything]`). We've talked about adjusting our versioning scheme to try and make that easier, but for now it's just something to be aware of.

So, it sounds like you've figured out what was wrong, and the original issue has been resolved. I'm going to close this but feel free to keep discussing or re-open it if the issue reoccurs!

**Closed by anurse** 2015-07-31 16:41 UTC

**Comment by jods4** [comment] 2015-09-02 21:28
Reading this in the beta7 announcement:
> When running on the full .NET Framework you can now use the new --framework switch with DNX to specify which .NET Framework version to use (ex. dnx451, dnx452, dnx46).

made me wonder if anything has changed in the tooling / IIS regarding running asp.net 5 on .NET 4.6.
Do we still need to set `DNX_IIS_RUNTIME_FRAMEWORK`?

**Comment by anurse** [comment] 2015-09-02 23:00
Yes, you still need to use the environment variable in IIS, because IIS is the one booting DNX so it needs to provide the framework data.

**Comment by jods4** [comment] 2015-09-02 23:30
OK. Thanks for the info.

**Comment by NiyazShoukath** [comment] 2015-10-22 11:25
i am also same problem in beta 8 ?

please give  any idea

**Comment by Gentlehag** [comment] 2015-11-22 19:20
I got this issue now with rc1 - final and .net 4.6.1

**Comment by YoungjaeKim** [comment] 2015-12-04 02:39
I got same problem with `dnx46` and .net framework 4.6 libraries.

**Comment by davidfowl** [comment] 2015-12-04 03:20
@Gentlehag @YoungjaeKim Can you provide *EXACT* repro steps? Do they match the above? Can you reproduce the problem in a new project?

**Comment by Gentlehag** [comment] 2015-12-04 07:54
Yes I was able to reproduce it with a plain new project and just changing the framework version in the project.json

**Comment by Gentlehag** [comment] 2015-12-14 14:49
Tried it again. Create a new project, change project.json to 461 , doesnt start

so any news on this?

**Comment by valeravorobjev** [comment] 2016-01-12 18:14
ASP.NET 5 app doesn't work if change DNX to 461!!!!

**Comment by andriysavin** [comment] 2016-01-14 19:52
Hi, I have similar issue on 1.0.0-rc1-update1/VS2015 Update1. Here are STR:
1. Create a ASP.NET 5 empty project
2. Remove dnxcore50 from project.json
3. Change dnx451 to dnx46
4. Add a "classic" class library which targets 4.6
5. Build the solution.

I get this warning:

"Warning	MSB3274	The primary reference "<....>\Dnx46BugRepro\ClassLibrary1\bin\Debug\ClassLibrary1.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.1".	Dnx46BugRepro	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	1819"

and this error:

"Error	NU1002	The dependency ClassLibrary1 1.0.0 in project Dnx46BugRepro does not support framework DNX,Version=v4.6.	Dnx46BugRepro	<...>\Dnx46BugRepro\src\Dnx46BugRepro\project.json	19"

**Comment by Maxwe11** [comment] 2016-01-17 00:24
@andriysavin dnx451TFM considered obsolete now so we won't see dnx46 TFM. Instead you should use net46 for targeting .NET 4.6.
References:
https://github.com/aspnet/Announcements/issues/98
https://github.com/dotnet/corefx/issues/4529

**Comment by andriysavin** [comment] 2016-01-17 10:34
@Maxwe11 I've tried that, and got similar warning:

"Warning	MSB3274	The primary reference "<...>\Net46BugRepro\ClassLibrary1\bin\Debug\ClassLibrary1.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.1".	Net46BugRepro	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	1819"

This looks pretty confusing, because I'm obviously targeting 4.6 in my DNX project, NOT 4.5.1 as the warning states.

**Comment by msmolcic** [comment] 2016-02-09 15:56
Any idea when it will be fixed to work with 4.6.1 also?

**Comment by anurse** [comment] 2016-02-09 16:44
What error do you get when you try to use `net461`?

**Comment by msmolcic** [comment] 2016-02-09 18:24
@anurse Application launches, but fails few seconds after with the same output this guy described in his question on SO: http://stackoverflow.com/questions/34817523/asp-net-5-project-not-properly-targeting-net-4-6-1-and-cannot-be-debugged

> 'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.Dnx.Host.Clr'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\msmolcic\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Host.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\msmolcic\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Extensions.PlatformAbstractions.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\msmolcic\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Loader.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\msmolcic\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.ApplicationHost.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\msmolcic\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Runtime.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\msmolcic\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Compilation.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\msmolcic\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Compilation.Abstractions.dll'. Cannot find or open the PDB file.
The program '[7256] dnx.exe: Program Trace' has exited with code 0 (0x0).
The program '[7256] dnx.exe' has exited with code 1 (0x1).
The program '[13548] iisexpress.exe: Program Trace' has exited with code 0 (0x0).
The program '[13548] iisexpress.exe' has exited with code -1 (0xffffffff).

**Comment by superlogical** [comment] 2016-02-25 00:54
Any ideas how to get this running?
