### ISSUE TITLE
--no-source and DNX_PACKAGES does not work together

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnx#1515] opened 2015-03-27 20:33 UTC
When I do a `dnu bundle --no-source` of an app and deploy it on a machine with `DNX_PACKAGES` environment variable set, I see the web application package fails to load with a FileNotFound exception

```
System.IO.FileNotFoundException
The system cannot find the file specified. (Exception from HRESULT: 0x80070002) at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence) at System.Reflection.</span>Assembly.LoadFile(String path)</span></pre>
at Microsoft.Framework.Runtime.Loader.</span>LoadContext.LoadFile<span class="faded">(String assemblyPath)</span></pre>
at Microsoft.Framework.Runtime.Loader.</span>NuGetAssemblyLoader.Load<span class="faded">(String name, IAssemblyLoadContext loadContext)</span></pre>
at Microsoft.Framework.Runtime.Loader.</span>NuGetAssemblyLoader.Load<span class="faded">(String name)</span></pre>
at dnx.host.</span>LoaderContainer.Load<span class="faded">(String name)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at dnx.host.</span>DefaultLoadContext.LoadAssembly<span class="faded">(String name)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at Microsoft.Framework.Runtime.Loader.</span>AssemblyLoaderCache.GetOrAdd<span class="faded">(String name, Func&lt;String, Assembly&gt; factory)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at Microsoft.Framework.Runtime.Loader.</span>LoadContext.LoadAssemblyImpl<span class="faded">(String name)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at Microsoft.Framework.Runtime.Loader.</span>LoadContext.ResolveAssembly<span class="faded">(Object sender, ResolveEventArgs args)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at System.</span>AppDomain.OnAssemblyResolveEvent<span class="faded">(RuntimeAssembly assembly, String assemblyFullName)</span></pre>
[18:32:47][xunit-test] 
[18:32:47][xunit-test]     </div>
[18:32:47][xunit-test] </div>
[18:32:47][xunit-test] <div class="message">
[18:32:47][xunit-test]     <span class="light exception">System.IO.FileNotFoundException</span><br />
[18:32:47][xunit-test]     <span class="heavy">Could not load file or assembly &#x27;MusicStore&#x27; or one of its dependencies. The system cannot find the file specified.</span><br />
[18:32:47][xunit-test]     
[18:32:47][xunit-test]     <div class="stacktrace">
[18:32:47][xunit-test]         <pre><span class="faded">at System.Reflection.</span>RuntimeAssembly._nLoad<span class="faded">(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at System.Reflection.</span>RuntimeAssembly.nLoad<span class="faded">(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at System.Reflection.</span>RuntimeAssembly.InternalLoadAssemblyName<span class="faded">(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at System.Reflection.</span>RuntimeAssembly.InternalLoad<span class="faded">(String assemblyString, Evidence assemblySecurity, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at System.Reflection.</span>RuntimeAssembly.InternalLoad<span class="faded">(String assemblyString, Evidence assemblySecurity, StackCrawlMark&amp; stackMark, Boolean forIntrospection)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at System.Reflection.</span>Assembly.Load<span class="faded">(String assemblyString)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at Microsoft.Framework.Runtime.Loader.</span>LoadContext.Load<span class="faded">(String name)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at Microsoft.Framework.Runtime.Loader.</span>LoadContext.ResolveAssembly<span class="faded">(Object sender, ResolveEventArgs args)</span></pre>
[18:32:47][xunit-test] <br /><pre><span class="faded">at System.</span>AppDomain.OnAssemblyResolveEvent<span class="faded">(RuntimeAssembly assembly, String assemblyFullName)</span></pre>

```

**Comment by Praburaj** [comment] 2015-03-27 20:34
@ChengTian @davidfowl

**Comment by ChengTian** [comment] 2015-03-27 20:54
Nice catch :+1: 

Yes, `DNX_PACKAGES` overrides the packages path in `global.json`. So if you deploy a bundled app to an environment that has `DNX_PACKAGES` set. The bundle will be broken because it won't use `approot/packages`, which contains nupkgs built from dependency projects.

@davidfowl , should we reverse the priority of `DNX_PACKAGES` and `global.json.packages`? Seems "local wins" rule makes more sense and it fixes this problem. Not sure whether this will introduce some regressions.

Or, we should at least show error message like `Unable to load assembly MusicStore.dll from /path/to/expected/package` to make users aware that they are using the wrong packages folder.

**Comment by davidfowl** [comment] 2015-03-27 21:01
Feels like we should do both. Instrument calls to the LoadContext so every call to LoadFile on both CLRs prints the path being loaded.

Lets also change the priority the env var and see what breaks.

/cc @troydai

**Comment by Praburaj** [comment] 2015-03-30 17:52
And it will also be good to review the impact of any other environment variables like `DNX_PACKAGES_CACHE` with `bundle --no-source`.

**Comment by davidfowl** [comment] 2015-03-30 17:59
That one has no negative effects

**Comment by ChengTian** [comment] 2015-05-13 23:11
@davidfowl , this just caused another issue on CI when @BrennanConroy checked in his tests for global install. Do we want to do this in beta5?

**Closed** 2015-12-07 10:24 UTC
Labels: bug, needs design
