### ISSUE TITLE
`dnu sources get` should not unconditionally result in `global.json` reference to cloned repo

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#2350] opened 2015-07-26 19:04 UTC
Copied from aspnet/Tooling-Internal#429 because it's DNX that changes `global.json`.

Changing `global.json` should be an off-by-default option. When on, the result is permanent changes to the solution file, at best longer package restoration and builds, and at worst failed builds.

I expected `dnu sources` to do what its help says -- "Retrieves the source code for packages used by projects". Then I would navigate to the downloaded sources in any solution where I need to debug those classes.

For example, once the MVC repo has been cloned, can:
1. Create a new MVC 6 project from the ASP.NET Web Application / ASP.NET 5 Preview Templates / Web Application template
2. Create a new Function Breakpoint at `Microsoft.AspNet.Mvc.TagHelpers.LinkTagHelper.Process`
3. Create a new Function Breakpoint at `Microsoft.AspNet.Mvc.TagHelpers.ScriptTagHelper.ProcessAsync` (or `Microsoft.AspNet.Mvc.TagHelpers.ScriptTagHelper.Process` if debugging very recent MVC builds)
3. Debug the application
4. When a breakpoint is hit and you're informed the PDB couldn't be found, navigate to whatever the correct location may be. (Hopefully `http://srv.symbolsource.org/pdb/Public` or `http://srv.symbolsource.org/pdb/MyGet` has what you need.)
5. When informed the source file couldn't be found, navigate to the `src\Microsoft.AspNet.Mvc.TagHelpers` directory in the MVC repo.

Observe: The solution is not completely revamped, both breakpoints are successfully hit, and whichever one is hit second does not require manual intervention to find the source file. Things Just Work:tm:

**Comment by davidfowl** [comment] 2015-07-27 01:48
Yea no this isn't that feature. This is about getting source code that you can edit. Symbols is a whole different feature. Dnu symbols get or something

**Comment by dougbu** [comment] 2015-07-27 03:31
My example was just to show debugging working _without_ changing the `global.json` file. The symbols part of it was only a detail.

> no this isn't that feature

The feature I expected is the one that just downloads the source matching a reference in a given project.

> about getting source code that you can edit

If that's the case, why change the current solution? The downloaded repo comes with its own `.sln` file, at least if it's one of the aspnet repos.

**Comment by Eilon** [comment] 2015-07-27 06:49
SLN doesn't work outside of VS.

This is a general purpose DNX feature. It has nothing to do with VS, SLN, ASP.NET, GitHub, or anything else.

The purpose of this feature is to swap a NuGet reference with source code. That's literally all this feature does, and it does exactly that.

**Comment by muratg** [comment] 2015-07-27 17:22
Closing this one as by design.

**Closed by muratg** 2015-07-27 17:22 UTC
