### ISSUE TITLE
Unable to restore packages from a local repo, defined by relative path

### ISSUE THREAD

**Issue by MiguelAlho** [aspnet/dnx#2107] opened 2015-06-19 23:25 UTC
Using a NuGet.config file, package addition and restore works well (as far as I can see) for remote repos and local repos with absolute paths. For relative paths an exception is thrown:

```
System.UriFormatException: Ìnvalid URI : The format of the URI could not be determined.
   in System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
m System.Uri..ctor(String uriString)
   in Microsoft.Framework.PackageManager.PackageSourceUtils.CreatePackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
   in Microsoft.Framework.PackageManager.RestoreCommand.AddRemoteProvidersFromSources(List`1 remoteProviders, List`1 effectiveSources)
   in Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__77.MoveNext()
   (...)
```

Restore is not adding or combining the current directory to the relative path, and therefore failing to build a valid URI. The problem may possibly be limited to the RestoteCommand class.

One interesting aspect - even though restore does not work, intellisense in project.json does and can identify packages and versions available in the folder, through the relative path.

**Comment by natemcmaster** [comment] 2015-07-20 18:40
+1 I'm seeing this issue too on CoreCLR for OS X

**Comment by rowanmiller** [comment] 2015-07-27 21:19
+1 for this. This actually seems to have got worse recently too. I used to be able to have a NuGet.config in my folder structure that had relative paths, provided I cleared the sources for the one in my dnx project. But now it errors out if any of the config files it finds have a relative path, even if those relative paths are later cleared from the source list.

**Comment by anurse** [comment] 2015-07-27 21:59
Dupe of #1150

**Closed by anurse** 2015-07-27 21:59 UTC

**Comment by anurse** [comment] 2015-07-27 22:00
This should be fixed in DNX versions higher than `1.0.0-beta7-12276` (not currently released to the `aspnetvnext` feed but coming soon)

**Comment by davidfowl** [comment] 2015-07-27 22:08
Do relative paths still fail @anurse ?

**Comment by anurse** [comment] 2015-07-27 22:17
No, they work in the upcoming fixed version.
