### ISSUE TITLE
Dependency issue : Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

### ISSUE THREAD

**Issue by radenkozec** [aspnet/dnx#2434] opened 2015-08-07 11:17 UTC
I have a project called "Project1.Data"  which is .NET Core class library project.
Here is a project.json:
```
"dependencies": {
    "Project1.Model": "1.0.0-*",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta6",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta6",
    "Newtonsoft.Json": "7.0.1-beta3"
  },

  "frameworks": {
    "dnx451": {
        "frameworkAssemblies": {
          "System.Net.Http": "",
          "System.Runtime": "",
          "System.Data": ""
        }
    },
    "dotnet": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-23109",
        "System.Runtime": "4.0.20-beta-23109",
        "System.Runtime.Extensions": "4.0.10-beta-23109",
        "System.Net.Http": "4.0.0-beta-23109",
        "System.Data.SqlClient": "4.0.0-beta-23109",
        "System.Data.Common": "4.0.0-beta-23109"
      }
    }
```
When I reference "Project1.Data" dll from artifacts / dotnet folder in my unit test projects and in unit test try to call method from this project  I am getting this exception:
```
Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```
even I have referenced System.Data in dnx451 section. 
All projects successfully build.
Any help to resolve this issue?

**Comment by glennc** [comment] 2015-08-07 17:16
Why is this a dll reference? Is your test project a csproj?

**Comment by radenkozec** [comment] 2015-08-07 18:36
@glennc Yes my test project is csproj. There are few reasons and explanation is complicated. One reason is that I need to run some tests in STAThread environment which was not supported in .NET Core projects and there are few more reasons.
So test project is csproj with xUnit and I reference .NET Core Class Library project from dotnet folder.

**Comment by davidfowl** [comment] 2015-08-09 16:24
You can't reference a csproj -> xproj yet. The support isn't there.

**Comment by radenkozec** [comment] 2015-08-10 08:24
@davidfowl I din't try to do that. I have just checked produce output on build and referenced xproj dll in dotnet folder from my csproj.
That worked great in CTP 6 without any issues.

**Comment by davidfowl** [comment] 2015-08-10 08:25
>  I din't try to do that. I have just checked produce output on build and referenced xproj dll in dotnet folder from my csproj.

The problem is that dependencies of the package won't be copied. This never worked, not even in CTP6, you just got lucky. If you want to include the dependencies, of the class library then you'll need to manually include them in the csproj file.

**Comment by radenkozec** [comment] 2015-08-10 08:33
@davidfowl  My xproj class library project had only 2 other class library dependencies. I have just referenced them also from csproj proj (xunit test project) and everything worked at least in CTP 6.
You think that message 
*Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.*
is somehow related to that?

**Comment by davidfowl** [comment] 2015-08-10 16:16
Does your class library use System.Data.SqlClient?

**Comment by radenkozec** [comment] 2015-08-11 06:19
As you can see from my project.json my xproj class library reference **and use** System.Data.SqlClient.
In my test project (csproj) I have referenced System.Data from Framework 4.5.

**Comment by davidfowl** [comment] 2015-08-11 06:21
Then I have no idea. Upload a minimal runnable sample to github with instructions on how to reproduce

**Comment by radenkozec** [comment] 2015-08-11 08:06
@davidfowl You have minimal runnable sample on my github repository.
https://github.com/radenkozec/SampleError
Instructions to reproduce are in readme file.

Thanks for help David.

**Comment by radenkozec** [comment] 2015-08-14 06:34
@glennc @davidfowl Any news about my issue?
Thanks.

**Comment by davidfowl** [comment] 2015-08-14 06:44
This line is the problem:

https://github.com/radenkozec/SampleError/blob/master/src/Tests.Integration/Tests.Integration.csproj#L38

You're referencing the wrong assembly from the class library. Reference the assembly from dnx451

**Comment by radenkozec** [comment] 2015-08-14 07:12
@davidfowl That resolved issue on this test project thanks. I still don't understand anymore logic there. I have read your suggested article about dnx451, dotnet but now I don't understand how can I reference dnx451 dll from csproj. If I can do that I don't see the point having dotnet section.

However when I changed my production project SQL Issue has been resolved but now I am getting another exception when I run my tests:

*System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Framework.Configuration.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.*


As one person written this is becoming dependency hell.

**Comment by davidfowl** [comment] 2015-08-14 07:38
There's no document explaining it but here's an attempt at trying to simplify it:

dnx4x can consume things that net4x can consume

What this means is that dnx451 is equivalent to .NET Framework 4.5.1. You can reference a .NET Framework 4.5.1 project from a .NET Framework 4.6 project. That's basically what you're doing here. DNX projects have multiple outputs (since nuget packages can have multiple outputs).

The dotnet output in the DNX class library has a bunch of package dependencies including `System.Data.SqlClient` that were missing in your Test project. That's why it was failing.

**Comment by muratg** [comment] 2015-09-09 20:10
Closing as it looks like the root cause was identified. @radenkozec Please file another one if you have more issues with this. Thanks!

**Closed by muratg** 2015-09-09 20:10 UTC

**Comment by psulek** [comment] 2016-05-04 11:45
@radenkozec You help me a lot with those lines:

```
"System.Runtime": "",
"System.Data": ""
```

Thanks a lot!
