### ISSUE TITLE
KPM-built NuGet on Mono pkg throws NotSupportedException when opening in NuGet.Core's OptimizedZipPackage

### ISSUE THREAD

**Issue by xavierdecoster** [aspnet/dnx#649] opened 2014-09-19 19:22 UTC
We can provide a package that demonstrates the issue. It was built with KPM using the following command: ```kpm build```

The symptoms were reported to @MyGet on September 19, 2014, by @viniciuschiele. He should be able to answer any questions you might have regarding how the package was built. The package and a solution reproducing the issue have been emailed to @davidfowl and @jeffhandley (and can be sent over again upon simple request).

Symptoms:
* Opening this in NuGet Package Explorer results in an exception: *“ZIP archive contains unsupported data structures.”*
* Extracting the archive and running nuget.exe pack against the nuspec works without any issues.
* Using NuGet.Core’s OptimizedZipPackage to open the archive throws: *“ZIP archive contains unsupported data structures."*

NuGet.Core's OptimizedZipPackage class is using System.IO.Packaging.Package.Open(path) (from Windowsbase.dll v4.0.0) internally. It is this call that throws the NotSupportedException with the above message. We used NuGet.Core.2.8.3-alpha0001.

The following piece of code reproduces this internal issue:
```csharp
var fullPackagePath = Path.GetFullPath("Aero.ConfigHub.1.0.0.0.nupkg");
using (Stream stream = File.OpenRead(fullPackagePath))
{
    Package package = Package.Open(stream); // throws NotSupportedException
}
```

Diving into the symbols where the exception got thrown, I traced it back to the static ZipArchive.[VerifyVersionNeededToExtract](http://referencesource.microsoft.com/WindowsBase/src/Base/MS/Internal/IO/Zip/ZipArchive.cs.html#15a3d3423bd8d382) method.
When parsing the _rels/.rels, the version parameter at some point has a value of 63, which does not have a matching value in the [ZIPIOVersionNeededToExtract](http://referencesource.microsoft.com/#WindowsBase/src/Base/MS/Internal/IO/Zip/ZipIOVersionNeededToExtract.cs) enum.

![debugging](https://cloud.githubusercontent.com/assets/880728/4340505/dc8b0ce6-402e-11e4-9def-bd9706e5da9a.png)

Looks like the packages produced by NuGet are using different implementations of OptimizedZipPackage, ZipArchive and ZipPackage than the ones being used in K. Perhaps there's some incompatibility there, not sure.

**Comment by davidfowl** [comment] 2015-03-29 04:39
Closing this as by design. The new NuGet 3 API s required to open packages now :smile:

**Closed by davidfowl** 2015-03-29 04:39 UTC
