### ISSUE TITLE
The appbase should not be required

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#1499] opened 2015-03-25 22:32 UTC
Since the `k` script was removed, now you have to type `dnx . <command>` instead of simply `dnx <command>`.

Why can't `dnx` infer the app base from the first argument? If the first argument is a folder assume it is the app base, otherwise `appbase = .`.

**Comment by davidfowl** [comment] 2015-03-25 22:32
This is a dupe of a bug Louis filed

**Closed by davidfowl** 2015-03-25 22:32 UTC
