### ISSUE TITLE
node_modules folder not excluded by dnu publish even though it is part of publishExclude

### ISSUE THREAD

**Issue by balachir** [aspnet/dnx#1925] opened 2015-05-21 19:09 UTC
With beta5 bits and latest tooling, I created a StarterWeb and do a publish to Azure or File System.

ACTUAL
node_modules folder and its contents are included in the output even though there is a publishExclude entry for node_modules in project.json

**Comment by davidfowl** [comment] 2015-05-21 20:21
What versions of things are you using?

**Comment by ChengTian** [comment] 2015-05-21 20:21
Talked to @balachir and he was using beta5-11749.

This was a regression: `dnu publish` was doing `dnu restore` in output folder without skipping restore-related events. But later it was fixed by @davidfowl .

Couldn't reproduce with latest dnx (beta5-11854).

**Closed** 2015-05-21 20:21 UTC
