### ISSUE TITLE
User setting to disable feed takes precedence over local nuget.config.

### ISSUE THREAD

**Issue by ericstj** [aspnet/dnx#1847] opened 2015-05-12 15:48 UTC
It looks like this is inconsistent with nuget.exe.  Example:
- `%AppData%\NuGet\nuget.config` (disables feed http://myfeed) 
- `src\nuget.config` (contains feed http://myfeed)
- `src\myproject\project.json` (references package p from http://myfeed)
- `src\myproject\packages.config` (references package p from http://myfeed).

Nuget.exe restore on packages.config succeeds, but dnu restore on project.json fails.
//cc @ellismg

**Comment by Eilon** [comment] 2015-05-12 16:33
@yishaigalatzer 

Yeah I think this has been a known issue for a while and it's quite unexpected...

**Comment by yishaigalatzer** [comment] 2015-05-12 17:22
I'm actually surprised nuget.exe succeeds here. The feature was that disabling feeds is a global machine level feature

**Comment by ericstj** [comment] 2015-05-12 19:05
I was surprised as well.  At first I thought we were just hitting this because we didn't have -ConfigFile, but I found that even without configfile nuget will honor the user-wide disable.  I can put together a repro if you like.

**Comment by davidfowl** [comment] 2015-05-12 19:11
It's the worst feature ever :smile:

**Comment by yishaigalatzer** [comment] 2015-05-12 19:35
unfortunately - yes it is @davidfowl

**Comment by yishaigalatzer** [comment] 2015-05-12 19:36
So this should be a bug on nuget, dnx seems to behave as expected.

**Comment by ericstj** [comment] 2015-05-12 20:11
I think nuget.exe established this behavior and its used by folks to create an isolated build environment.  I don't think you can punt from dnx if there is some suitable replacement for the isolated environment scenario.  If -configfile is added to DNX and it takes precedence over  %AppData%\NuGet\nuget.config  we'd be OK with punting, though I do imagine that other folks might trip on this.

**Comment by davidfowl** [comment] 2015-05-12 20:13
It can't be punted but it needs to work the same way nuget does. So we need to change both behaviors but I believe the original intent was to let global group policy something override local decisions though I think doing that via a global config file isn't the right way to go about it.

**Comment by ericstj** [comment] 2015-05-19 16:16
Just wanted to refcount this issue again.  I've seen a 5 more reports of folks hitting this since last week.

**Comment by muratg** [comment] 2015-05-21 17:29
@davidfowl @yishaigalatzer what's the plan?  are we changing nuget behavior or both?

**Comment by muratg** [comment] 2015-06-11 20:30
NuGet/dnu work is currently slated to beta 6.

**Comment by anurse** [comment] 2015-06-29 21:13
What's the result here? Are we changing the logic to ensure a true fallback order in both places? I'd want to sync this up with NuGet work (cc @yishaigalatzer) before we make this change. They don't have to be perfectly in sync, but they should be pretty close...

**Comment by pranavkm** [comment] 2015-06-29 22:29
I think NuGet did fix this behavior with priority settings - things closer to CWD do not get overwritten via things further away. @deepakaravindr \ @zhili1208, could you confirm?

**Comment by zhili1208** [comment] 2015-06-29 22:45
Yes, I checked latest version. things closer to CWD do not get overwritten via things further away. @

**Comment by yishaigalatzer** [comment] 2015-06-30 00:40
@zhili1208 can you please double check specifically for disabled feeds?

From what I understand this was a by design decision (alas bad design) because disabling feeds was a desired global behavior. We did not plan on changing the behavior, so how and when did it change?

**Comment by zhili1208** [comment] 2015-06-30 17:46
@yishaigalatzer I think this is changed by this commit https://github.com/NuGet/NuGet3/commit/50443eb4cb0aa53f28d547bba96ed7c504373d66

**Comment by anurse** [comment] 2015-07-14 23:34
Ok, so is this the new desired behavior? If so, DNU needs to be updated to get in sync with it.

**Comment by anurse** [comment] 2015-07-16 17:04
I haven't gotten a clear answer yet, we need to push this to beta7 /cc @muratg

**Comment by muratg** [comment] 2015-07-16 17:16
@yishaigalatzer @davidfowl we have to decide on this asap, and do the changes in either place early in beta 7.

**Comment by anurse** [comment] 2015-08-13 18:33
This is not going to be able to happen without either a) consuming NuGet.Configuration or b) significant changes to our copy of the config code. I don't think it can make beta7 so I'm punting to beta8 (cc @Eilon)

**Comment by anurse** [comment] 2015-09-24 17:00
This is not going to happen in beta8. It's pushing it a bit to pull it to RC1, but we're blocked on a NuGet bug (#1427) and there is debate over whether we should do it. /cc @muratg @davidfowl

**Comment by muratg** [comment] 2015-09-24 17:03
Tentatively putting this in RC1. If we decide we're not going to do this, we'll just close.

**Comment by anurse** [comment] 2015-09-24 17:16
I don't think not doing it is really a good option. Our behavior **should** be in sync with NuGet.

**Comment by pranavkm** [comment] 2015-09-25 12:42
Slightly tangential - once we switch to using NuGet.Configuration we'll lose out on `NuGet.redirect.config`.

**Comment by muratg** [comment] 2015-09-25 15:30
@anurse agreed. Looks like nuget/home/1427 will be fixed "soon".

**Closed** 2017-02-19 08:57 UTC
Labels: 1 - Ready, bug, Move to NuGet
