### ISSUE TITLE
Types from an indirect dependency creating conflicts.

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dnx#2391] opened 2015-08-01 21:55 UTC
For some reason types from a dependency that I'm not directly referencing - System.Reflection.TypeExtensions - are accessible in my project and are generating conflicts with my own types with a matching name. Is this new behavior? I don't remember having this problem in the past. I'm using beta 6.

---

I'm referencing Microsoft.CSharp. Microsoft.CSharp references System.Reflection.TypeExtensions. Compiler imports types from System.Reflection.TypeExtensions and generates conflicts, even through I don't want anything from System.Reflection.TypeExtensions.

**Comment by davidfowl** [comment] 2015-08-02 16:21
Can you make a repo project? It's hard to know what conflict means without seeing version numbers and compilation errors.

**Comment by JamesNK** [comment] 2015-08-02 22:58
What I'm seeing is types from System.Reflection.TypeExtensions being available in a project even though it is not a dependency. A new default class library references Microsoft.CSharp. System.Relfection.BindingFlags resolves even though System.Reflection.TypeExtensions is not a dependency.

**Comment by davidfowl** [comment] 2015-08-02 23:00
Dependencies are transitive by default.

**Comment by JamesNK** [comment] 2015-08-02 23:06
Isn't that dangerous? If Json.NET depends on System.ComponentModel.TypeConverters and an application or library depends on Json.NET and uses TypeConverters without directly depending on it, what happens if I then remove the dependency to System.ComponentModel.TypeConverters? Won't the application now fail to compile and break?

**Comment by davidfowl** [comment] 2015-08-02 23:08
Dangerous? It's the way nuget always worked. When you install a package today you get the full closure added to your project. It's no different with `project.json`. That said, there is a plan to allow for private dependencies but it's not implemented as yet and probably won't be for v1.

**Comment by JamesNK** [comment] 2015-08-02 23:20
Today a dependency's dependency will explicitly be added to a csproj's references and packages.config.

e.g. PayPalCoreSDK uses Json.NET. Adding the PayPal package will add both the paypal and Newtonsoft.Json dll to the csproj's references and packages.config

If PayPal stops using Newtonsoft.Json in a future version, upgrading to the newer package won't remove Newtonsoft.Json from the csproj or packages.config.

With the new project.json, upgrading to the newer package will result in no reference to Newtonsoft.Json. The application will no longer compile.

Correct me if I'm wrong here.

**Comment by davidfowl** [comment] 2015-08-02 23:32
> Today a dependency's dependency will explicitly be added to a csproj's references and packages.config.

Correct, assemblies are non transitive but the act of installing via nuget will make it transitive. In the project.json world, this happens by default by just referencing the top level dependency.

> If PayPal stops using Newtonsoft.Json in a future version, upgrading to the newer package won't remove Newtonsoft.Json from the csproj or packages.config.

It will if no other package is using Newtonsoft.Json.

>  With the new project.json, upgrading to the newer package will result in no reference to Newtonsoft.Json. The application will no longer compile.

That's correct. If the application didn't depend on Newtonsoft.Json directly, it will break.

**Comment by JamesNK** [comment] 2015-08-02 23:42
> It will if no other package is using Newtonsoft.Json.

Doesn't it prompt you? I just tested uninstalling and I got a prompt asking whether to also uninstall Newtonsoft.Json.

> That's correct. If the application didn't depend on Newtonsoft.Json directly, it will break.

That seems pretty dangerous. Any app or library that uses BindingFlags out of TypeExtensions but doesn't have an explicit dependency would break if Microsoft.CSharp was refactored to no longer depend on it.

**Comment by davidfowl** [comment] 2015-08-03 11:20
It's by design. Private dependencies will allow you to do what you want but that's not the default.

**Comment by davidfowl** [comment] 2015-08-07 08:05
Closing this issue out as its by design.

**Closed by davidfowl** 2015-08-07 08:05 UTC
