### ISSUE TITLE
DNX list prints the text LibraryDescription instead of useful information

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnx#1641] opened 2015-04-13 15:19 UTC
```
Listing dependencies for xunit.execution.AspNet (D:\xunit\src\xunit.execution.AspNet\project.json)

[Target framework DNX,Version=v4.5.1 (dnx451)]

  framework/Microsoft.CSharp 4.0.0.0
    -> Microsoft.Framework.Runtime.LibraryDescription
  framework/mscorlib 4.0.0.0
    -> Microsoft.Framework.Runtime.LibraryDescription
  framework/System 4.0.0.0
    -> Microsoft.Framework.Runtime.LibraryDescription
  framework/System.Collections 4.0.0.0
    -> Microsoft.Framework.Runtime.LibraryDescription
  framework/System.Core 4.0.0.0
    -> Microsoft.Framework.Runtime.LibraryDescription
  framework/System.Diagnostics.Debug 4.0.0.0
    -> Microsoft.Framework.Runtime.LibraryDescription
```

**Comment by BrennanConroy** [comment] 2015-04-13 15:45
dupe of #1637

**Closed by BrennanConroy** 2015-04-13 15:45 UTC
Labels: bug, duplicate
