### ISSUE TITLE
Error for PCL v4.0 Profile 6 + async

### ISSUE THREAD

**Issue by anfomin** [aspnet/dnx#2180] opened 2015-07-02 18:22 UTC
I've this `project.json`:
```JSON
{
	"dependencies": {
		"Microsoft.Bcl.Async": "1.0.168"
	},

	"frameworks": {
		".NETPortable,Version=v4.0,Profile=Profile6": {
			"frameworkAssemblies": {
				"mscorlib": "",
				"System": "",
				"System.Core": ""
			}
		}
	}
}
```

When I try to compile anything with `await Task` I get error:
> The type 'Task' exists in both 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'

However old cproj-project can compile this.

Sample: https://github.com/anfomin/DNX-PCL-test/tree/master/PCL6

**Comment by muratg** [comment] 2015-07-06 17:34
@anurse

**Comment by anurse** [comment] 2015-07-06 18:42
I can take a look. It is highly likely that this and #2182 are the same underlying issue.

**Comment by anurse** [comment] 2015-07-09 19:00
I have a fix for this. The issue is in our framework matching code. We're picking the ` lib\portable-net40+sl40+win8` folder from `Microsoft.Bcl.Async` when we should be using `lib\portable-net40+win8`. PR to come shortly

**Closed** 2015-07-10 18:54 UTC
