### ISSUE TITLE
The aliases made by "build dev-install" don't work

### ISSUE THREAD

**Issue by lodejard** [aspnet/dnx#1427] opened 2015-03-17 20:52 UTC
it's calling `dnvm alias {0} {1}` where the `{1}` is given a full runtime name instead of just the version.

This results in an `alias\clr-win-x86-dev.txt` file containing `dnx-clr-win-x86.dnx-clr-win-x86.1.0.0-dev` instead of `dnx-clr-win-x86.1.0.0-dev`

correct syntax is `dnvm alias {0} {1} -runtime {2} -arch {3}` where `{1}` is the version, `{2}` is the runtime, and `{3}` is the alias

alternatively, the dev-install target could simply write out the alias txt file instead of shelling out to dnvm

**Comment by anurse** [comment] 2015-03-18 00:47
Dupe of https://github.com/aspnet/dnvm/issues/174

**Comment by anurse** [comment] 2015-03-18 01:01
Well, maybe not a dupe, but I've got a fix for the other one anyway. This was a regression in dnvm from kvm, so it's probably good to fix.

**Comment by victorhurdugaci** [comment] 2015-03-18 16:06
It is a dupe and that's a bug in dnvm.

**Comment by muratg** [comment] 2015-03-19 17:17
Closing as dup. Victor will be doing more ET on dnvm and fix remaining regressions.

**Closed by muratg** 2015-03-19 17:17 UTC
