### ISSUE TITLE
Improve KPM error messages when failing to resolve a source

### ISSUE THREAD

**Issue by chlowell** [aspnet/dnx#1271] opened 2015-02-24 18:55 UTC
Using the latest WTE with WPT 22624, package restore fails when a GET from one source returns an error response, even if packages can be retrieved successfully from another source. This happens when a source returns 404 or its URL is invalid, etc. For example, this is the package manager output from a restore on a fresh console app configured with an invalid source URL:

```
 GET https://www.myget.org/f/aspnetvnext/api/v2/FindPackagesById()?Id='System.IO'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.IO'.
  GET http://packagesource/FindPackagesById()?Id='System.IO'.
  GET https://www.myget.org/f/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime'.
  GET http://packagesource/FindPackagesById()?Id='System.Runtime'.
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime' 895ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.IO' 1283ms
  OK https://www.myget.org/f/aspnetvnext/api/v2/FindPackagesById()?Id='System.Runtime' 1307ms
  OK https://www.myget.org/f/aspnetvnext/api/v2/FindPackagesById()?Id='System.IO' 1439ms
Warning: FindPackagesById: System.Runtime
  An error occurred while sending the request.
Warning: FindPackagesById: System.IO
  An error occurred while sending the request.
  GET http://packagesource/FindPackagesById()?Id='System.Runtime'.
  GET http://packagesource/FindPackagesById()?Id='System.IO'.
Warning: FindPackagesById: System.IO
  An error occurred while sending the request.
Warning: FindPackagesById: System.Runtime
  An error occurred while sending the request.
  GET http://packagesource/FindPackagesById()?Id='System.IO'.
  GET http://packagesource/FindPackagesById()?Id='System.Runtime'.
Error: FindPackagesById: System.Runtime
  An error occurred while sending the request.
Error: FindPackagesById: System.IO
  An error occurred while sending the request.
----------
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'packagesource'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.HttpSource.<GetAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.NuGetv2Feed.<FindPackagesByIdAsyncCore>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass81_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass94_0`1.<<ForEachAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__81.MoveNext()
----------
Restore failed
An error occurred while sending the request.
```

If the offending source is disabled or removed, restore will succeed.

**Comment by davidfowl** [comment] 2015-02-26 02:26
What's the bug?

**Comment by chlowell** [comment] 2015-02-26 18:56
An error retrieving packages from one source causes restore to fail despite successful communication with other sources offering the required packages.

**Comment by davidfowl** [comment] 2015-03-01 04:07
Thats by design. Use kpm restore --ignore-failed-sources.

**Comment by chlowell** [comment] 2015-03-02 19:38
Ah, I see. ```kpm restore --ignore-failed-sources``` does work here. Is the plan to change the messaging in future, replacing stack trace with usage instructions?

**Comment by glennc** [comment] 2015-03-05 00:07
We can investigate making it easier to discover `ignore-failed-sources` with some polishing of the the error or something. Changing the title to reflect that and assigning it to a milestone.

**Comment by dsplaisted** [comment] 2015-03-12 21:52
This failure also occurs if the package source is available but it returns a 404 for any of the packages.  That means if I were to set up a private feed I would have to re-host all of the packages that I depend on from the public feed, instead of just putting the private packages I've built on that feed.

Is this the intended behavior?  This is quite a big change from how multiple feeds have worked in NuGet until now.

**Comment by davidfowl** [comment] 2015-07-07 07:48
@dsplaisted What package source returns a 404 for missing packages? In the v2 protocol it usually returns an empty data set.

**Comment by dsplaisted** [comment] 2015-07-07 20:19
@davidfowl I think MyGet was returning 404 for missing packages when we ran into this.

**Comment by davidfowl** [comment] 2015-07-10 10:42
It doesn't and if it did that was a bug.

**Comment by davidfowl** [comment] 2015-12-07 09:59
I believe we fixed this

**Closed by davidfowl** 2015-12-07 09:59 UTC
Labels: polish
