### ISSUE TITLE
Dnu install fails

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnx#2254] opened 2015-07-13 18:52 UTC
Run this on a project:

`dnu install Microsoft.AspNet.Hosting 1.0.0-beta5 --source "https://www.myget.org/F/aspnetvnext/api/v2" --source "https://nuget.org/api/v2/" --no-cache`

Result:

```
Microsoft .NET Development Utility CLR-x86-1.0.0-beta6-12208

  GET https://www.myget.org/F/aspnetvnext/api/v2/
  OK https://www.myget.org/F/aspnetvnext/api/v2/ 843ms
  GET https://nuget.org/api/v2/
  OK https://nuget.org/api/v2/ 691ms
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?id='Microsoft.AspNet.Hosting'
  GET https://nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNet.Hosting'
  OK https://nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNet.Hosting' 218ms
  OK https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?id='Microsoft.AspNet.Hosting' 892ms
Microsoft.AspNet.Hosting.1.0.0-beta5 was added to project.json.
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__1`1.MoveNext()
   at Microsoft.Framework.PackageManager.RestoreCommand.<Execute>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.InstallCommand.<ExecuteCommand>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.InstallConsoleCommand.<>c__DisplayClass0_0.<<Register>b__1>d.MoveNext()
```

**Comment by muratg** [comment] 2015-07-14 17:24
@ChengTian any ideas?

**Comment by ChengTian** [comment] 2015-07-14 17:52
Looks like a regression. Investigating.

**Comment by ChengTian** [comment] 2015-07-14 19:08
This regression makes `dnu install` unusable, should be fixed ASAP.

**Comment by muratg** [comment] 2015-07-14 19:10
Agreed

**Closed** 2015-07-14 23:05 UTC
Labels: 3 - Done, bug
