### ISSUE TITLE
inlcuding package in dependencies part of project.json

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#3113] opened 2015-11-02 15:06 UTC
_From @OlegKi on November 2, 2015 6:22_

I posted [the pull request](https://github.com/aspnet/Mvc/pull/3456) before, but the answers reduced my suggestion to successful building of MVC beta8. Thus I open better new issues with the following question:
- **Which packages should be included in `"dependencies"` part of `project.json`?**

[The line 308](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/Compilation/RoslynCompilationService.cs#L308) of `RoslynCompilationService.cs` of `Microsoft.AspNet.Mvc.Razor.xproj`  **uses directly** enum `PEStreamOptions.PrefetchMetadata` from the namespace `System.Reflection.PortableExecutable`, defined in [System.Reflection.Metadata](https://www.nuget.org/packages/System.Reflection.Metadata/). Thus I correct to *_include *_ `System.Reflection.Metadata` in `dependencies` part of `project.json`. I suggest to add the following line

```
    "System.Reflection.Metadata": "1.1.0-*"
```

**Please explain the common rule of including packages in `dependencies` part of `project.json`.** Should one include all packages referenced _directly_ in the code or not?

_Copied from original issue: aspnet/Mvc#3459_

**Comment by dougbu** [comment] 2015-11-02 15:06
The choice of which dependencies to list beyond the minimum needed for correct compilation and execution is a developer's choice. In most of the ASP.NET 5 / MVC 6 / EF 7 codebase, we have chosen to list _only_ the minimum required. We have occasionally double-checked listed dependencies and removed those referenced transitively.

**Comment by dougbu** [comment] 2015-11-02 15:06
_From @OlegKi on November 2, 2015 9:28_

Sorry, but "double-checked listed dependencies" seems to me not a strong enough rule. By examining of **the current** dependencies you suppose that **the next version** of all the dependencies will stay *the same*. If one follow the rule then the project can be broken after publishing one new version from direct or indirect depended package. Moreover I can imagine that the existing rules of resolving dependencies produce different results depend on the order of recursive resolving of dependencies.

The analyse of `project.lock.json` shows that `System.Reflection.Metadata` is included (currently) in the 4-th level of dependencies of `Microsoft.AspNet.Razor.Runtime.Precompilation` and `Microsoft.Dnx.Compilation.CSharp.Common`. To be exact one have
```
"Microsoft.AspNet.Razor.Runtime.Precompilation/4.0.0-beta8"
  "Microsoft.Dnx.Compilation.CSharp.Abstractions/1.0.0-beta8"
    "Microsoft.CodeAnalysis.CSharp/1.1.0-beta1-20150928-02"
      "Microsoft.CodeAnalysis.Common/1.1.0-beta1-20150928-02"
        "System.Reflection.Metadata": "1.1.0-alpha-00014"

"Microsoft.Dnx.Compilation.CSharp.Common/1.0.0-beta8"
  "Microsoft.Dnx.Compilation.CSharp.Abstractions/1.0.0-beta8"
    "Microsoft.CodeAnalysis.CSharp/1.1.0-beta1-20150928-02"
      "Microsoft.CodeAnalysis.Common/1.1.0-beta1-20150928-02"
        "System.Reflection.Metadata": "1.1.0-alpha-00014"
```
together with **direct** dependency to `System.Reflection.Metadata` (in version >= 1.1.0-* or >= 1.\*.\*-* probably). Thus publishing of **any new version of**  `Microsoft.Dnx.Compilation.CSharp.Abstractions`, `Microsoft.CodeAnalysis.CSharp`, `Microsoft.CodeAnalysis.CSharp` or `Microsoft.CodeAnalysis.Common` can break the dependency to `System.Reflection.Metadata`. Isn't so?

I formulate my question as common question about including dependencies in `package.json`. The project `Microsoft.AspNet.Mvc.Razor.xproj` is just an example. Probably placing the question to https://github.com/aspnet/Mvc was wrong and it would be better to place it in some other repository of https://github.com/aspnet (but which one)?

Sorry, but I don't understand why one not includes **all modules, which will be used directly** in the project. It's not really important, whether the list will contains 9 packages or 90. One can use tools, which scan source code for dependencies (like ReSharper) or which examine the final binary (like IDL, or Fuslogvw.exe, ildasm.exe, NetReflector and so on) to scan for direct dependencies. One can create the tools and include there in the SDK.

**It seems that the state of cached packages from `%userprofile%\.dnx` influence the current building process.** It's very dangerous! The request to NuGet repository(s) about metadata information of all direct (or even indirect) used packages could work quick enough. The backend (NuGet service) could makes the resolution of all dependencies based on the metadata of all dependent packages published on NuGet. Why one don't make the request(s) first of all? Only after building the full list of dependencies, *based on the latest information from NuGet*, one can uses packages from the cache, but only if **the exact versions** are already cached. Such building process will be free from side effect from existing of old version of packages in the cache (on `%userprofile%\.dnx`).

**Comment by OlegKi** [comment] 2015-11-02 15:15
One additional information, which I found out. There are an important difference in the usage of **direct dependence** `"System.Reflection.Metadata":  "1.1.0-*"` included in `"dependencies"` part of `project.json`. After adding the rule one can examin `project.lock.json` and see:
```json
{
...
      "Microsoft.AspNet.Mvc.Razor/6.0.0-beta8": {
          ...
          "System.Reflection.Metadata": "1.1.0-alpha-00014"
      },
      "Microsoft.CodeAnalysis.Common/1.1.0-beta1-20150928-02": {
          ...
          "System.Reflection.Metadata": "1.1.0-alpha-00014"
      },
      "System.Reflection.Metadata/1.1.0": {
        "type": "package",
        "dependencies": {
          "System.Collections": "4.0.0",
          "System.Collections.Immutable": "1.1.37",
          "System.Diagnostics.Debug": "4.0.0",
          "System.IO": "4.0.0",
          "System.Reflection": "4.0.0",
          "System.Reflection.Extensions": "4.0.0",
          "System.Reflection.Primitives": "4.0.0",
          "System.Resources.ResourceManager": "4.0.0",
          "System.Runtime": "4.0.0",
          "System.Runtime.Extensions": "4.0.0",
          "System.Runtime.InteropServices": "4.0.0",
          "System.Text.Encoding": "4.0.0",
          "System.Text.Encoding.Extensions": "4.0.0",
          "System.Threading": "4.0.0"
        },
        "compile": {
          "lib/dotnet5.2/System.Reflection.Metadata.dll": {}
        },
        "runtime": {
          "lib/dotnet5.2/System.Reflection.Metadata.dll": {}
        }
      },
...
}
```
I interpret the results as following: the project use the newest version `1.1.0` of `System.Reflection.Metadata` even if other dependencies like `Microsoft.AspNet.Mvc.Razor` required `1.1.0-alpha-00014` (or higher). Without the usage direct dependency it seems be used old `1.1.0-alpha-00014` version.

**Comment by OlegKi** [comment] 2015-11-02 15:34
After moving the issue I'm not sure that all required information will be easy found by other users. Thus I repeat the following, which I find inportant result of my analyse:

Like I wrote in [the comment](https://github.com/aspnet/Mvc/pull/3456#issuecomment-153043975) to the pull request, the building process of many projects faild with the error: "System.Reflection.Metadata.dll" will be not found in `dnx\packages\System.Reflection.Metadata\1.1.0-alpha-00014\lib\dotnet` folder. The folder `1.1.0-alpha-00014\lib` really contains only `portable-net45+win8` subdirectory and no `dotnet` folder. After including of *direct* dependency `"System.Reflection.Metadata": "1.1.0-*"` in all projects, which build failed, one can see that the *new* `1.1.0` version of `System.Reflection.Metadata.dll` be used and the folder `.dnx\packages\System.Reflection.Metadata\1.1.0\lib` contains now **two** subdirectories: `portable-net45+win8` and `dotnet5.2`. It seems solves the probelm with building MVC projects.

Thus including of direct dipendency seems to produce **another results** in the building process.

**Comment by dougbu** [comment] 2015-11-02 16:30
Don't mix an issue with building the MVC solution in your environment into your other points here. I can't reproduce that issue and it does not relate to whether or not we should avoid transitive dependencies.

**Comment by OlegKi** [comment] 2015-11-02 16:55
How you can comment the existence of folders `dotnet5.2`and `portable-net45+win8` in `System.Reflection.Metadata\1.1.0\lib` and the existence of only one `portable-net45+win8` folder in `1.1.0-alpha-00014\lib``?

Which version in your opinion would be **correct** in building MVC project today: `1.1.0-alpha-00014` or the latest currently existing on NuGet `1.1.0`?

Do you tried to add direct dependency "System.Reflection.Metadata": "1.1.0-*" in some project and verify `project.lock.json` that the resulting assemble will use version `1.1.0` instead of the usage `1.1.0-alpha-00014` before? The test is independent from the problem of reproducing the error
```
25>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(166,5): error : The design time host build failed with the following error: Ein Teil des Pfades "C:\Users\Oleg\.dnx\packages\System.Reflection.Metadata\1.1.0-alpha-00014\lib\dotnet\System.Reflection.Metadata.dll" konnte nicht gefunden werden.
```
which I reported before.

I believe you of cause, that you can't reproduce the problem, but I'm sure that I will be not the only person, who will have the same problems in the future. Thus I suggest to analyse the problem exactly. What you need to know about my environment? I can provide you any information, and I can do any tests. I can send you any log files, traces of Process Explorer and so on. In any way the issue exist and I can help you to locale the reason of the problem.

**Comment by OlegKi** [comment] 2015-11-02 17:17
One more additional information, which seems to me important for localizing of error during building of MVC project: I downloaded `1.1.0-alpha-00014` version of `System.Reflection.Metadata` from [NuGet](https://www.nuget.org/packages/System.Reflection.Metadata/1.1.0-alpha-00014) and examined the metadata. I can see that it contains **both** subfolders `dotnet` and `portable-net45+win8`. I exmined the metadara of `System.Reflection.Metadata.1.1.0-alpha-00014.nupkg` from `C:\Users\Oleg\.dnx\packages\System.Reflection.Metadata\1.1.0-alpha-00014` and I see **another package** which don't have `dotnet` folder. I will try to analyse which NuGet repository contains wrong package and will write you the information later.

**Comment by Eilon** [comment] 2015-11-02 17:18
@OlegKi the version of this package on MyGet's aspnetmaster feed was broken and I fixed it ~12 hours ago. You'll need to clear your package cache to get the fixed one to be downloaded.

**Comment by OlegKi** [comment] 2015-11-02 19:21
@Eilon : Thank you for the information. I reset my copy of local .dnx aproximately in the same time when you fixed the package `System.Reflection.Metadata.1.1.0-alpha-00014.nupkg`. If you would inform me directly I could save some hours. Nevertherless I can confirm that I get now **new** `System.Reflection.Metadata.1.1.0-alpha-00014.nupkg` package (with both `dotnet` and `portable-net45+win8` folders). Now the building of MVC beta8 is successfuly.

@Eilon and @dougbu :
Now we can come back to my question in the issue: *which version should be used during building of MVC project after publishing of final 1.1.0 version of `System.Reflection.Metadata`: old `1.1.0-alpha-00014` or new `1.1.0-alpha-00014`?*

Why one have **different results** if one would include *direct dependency* `"System.Reflection.Metadata": "1.1.0-*"` to `Microsoft.AspNet.Mvc.Razor` project for example? I made just now the test and compared the changes in `project.lock.json`. I can see that after including direct dependency `Microsoft.AspNet.Mvc.Razor` uses
 - `System.Reflection.Metadata` version `1.1.0` instead of `1.1.0-alpha-00014` before
 - `System.Collections.Immutable` version `1.1.37` instead of `1.1.36` before
 - new `System.Globalization` version `4.0.0` are added because of usage `1.1.37` instead of `1.1.36` version of `System.Collections.Immutable`
 - new `System.Link` version `4.0.0` are added because of usage `1.1.37` instead of `1.1.36` version of `System.Collections.Immutable`

It shows that removing of dependences ("to list beyond the minimum needed for correct compilation" see comment of dougbu) produces **another results**. If we speak about "correct compilation" then it's interesting to aks what version `1.1.0` or `1.1.0-alpha-00014` would be **correct** (or better) to use? One can see that optimization of dependencies produce side effects. One can see that `1.1.0-alpha-00014` will be used even if the final `1.1.0` exist in local cache if we don't include `System.Reflection.Metadata` as the direct dependency.

**Closed** 2017-12-17 19:50 UTC
