### ISSUE TITLE
DNX Crashing on NanoServer

### ISSUE THREAD

**Issue by gazzyt** [aspnet/dnx#2129] opened 2015-06-25 15:58 UTC
I am trying to run a simple asp.net app on Windows Nanoserver TP2 but whenever I run dnx it crashes with the error:
dnx.onecore.dll could not be loaded. Last error: 126

I have tried with the following builds:
dnx-coreclr-win-x64.1.0.0-beta5-12103
dnx-coreclr-win-x64.1.0.0-beta6-12114
dnx-coreclr-win-x64.1.0.0-beta6-12120

I have the Microsoft-OneCore-ReverseForwarders-Package package installed in my NanoServer VM running on Hyper V.

I was trying to follow this post:
http://www.itwriting.com/blog/9192-running-asp-net-5-0-on-nano-server-preview.html
But the beta5 build he used is no longer available in the feed.

I have not found much on the web about doing this so not sure if a defect or I am doing something wrong.

Gary

**Comment by muratg** [comment] 2015-06-25 16:02
@moozzyk @victorhurdugaci

**Comment by victorhurdugaci** [comment] 2015-06-25 16:42
Bug confirmed. We have a repro: https://xplat-ci.asp.net/viewLog.html?buildId=1340&buildTypeId=XPlat_Windows_WinNanoServer_MusicStore&tab=buildLog

**Comment by moozzyk** [comment] 2015-06-25 16:50
Looks like VCRuntime140.dll is missing from the folder.

**Comment by gazzyt** [comment] 2015-06-26 10:04
@moozzyk good catch! I copied VCRuntime140.dll into the folder containing dnx on the nanoserver and dnx now launches successfully. So your diagnosis is spot on.

Thanks for the quick response.

Gary

**Comment by moozzyk** [comment] 2015-06-26 13:50
Thanks for confirming. I need to check why it was not copied during build in the first place...

**Comment by moozzyk** [comment] 2015-06-26 17:28
A setting on the CI had a typo. It should be fixed now and the next build will have VCRuntime.dll

**Closed by moozzyk** 2015-06-26 17:28 UTC
Labels: bug

**Comment by dmetzgar** [comment] 2015-07-30 00:45
@gazzyt I'm having the same problem. Where did you get a version of vcruntime140.dll that is built for onecore?

**Comment by gazzyt** [comment] 2015-07-30 10:45
I found it in artifacts\bin\{ProjectName}\Release\Publish\approot\runtimes\dnx-coreclr-win-x64.1.0.0-beta6-12120\bin under my project folder.
