### ISSUE TITLE
dnx 4.5.1 failing with System.IO.PathTooLongException

### ISSUE THREAD

**Issue by jpoehls** [aspnet/dnx#2179] opened 2015-07-02 17:10 UTC
I'm not sure what changed since I swear my project was building yesterday and today magically doesn't. Here's the error. Any ideas? I've moved my project to `c:\pts` and it doesn't get much shorter than that.

I'm on DNVM 1.0.0-beta4 still. DNX version 4.5.1.

```
PS> dnvm list

Active Version           Runtime Architecture Location                       Alias
------ -------           ------- ------------ --------                       -----
       1.0.0-beta4       clr     x64          C:\Users\jpoehls\.dnx\runtimes
  *    1.0.0-beta4       clr     x86          C:\Users\jpoehls\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\jpoehls\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\jpoehls\.dnx\runtimes
       1.0.0-beta5-12103 clr     x64          C:\Users\jpoehls\.dnx\runtimes
       1.0.0-beta5-12103 clr     x86          C:\Users\jpoehls\.dnx\runtimes default

================================================

PS> dnx --appbase "C:\pts\src\MyCompany.MyProject" "C:\Users\jpoehls\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll" pack "C:\pts\src\MyCompany.MyProject" --configuration Debug --out "..\..\artifacts\bin\MyCompany.MyProject"

Building MyCompany.MyProject for DNX,Version=v4.5.1
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.IO.FileSystemInfo.get_FullName()
   at Microsoft.Framework.FileSystemGlobbing.Abstractions.DirectoryInfoWrapper.<EnumerateFileSystemInfos>d__3.MoveNext()
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Execute()
   at Microsoft.Framework.FileSystemGlobbing.Matcher.Execute(DirectoryInfoBase directoryInfo)
   at Microsoft.Framework.FileSystemGlobbing.MatcherExtensions.GetResultsInFullPath(Matcher matcher, String directoryPath)
   at Microsoft.Framework.Runtime.PatternGroup.SearchFiles(String rootPath)
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.CompileProject(Project project, ILibraryKey target, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences)
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReferenceProvider.GetProjectReference(Project project, ILibraryKey target, Func`1 referenceResolver)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.<>c__DisplayClass5_0.<GetLibraryExport>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Framework.Runtime.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.<>c__DisplayClass2_0.<GetLibraryExport>b__0(ILibraryExportProvider r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.ProjectExportProviderHelper.GetExportsRecursive(ICache cache, ILibraryManager manager, ILibraryExportProvider libraryExportProvider, ILibraryKey target, Func`2 include)
   at Microsoft.Framework.Runtime.ProjectExportProviderHelper.GetExportsRecursive(ICache cache, ILibraryManager manager, ILibraryExportProvider libraryExportProvider, ILibraryKey target, Boolean dependenciesOnly)
   at Microsoft.Framework.Runtime.LibraryManager.<>c__DisplayClass23_0.<GetAllExports>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Framework.Runtime.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.LibraryManager.GetAllExports(String name, String aspect)
   at Microsoft.Framework.Runtime.LibraryManager.GetAllExports(String name)
   at Microsoft.Framework.PackageManager.BuildContext.ShowDependencyInformation(IReport report)
   at Microsoft.Framework.PackageManager.BuildContext.Initialize(IReport report)
   at Microsoft.Framework.PackageManager.BuildManager.Build()
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_3.<Main>b__6()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
```

**Comment by muratg** [comment] 2015-07-02 17:17
What else did you change in the project?  And how does your project.json look like (are you using beta4 packages?)

**Comment by jpoehls** [comment] 2015-07-02 17:25
I'm not aware of any changes, that's the annoying thing. I basically switched branches, came back and did a `git clean` and tried to build and it flopped. I'm sure _something_ must have changed but I don't have a clue what.

Here's my `project.json` file.

```
{
    "version": "0.1.1",
    "dependencies": {
        "EntityFramework.Core": "7.0.0-beta4",
        "EntityFramework.InMemory": "7.0.0-beta4",
  ... some internal stuff
        "Microsoft.AspNet.Mvc": "6.0.0-beta4",
        "Microsoft.Composition": "1.0.30",
        "Microsoft.Framework.ConfigurationModel": "1.0.0-beta4"
    },
    "frameworks": {
        "dnx451": {
            "frameworkAssemblies": {
                "System.ComponentModel.Composition": "4.0.0.0"
            }
        }
    },
    "publishExclude": [
        "**.xproj",
        "**.user"
    ]
}
```

**Comment by thomaslevesque** [comment] 2015-07-04 12:35
I have a similar issue with `dnu build`. Here's the output:


```
dnu : System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file 
name must be less than 260 characters, and the directory name must be less than 248 characters.
At line:1 char:1
+ dnu build 2> D:\tmp\output.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.IO.PathT...248 characters.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.IO.PathHelper.GetFullPathName()
   
at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, 
SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateFileSystemInfos(String searchPattern, SearchOption searchOption)
   at 
Microsoft.Framework.FileSystemGlobbing.Abstractions.DirectoryInfoWrapper.<EnumerateFileSystemInfos>d__3.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Match(DirectoryInfoBase directory, String 
parentRelativePath)
   at Microsoft.Framework.FileSystemGlobbing.Internal.MatcherContext.Execute()
   at Microsoft.Framework.FileSystemGlobbing.Matcher.Execute(DirectoryInfoBase directoryInfo)
   at Microsoft.Framework.FileSystemGlobbing.MatcherExtensions.GetResultsInFullPath(Matcher matcher, String 
directoryPath)
   at Microsoft.Framework.Runtime.PatternGroup.SearchFiles(String rootPath)
   at Microsoft.Framework.Runtime.ProjectFilesCollection.get_SourceFiles()
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.CompileProject(ICompilationProject project, ILibraryKey 
target, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver)
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectCompiler.CompileProject(ICompilationProject pr
oject, ILibraryKey target, Func`1 referenceResolver, Func`1 resourcesResolver)
   at 
Microsoft.Framework.Runtime.ProjectLibraryExportProvider.<>c__DisplayClass5_0.<GetLibraryExport>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.CacheExt
ensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.Cr
eateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.<>c__DisplayClass2_0.<GetLibraryExport>b__0(ILibraryEx
portProvider r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Framework.Runtime.CompositeLibraryExportProvider.GetLibraryExport(ILibraryKey target)
   at Microsoft.Framework.Runtime.ProjectExportProviderHelper.GetExportsRecursive(ICache cache, ILibraryManager 
manager, ILibraryExportProvider libraryExportProvider, ILibraryKey target, Func`2 include)
   at Microsoft.Framework.Runtime.ProjectExportProviderHelper.GetExportsRecursive(ICache cache, ILibraryManager 
manager, ILibraryExportProvider libraryExportProvider, ILibraryKey target, Boolean dependenciesOnly)
   at Microsoft.Framework.Runtime.LibraryManager.<>c__DisplayClass23_0.<GetAllExports>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.LibraryManager.GetAllExports(String name, String aspect)
   at Microsoft.Framework.Runtime.LibraryManager.GetAllExports(String name)
   at Microsoft.Framework.PackageManager.BuildContext.ShowDependencyInformation(IReport report)
   at Microsoft.Framework.PackageManager.BuildContext.Initialize(IReport report)
   at Microsoft.Framework.PackageManager.BuildManager.Build()
   at Microsoft.Framework.PackageManager.BuildConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider 
serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```
If I try to build in VS2015, I don't get any error, but the build never completes

**Comment by troydai** [comment] 2015-07-06 16:31
@jpoehls @thomaslevesque is there other `project.json` file under your `bin` folder?

**Comment by thomaslevesque** [comment] 2015-07-06 16:52
@troydai, I don't think so, but I no longer have the project that was failing. I think it was caused by the node_modules folder which has a *very* deep folder hierarchy.

**Comment by jpoehls** [comment] 2015-07-06 17:01
@troydai no, no `project.json` anywhere beneath my `bin` folder.

**Comment by muratg** [comment] 2015-07-06 17:35
@jpoehls is it the node_modules folder for you as well?

**Comment by jpoehls** [comment] 2015-07-06 17:41
I'd bet so. Even doing `ls -recurse -include node_modules` in PowerShell errors out with a `PathTooLongException`.

What's the workaround for that? Like I said, I've already got my project at `c:\pts` -- so I can't shorten that end of it.

**Comment by troydai** [comment] 2015-07-06 22:09
so if `node_modules` is the issue, the quickest solution is to include them in the `exclude` section so that the globbing will ignore them.
```
// project.json
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
```

**Comment by troydai** [comment] 2015-07-08 23:51
@jpoehls does it help?

**Comment by glennc** [comment] 2015-08-11 17:59
Closing, feel free to reopen if you want to continue the discussion.

**Closed by glennc** 2015-08-11 17:59 UTC

**Comment by skorunka** [comment] 2016-03-11 10:03
Problem solved. Thank you.

**Comment by atillatan** [comment] 2016-05-25 03:37
@troydai Thank you.
