### ISSUE TITLE
DTH fails with the following error: preprocessorSymbols

### ISSUE THREAD

**Issue by glatzert** [aspnet/dnx#2143] opened 2015-06-26 14:31 UTC
VS2015 RC with ASP.NET 5 vNext Feed and Nuget 3.0 RC 2

The error list states the following:
Description: The design time host build failed with the following error: preprocessorSymbols
Project: <ProjectName>
File: C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets
Line: 143

Description: preprocessorSymbols
Project: <ProjectName>
File: <None>
Line: 1

DNVM list

       1.0.0-beta4       clr     x64          C:\Users\glatzert\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\glatzert\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\glatzert\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\glatzert\.dnx\runtimes
       1.0.0-beta5-12021 clr     x64          C:\Users\glatzert\.dnx\runtimes
       1.0.0-beta5-12021 clr     x86          C:\Users\glatzert\.dnx\runtimes
       (*) 1.0.0-beta5-12103 clr     x64          C:\Users\glatzert\.dnx\runtimes default

**Comment by muratg** [comment] 2015-06-26 17:46
@BillHiebert @troydai

**Comment by troydai** [comment] 2015-06-26 19:41
@glatzert can I know what's the version of the sdk been stated in `global.json` if it is stated.

**Comment by glatzert** [comment] 2015-06-26 20:03
@troydai 
I was not aware, that there is such entry:

    "sdk": {
        "version": "1.0.0-beta4"
    }

I assume i have to Change it?

**Comment by troydai** [comment] 2015-06-26 20:27
@glatzert yes.

The sdk version specified here is that actual version of DTH VS uses. If it is not specified, VS will fall back to the current default DNX.

**Comment by glatzert** [comment] 2015-06-26 21:36
@troydai 
Okay - I removed it from the global.json - the error vanished.
Thanks so far :+1: 

After changing that, it won won't finish restoring.
It hangs with "CACHE <nuget>" - do I have to do something else?

**Comment by troydai** [comment] 2015-06-26 23:47
@glatzert it's hard to tell what cause the hanging without accessing your environment. But you can try these things to self-diagnose.
1. Try to restore it from command line (eliminating the DTH as a factor);
2. Try to clean the cache. (under %localappdata%\dnu\cache);
3. In addition to the cache, clean the packages folder (~\.dnx\packages);
4. Check the connection to our source, either myget or nuget.

So you can keep reproducing the hanging, then we may have an issue in dnu restore. In that case, we'd love to look into it.

**Comment by glatzert** [comment] 2015-06-27 17:54
Okay - that did it.
I appreciate your help :+1: 

Prehaps you guys think about adding a timeout for the Cache Operation - since it tried all night ;)
Or a kill all Caches button..

Nevertheless: good work - Keep it up

**Comment by muratg** [comment] 2015-06-29 15:20
Looks like this issue was resolved. Closing.

**Closed by muratg** 2015-06-29 15:20 UTC
