### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by Tratcher** [aspnet/dnx#3381] opened 2016-03-15 02:05 UTC
_From @xatabhk on March 15, 2016 0:14_

dnx web
or
donet run

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.Dnx.Runtime.ApplicationHostContext.Initialize(ApplicationHostContext context)
   at Microsoft.Dnx.Compilation.CompilationEngine.CreateProjectExporter(Project project, FrameworkName targetFramework, String configuration)
   at Microsoft.Dnx.Compilation.CompilationEngine.LoadProject(Project project, FrameworkName targetFramework, String aspect, IAssemblyLoadContext loadContext, AssemblyName assemblyName, String configuration)
   at Microsoft.Dnx.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

_Copied from original issue: aspnet/Hosting#649_

**Comment by davidfowl** [comment] 2016-03-15 02:46
Can you provide a sample application on github please?

**Comment by xatabhk** [comment] 2016-03-15 03:39
Here is the sample.
>dnx --version
 Microsoft .NET Execution environment
 Version: 1.0.0-rc2-16595
 Type: Clr
 Architecture: x86
 OS Name: Windows
 OS Version: 10.0.10586
 Runtime Id: win10-x86

>dotnet --version
 .NET Command Line Tools (1.0.0-beta-001747)

Product Information:
 Version: 1.0.0-beta-001747
 Commit Sha: 58a8a10d41

Runtime Environment:
 OS Name: Windows
 OS Version: 10.0.10586
 OS Platform: Windows
 Runtime Id: win10-x64

Steps:
>dotnet restore
>dotnet run or dnx web
An item with the same key has already been added. Key: System.IO Unspecified
[zaxitech_core_demo.zip](https://github.com/aspnet/dnx/files/173227/zaxitech_core_demo.zip)

**Comment by moozzyk** [comment] 2016-03-15 17:07
Dupe of https://github.com/dotnet/cli/issues/1775 ?

**Comment by muratg** [comment] 2016-04-05 18:02
@xatabhk Do you still have the issue with newer builds of the CLI?

**Closed** 2017-12-17 19:49 UTC
