### ISSUE TITLE
Sending a FilesChanged doesn't always stop the IIS Express process

### ISSUE THREAD

**Issue by BillHiebert** [aspnet/dnx#1843] opened 2015-05-11 22:21 UTC
1. Create a new DNX Site
2. Ctrl+F5 to run it
3. Note the IIS Express process id
4. Open project.json and save it.
5. Most of the time the IIS Express process is not restarted

I can repro it with .cs files as well.

**Comment by muratg** [comment] 2015-05-12 18:42
@Tratcher any ideas?

**Comment by Tratcher** [comment] 2015-05-12 19:50
Modifying startup works. I noticed that the PID only changes if I have accessed/refreshed the page since the last change. I think this is because sites are delay started, they only initialize (and listen for file changes) if someone actually visits the site.

Modifying the project.json does not appear to trigger a process close, and it's harder to tell if you've actually changed anything in the site.

**Comment by davidfowl** [comment] 2015-05-12 19:51
Likely a DTH bug. I made a change here in beta5 that might have something to do with it.

**Comment by muratg** [comment] 2015-05-12 23:37
Assigning to @davidfowl to investigate the potential DTH issue, but to me there doesn't seem to be a functional impact. I think we can just close it.

**Comment by davidfowl** [comment] 2015-05-20 08:44
Closing this as by design.

**Closed by davidfowl** 2015-05-20 08:44 UTC
