### ISSUE TITLE
DNU always timeout with mono

### ISSUE THREAD

**Issue by Kagamine** [aspnet/dnx#3149] opened 2015-11-10 11:55 UTC
I have done `export MONO_THREADS_PER_CPU=2000`, it still not works.

In China, our government developed a firewall to forbid us access to foreign websites. 

So we need more time to restore the packages, The packages always restore timeouted in mono.

**Comment by muratg** [comment] 2015-12-09 22:50
@Kagamine How about CoreCLR?  We have multiple issues with Mono, and I suspect this is also a Mono issue.

**Comment by Kagamine** [comment] 2015-12-12 13:19
I don't know why I cannot use dnu with coreclr.

**Comment by muratg** [comment] 2015-12-14 12:48
@Kagamine What's the Mono version you're using?  

Also, what's your issues with using DNU with CoreCLR?  It should work in general, so if there's an exception or a problem, we'd like to know :)

**Comment by Kagamine** [comment] 2015-12-14 13:21
In coreclr, I have excuted `dnu restore`, but it cannot restore anything, and it outputed nothing. It just exited when I typed `dnu restore` & enter.

**Comment by muratg** [comment] 2015-12-14 14:00
Can you put your dnvm list output? What's the DNX version you tried?

Also, can you try `dnu -v restore` (for verbose) for the same project to see what the output is?

**Comment by mconnew** [comment] 2016-01-06 00:51
[WCF](http://github.com/dotnet/wcf) has been hitting this issue with building on Linux and I have a fix I'm going to create a PR for. It's caused by the fact that on mono, ServicePointManager is set to only allow one current request per remote host. When you have a large number of packages to download, you can have up to 50 packages per source being attempted to download at once. You end up with 50 tasks all awaiting on HttpClient.SendAsync. The first request in will begin downloading, and all subsequent requests will queue up. The issue is the request timeout timer (defaults to 100 seconds) will begin pretty much straight away when entering SendAsync. With enough packages needing to be downloaded, you will eventually have a call into SendAsync waiting longer than 100 seconds which causes it to timeout.

**Comment by Kagamine** [comment] 2016-01-19 13:29
It still timeout when using coreclr.

**Comment by Kagamine** [comment] 2016-01-19 13:34
It still timeout when active the coreclr

**Comment by muratg** [comment] 2016-01-19 17:13
@emgarten Just wanted to bring https://github.com/aspnet/dnx/issues/3149#issuecomment-169181328 to your attention, in case it's something you need to worry about in the new restore

**Comment by emgarten** [comment] 2016-01-19 22:27
@muratg  thanks for the heads up, this should be fixed in nuget already.
https://github.com/NuGet/Home/issues/1355

**Comment by muratg** [comment] 2016-01-19 22:45
:+1:

**Closed by muratg** 2016-01-19 22:45 UTC
Labels: Move to NuGet
