### ISSUE TITLE
IIS startup: method not found

### ISSUE THREAD

**Issue by anfomin** [aspnet/dnx#2412] opened 2015-08-05 10:22 UTC
After `ILibraryManager` methods renaming I can't start project with IIS. Exception occurs on start:
```
Method not found: 'Microsoft.Dnx.Runtime.Library Microsoft.Dnx.Runtime.ILibraryManager.GetLibraryInformation(System.String)'.
```

Project starts normal with WebListener. It seems that `Microsoft.AspNet.Server.IIS` should react to renaming...

**Comment by dougbu** [comment] 2015-08-05 16:38
@anfomin see aspnet/Home#798 for more on the Microsoft.AspNet.Server.IIS status.

**Comment by glennc** [comment] 2015-08-05 17:31
Closing as dupe of  aspnet/Home#798

**Closed by glennc** 2015-08-05 17:31 UTC
