### ISSUE TITLE
DateTime.Parse inconsistent with other platforms

### ISSUE THREAD

**Issue by JamesNK** [aspnet/dnx#773] opened 2014-10-17 09:37 UTC
This passes in .NET 4.5 and Win 8 Store but fails on CoreCLR:

    [Test]
    public void FailingDateTimeParse()
    {
        string text = "2000-12-15T22:11:03.055+23:30";

        DateTime oldDt;
        bool success = DateTime.TryParseExact(text, "yyyy-MM-ddTHH:mm:ss.FFFFFFFK", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out oldDt);

        Console.WriteLine("Success: " + success);
        Console.WriteLine("DateTime: " + oldDt);

        Assert.True(success);
    }

**Comment by glennc** [comment] 2015-02-17 00:55
@GrabYourPitchforks do you think this is related to something similar to https://github.com/aspnet/XRE/issues/600?

**Comment by muratg** [comment] 2015-03-06 20:10
@troydai Does the work you did with carrying Culture across threads solve this one and #600? 

/cc: @DamianEdwards

**Comment by troydai** [comment] 2015-03-13 16:52
It doesn't seems to be related to #600. #600 will be fixed when quirk switch for TFM is added. But this is not.

**Comment by muratg** [comment] 2015-03-19 17:40
Troy, can you file this one on CoreCLR repo?

**Comment by troydai** [comment] 2015-03-19 20:33
Filed CoreCLR issue https://github.com/dotnet/corefx/issues/1181

**Comment by troydai** [comment] 2015-03-25 03:21
@JamesNK, I'm going to close this issue as by design. Please see the coreclr team's response here:
https://github.com/dotnet/corefx/issues/1181#issuecomment-85752670

**Closed by troydai** 2015-03-25 03:21 UTC
Labels: 2 - Working
