### ISSUE TITLE
Running K / DNX - ASP.NET 5 application as a background service on Linux

### ISSUE THREAD

**Issue by jsinh** [aspnet/dnx#1673] opened 2015-04-18 00:47 UTC
I am stuck and out of options.

I am trying to create a generic script / util that will help LINUX users (especially for people who SSH) to run web application as service.

This happens when we have a SS entry in `/etc/init.d` with allowed run specified.

Repo where I am pushing this changes is at:
https://github.com/jsinh/dnx-app-startup

I was able to get all other bits working expect this one:
```csharp
System.ArgumentNullException: Argument cannot be null.
Parameter name: path1
  at System.IO.Path.Combine (System.String path1, System.String path2, System.String path3) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.NuGetDependencyResolver.ResolveRepositoryPath (System.String rootDirectory) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.ApplicationHostContext..ctor (IServiceProvider serviceProvider, System.String projectDirectory, System.String packagesDirectory, System.String configuration, System.Runtime.Versioning.FrameworkName targetFramework, ICache cache, ICacheContextAccessor cacheContextAccessor, INamedCacheDependencyProvider namedCacheDependencyProvider, IAssemblyLoadContextFactory loadContextFactory, Boolean skipLockFileValidation) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.DefaultHost.Initialize (Microsoft.Framework.Runtime.DefaultHostOptions options, IServiceProvider hostServices) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.DefaultHost..ctor (Microsoft.Framework.Runtime.DefaultHostOptions options, IServiceProvider hostServices) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0 
  at dnx.host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args) [0x00000] in <filename unknown>:0 
```

Is it K tools / DNX / Mono or my app? No clue anymore :(

I have tried for K tools and DNX nightlies and i get the same issue in both case.
Under init.d context you won't get access to user local ENV VARS. I was able to successfully feed `KRE_APPBASE` using known techniques to `k kestrel` before it starts (as suggested by David and others on Jabbr yesterday).

I am not sure what settings, command pattern or ENV VARS I am missing to be set before the app can run successfully as a service.

I have seen similar exception issues already reported in past, studying them and understanding commits didn't helps:
https://github.com/aspnet/dnx/issues/974
https://github.com/aspnet/dnx/pull/1112

I appreciate anyone who can help, thanks in advance.

Configuration:
K tools / DNX nightlies (tried both)
Ubuntu 14.04 LTS
Mono 3.12.1

**Comment by anurse** [comment] 2015-04-21 17:29
The problem is that DNX can't find the packages folder. Normally, it looks like ~/.dnx/packages, but it looks like the HOME environment variable is empty in your init.d context.

The easy solution is to find a place to put your packages, and set the DNX_PACKAGES environment variable during your init script. If you want, you can just point it at `/home/[username]/.dnx/packages`. Wherever you put it, you need to make sure the packages have actually been installed there, by running `DNX_PACKAGES=[your package dir] dnu restore` in the app directory to ensure the packages are properly installed.

Even **better** would be to use `dnu publish` to pack the entire app up in a single self-contained folder. The result will be a folder containing ALL NuGet packages needed by the app, and the application itself. You can also use the `--no-source` switch to precompile your app and the `--runtime` switch to include a runtime in the published application so it is entirely stand-alone (though it will still need Mono installed). See `dnu help publish` for more help there.

Hope that helps!

**Comment by jsinh** [comment] 2015-04-30 20:16
@anurse That makes sense and seems to be the reason of the error. I will try setting up `DNX_PACKAGES` to see if that helps.

`dnu publish` should be the stage where there would be more need of running app as a service.

Thanks for that clue

**Comment by jsinh** [comment] 2015-05-10 21:58
@anurse So the idea works - setting up `DNX_PACKAGES` with correct path of `dnu restore`d packages folder. One extra thing I had to do is to also provide actual path to the dnx runtime e.g: `/home/[username]/.dnx/runtimes/dnx-mono.1.0.0-beta4/bin/dnx`

So if I do not `dnu publish` I am almost static while creating init.d script (sorry if I am not thinking in the correct direction) in context of packages folder path and dnx runtime path.

Next thing I tried is `dnu publish` and see if that makes things any better, but situation remained same.

So now with paths and env. var. in place I get "Started" as log output but after that the application stops automatically and returns. Expect it to keep running in background but it doesn't

sample command I used for reference:

`DNX_PACKAGES=$DNX_PACKAGES_PATH $DNX_COMMAND $APP_DIR kestrel 1>"$APP_SERVICE_LOG_FILE" 2>&1 &`

`$DNX_PACKAGES_PATH` - Path to packages (common in .dnx folder)
`$DNX_COMMAND` - Full path to dnx executable
`$APP_DIR` - Full path to application base directory
`$APP_SERVICE_LOG_FILE` - Application log file name with full path

[Original in-development script for reference](https://github.com/jsinh/dnx-app-startup/blob/master/init.d/dnx-app#L67)

So what am I missing?

Thanks in advance to everyone who helps.

**Comment by Tragetaschen** [comment] 2015-05-11 08:51
The problem is, that Hosting does a `Console.ReadLine()` and requires a valid TTY for that at the moment. There is [some](aspnet/Hosting#129) [work](aspnet/Hosting#253) [underway](aspnet/Hosting#255) to remove that requirement.

**Comment by anurse** [comment] 2015-05-11 16:41
@jsinh When you did `dnu publish`, did you try using the `--runtime` argument to embed a runtime in your application package? That might help with deployment. It should be possible to build a single folder that contains everything you need to run your DNX application (including the runtime) using `dnu publish`. If there are issues with that, we should fix them :).

**Comment by jsinh** [comment] 2015-05-17 18:10
Hello @anurse, yes I did tried `dnu publish` with `--runtime` and that helps - No need to refer the DNX statically in `init.d` script.

Yes that would be ideal in situations when you deploy and try setting up DNX app to run as service with `init.d` except for the "Hosting does a `Console.ReadLine()` and requires a valid TTY`.

But I was ALSO trying to configure DNX / ASP.NET application as service so any developer / devops can develop with any XYZ editor, make changes and run the app with single / common / simple and easy to use command - script in place. (This is what I see and have played with while working / fiddling with NodeJS apps, help me if I am thinking it wrong)

Also I was asked the same thing as question by one of my blog reader in response to what I have written about few aspects of new ASP.NET stack.

So in current situation, the best thing would be to wait until Hosting adopts different pattern than `Console.ReadLine()` and then I can make some progress on this.

BTW @Tragetaschen - The three links you refer are all 404 at the moment. Sorry but haven't checked it earlier. 

**Side note:** Now that VS Code is out for Linux this seems to be less important as such. But would helps in case there is not GUI on linux on cloud VMs / docker containers.

**Comment by Tragetaschen** [comment] 2015-05-17 19:06
Hmm, github weirdness?

The changes to Hosting are merged and `Console.ReadLine` [is gone](https://github.com/aspnet/Hosting/commit/95b1997c14bb6fb7e2e68dd156f4feee3d139fec)

**Comment by jsinh** [comment] 2015-05-17 19:23
@Tragetaschen I guess but not sure.

Thanks for the change :). It is currently floating in in dev / beta-5 i guess. Will try it out when I have a setup to play with nightlies / bleeding edge.

**Closed** 2015-05-17 19:36 UTC
