### ISSUE TITLE
dnu restore fails with an exit code of 0

### ISSUE THREAD

**Issue by aggieben** [aspnet/dnx#2379] opened 2015-07-30 22:55 UTC
Obviously things are better if dnu doesn't fail, but I have a `dnu restore` operation that is affected by #1590.  This happens during a CI-invoked docker build, but the build continues and creates an image (a broken one) because it doesn't know that `dnu restore` failed.  Here's why:

```
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>:0
  at Microsoft.Framework.PackageManager.RestoreCommand+<Execute>d__69.MoveNext () [0x00000] in <filename unknown>:0
----------
Restore failed
A task was canceled.

NuGet Config files used:
    /root/.config/NuGet/NuGet.Config
    /var/lib/dnx/cm-core/NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetrelease/api/v2/
    https://nuget.org/api/v2/
Warning: DownloadPackageAsync: https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.AspNet.Owin/1.0.0-beta6-11747
  HTTP request timed out. Retrying.
  GET https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.AspNet.Owin/1.0.0-beta6-11747
Warning: DownloadPackageAsync: https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.AspNet.Server.WebListener/1.0.0-beta6-12467
  HTTP request timed out. Retrying.
  GET https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.AspNet.Server.WebListener/1.0.0-beta6-12467
Warning: DownloadPackageAsync: https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.AspNet.Mvc/6.0.0-beta6-14346
  HTTP request timed out. Retrying.
  GET https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.AspNet.Mvc/6.0.0-beta6-14346
Warning: DownloadPackageAsync: https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.Framework.Configuration.Json/1.0.0-beta6-11605
  HTTP request timed out. Retrying.
  GET https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.Framework.Configuration.Json/1.0.0-beta6-11605
Error: DownloadPackageAsync: https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.Framework.Logging.Console/1.0.0-beta6-11609
  HTTP request timed out. Exiting.
Warning: DownloadPackageAsync: https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.Framework.Logging.Abstractions/1.0.0-beta6-11609
  HTTP request timed out. Retrying.
  GET https://www.myget.org/F/aspnetrelease/api/v2/package/Microsoft.Framework.Logging.Abstractions/1.0.0-beta6-11609
root@3d728a9ab363:/var/lib/dnx/cm-core/src/Cm.Core# echo $?
0
root@3d728a9ab363:/var/lib/dnx/cm-core/src/Cm.Core#
```

Can we get a non-zero exit code in the case of failures?

For anyone dealing with this same thing: my current work around goes like this:
```
if [ ! -f project.lock.json ]; then echo "dnu restore failed"; exit 1; fi
```

**Comment by anurse** [comment] 2015-07-30 23:26
:+1: any time we fail we should return a non-zero code

**Comment by glennc** [comment] 2015-07-31 17:49
@ChengTian I am assuming this is a fairly trivial fix. Let me know if that's not the case.

**Comment by ChengTian** [comment] 2015-07-31 22:12
I cannot reproduce this with
`dnx-mono.1.0.0-beta7-12290` on `Mono JIT compiler version 4.0.1` (and simulating HTTP request timeout with some bandwidth throttling tools)

Also tried `dnx-mono.1.0.0-beta6`, `dnu restore` returns 1 after timeout error.

@aggieben , could you please try the latest version of dnx by running `dnvm upgrade -u`?

**Comment by aggieben** [comment] 2015-08-01 23:56
Hmm, I also can't reproduce this when simulating timeouts.  However, whenever the restore fails as in #1590, the exit code is 0.

**Comment by ChengTian** [comment] 2015-08-03 23:55
Tried on Ubuntu with `Mono JIT compiler version 4.1.0` and I can repro the issue https://github.com/aspnet/dnx/issues/1590. However, the exit code is still non-zero (, which means I still cannot repro current issue):

![capture](https://cloud.githubusercontent.com/assets/1383883/9049971/1c12e988-39fd-11e5-9c8a-68f7f170568a.PNG)

It is very likely a sporadic Mono issue because when you get an unhandled exception like this, the exit code is controlled by runtime, instead of code in DNX.

Closing this for now. @aggieben , if you figure out more specific conditions that can trigger this issue, please reopen issue and report it here.

**Closed by ChengTian** 2015-08-03 23:55 UTC

**Comment by ChengTian** [comment] 2015-08-04 00:11
My bad, the timeout exception is not an unhandled exception. We are handling all possible exceptions here:
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Restore/RestoreCommand.cs#L225

But as you can see, if you have 
```
----------
Restore failed
```
in `dnu restore` output, it should be going through the code path in the catch statement and eventually return `false`, which leads to a non-zero exit code. So I still suspect it is an issue in Mono.

**Comment by aggieben** [comment] 2015-08-04 00:25
Yeah, no problem.  I'll resurrect if I can narrow a repro, but realistically speaking I don't think I'll have time for all that.
