### ISSUE TITLE
BUG: "dnu commands install" fails to find .sha512

### ISSUE THREAD

**Issue by giggio** [aspnet/dnx#2192] opened 2015-07-06 22:16 UTC
I have a project.json that depends on `FluentMigrator` version `1.5.1.0`. This package defines its version as `1.5.1.0`. If I try to install my package (FluentMigrator.Runner.Aspnet):

````
dnu commands install FluentMigrator.Runner.Aspnet --no-cache
````

It fails because it can't find the `.sha512` file:

````
Could not find a part of the path 'C:\Users\username\.dnx\bin\packages\FluentMigrator\1.5.1.0\FluentMigrator.1.5.1.0.nupkg.sha512'.
````

It is looking for the `1.5.1.0` directory, but `dnu` is saving it without the last `.0`, so I have on disk only the `$HOME\.dnx\bin\packages\FluentMigrator\1.5.1` directory. And installation fails.

**Comment by giggio** [comment] 2015-07-06 22:36
The problem also happens on `dnu restore` for the package.

**Comment by davidfowl** [comment] 2015-07-07 07:22
The problem is that these packages have inconsistent nuspec versions. 

@muratg @ChengTian @anurse  we should fix this ASAP. A bunch of packages are running into this. We need to resolve the inconsistencies between package version in the nuspec and elsewhere.

**Comment by muratg** [comment] 2015-07-07 15:47
:+1:

**Comment by troydai** [comment] 2015-07-08 23:08
@giggio Could you let us know what's version of the DNX you're using?

I fail to repo this issue with either beta5 or beta6 latest with this command (targeting alpha3 since you work around the problem in alpha4):
```
dnu commands install FluentMigrator.Runner.AspNet 1.0.0-alpha3 --no-cache
```

**Comment by davidfowl** [comment] 2015-07-09 00:23
This absolutely repros. I can repro it myself without a commands install.

**Comment by giggio** [comment] 2015-07-09 00:46
@troydai that is because I have forked the original FluentMigrator.Runner and uploaded a correct version to Nuget (which I plan to remove as soon as the original is fixed).

**Comment by troydai** [comment] 2015-07-09 05:59
@giggio I can repo the issue now. Working on it.

**Comment by troydai** [comment] 2015-07-09 23:28
Fixed in cae8aab5b38e0039f03eb87a8d994e3035179206

**Closed** 2015-07-09 23:53 UTC
Labels: 2 - Working, bug

**Comment by giggio** [comment] 2015-07-13 20:45
@davidfowl @troydai Any workarounds at this point to work with these packages and `beta5`?
