### ISSUE TITLE
--watch flag does not work as expected

### ISSUE THREAD

**Issue by alikor** [aspnet/dnx#2236] opened 2015-07-10 02:15 UTC
when executing 

dnx --watch . kestrel

The process stops whenever any .cs file is changed but the process does not restart, this is not a common usecase for watchers in most if not all other command line tools such as compass, Stylus, Node-Sass, Jade, Karma and many more!

**Comment by davidfowl** [comment] 2015-07-10 06:06
Dupe of https://github.com/aspnet/dnx/issues/1795

**Closed by davidfowl** 2015-07-10 06:06 UTC
