### ISSUE TITLE
`dnu restore --lock` should not write a `project.lock.json` file if any resolutions fail

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#1921] opened 2015-05-21 17:21 UTC

**Comment by dougbu** [comment] 2015-05-21 17:23
For example, I had a temporary network glitch which convinced `dnu` that `Microsoft.AspNet.Razor` did not exist. (Fact that failure seems to have been cached is a separate issue.)  Until I deleted `$env:localappdata\dnu\cache`, `dnu restore --lock` consistently reported:
```
Restoring packages for C:\dd\dnx\Universe\Mvc\test\WebSites\RoutingWebSite\project.json
Unable to locate Microsoft.AspNet.Razor >= 4.0.0-beta5-11462
Writing lock file C:\dd\dnx\Universe\Mvc\test\WebSites\RoutingWebSite\project.lock.json
Restore complete, 730ms elapsed
```

**Comment by ChengTian** [comment] 2015-05-22 17:36
Please share the version of dnx you are using here

**Comment by dougbu** [comment] 2015-05-22 17:38
I normally use the volatile feed. So this would have been with the latest CLR runtime as of yesterday morning.

**Comment by ChengTian** [comment] 2015-05-22 17:48
Hmm, this version of `dnu restore` should never cache things if you have network glitch. Unless your network glitch convinced `dnu` by returning 200 OK along with a valid NuGet OData XML that shows there is no ` Microsoft.AspNet.Razor` in the feed.

Could you please file a separate issue for the wrong caching behavior? Please paste the contents of `list_Microsoft.AspNet.Razor_page1.dat` in your `$env:localappdata\dnu\cache`.

**Comment by dougbu** [comment] 2015-05-22 17:54
Sorry, I deleted `$env:localappdata\dnu\cache` to work around this problem. Not sure how to force the problem to happen again. But, on your end, it should be possible to corrupt the cache correctly to reproduce _this_ bug.

**Comment by ChengTian** [comment] 2015-05-22 18:13
Cannot reproduce the wrong caching behavior. We can file a bug when someone sees it again.

Ok, let's get back to the major topic in this thread:
**Should `dnu restore` write lock file when there is unresolved dependency during restore?**

I know that previously we didn't write lock file when `dnu restore` is unable to locate some dependencies. But later we changed that behavior at some point. So it should be by design.

I talked to @anurse and he thinks current behavior is handy for integration with MSBuild projects.
Adding @davidfowl , who can give more reasons here.

**Comment by anurse** [comment] 2015-05-22 19:01
The MSBuild integration we're working on could benefit from having the unresolved dependencies called out in the lock file. I agree that we should ensure the lock file is written in a state that makes it very clear to tools that the restore has failed, but having the metadata about what failed in a persistent form can be very useful for error display in the IDE, among other things.

**Comment by muratg** [comment] 2015-09-15 18:01
https://github.com/aspnet/dnx/issues/2332 is tracking the changes coming in for the lock file. Closing this one.

**Closed by muratg** 2015-09-15 18:01 UTC
