### ISSUE TITLE
Regression: IRuntimeEnvironment not resolved on windows dnx in MVC application

### ISSUE THREAD

**Issue by borgdylan** [aspnet/dnx#2898] opened 2015-10-05 12:12 UTC
When using the latest DNX from the unstable feed on Azure, I get the following exception:
```
System.InvalidOperationException: Failed to resolve IRuntimeEnvironment
   at Microsoft.Dnx.Runtime.RuntimeEnvironmentHelper.GetRuntimeEnvironment()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Dnx.Runtime.RuntimeEnvironmentHelper.<>c.<.cctor>b__10_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Dnx.Runtime.FrameworkReferenceResolver.GetReferenceAssembliesPath()
   at Microsoft.Dnx.Runtime.FrameworkReferenceResolver.GetFrameworkInformation(FrameworkName targetFramework)
   at System.Collections.Generic.DictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory)
   at Microsoft.Dnx.Runtime.FrameworkReferenceResolver.TryGetAssembly(String name, FrameworkName targetFramework, String& path, Version& version)
   at Microsoft.Dnx.Runtime.ReferenceAssemblyDependencyResolver.GetDescription(LibraryRange libraryRange, FrameworkName targetFramework)
   at Microsoft.Dnx.Runtime.ApplicationHostContext.Initialize(ApplicationHostContext context)
   at Microsoft.Dnx.ApplicationHost.RuntimeLibraryManager.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.Dnx.ApplicationHost.RuntimeLibraryManager.GetReferencingLibraries(String name)
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__1`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Microsoft.AspNet.Mvc.Controllers.DefaultControllerTypeProvider.get_ControllerTypes()
   at Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorsCollectionProvider.GetCollection()
   at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorsCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNet.Mvc.Routing.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SoHi.LoggerExtensions.<Logger>d__0.MoveNext()
```

**Comment by borgdylan** [comment] 2015-10-05 12:58
This still happens with the aspnetcidev bits.

**Comment by muratg** [comment] 2015-10-05 15:55
@borgdylan HttpPlatformHandler module is not yet installed on Azure, but should be once we release Beta 8.

**Comment by borgdylan** [comment] 2015-10-05 16:06
It is installed just its version 1.0 so I had to use absolute paths. I expected dev builds for rc 1 to not crash with it since beta8 is expected to be rid of Helios.


Regards,

Dylan Borg B. Sc. (Hons) ICT (Melit.)

borgdylan@hotmail.com

borgdylang@gmail.com

+00356 99214902





On Mon, Oct 5, 2015 at 8:55 AM -0700, "Murat Girgin" <notifications@github.com> wrote:
@borgdylan HttpPlatformHandler module is not yet installed on Azure, but should be once we release Beta 8.

---

**Comment by borgdylan** [comment] 2015-10-05 16:09
The proxying part worked and Nowin (I use it instead of Kestrel) received requests ok. I know this as requests and responses were logged in the stdout logs of the platform handler module. So the issue is not coming from the platform handler module. Also AFAIK the platform handler has been on azure for ages to proxy over to tomcat etc.

**Comment by borgdylan** [comment] 2015-10-05 16:21
Could the issue be that there is no runtime id for windows x64 that is not on helios?

**Comment by davidfowl** [comment] 2015-10-05 16:28
Does it work locally? Can you provide a repro project?

**Comment by borgdylan** [comment] 2015-10-05 16:40
I cant try it locally since I do not have any windows installs here. Using a similar setup with Nowin on Linux works fine however (using the same package versions).

**Comment by borgdylan** [comment] 2015-10-05 16:42
I did try to patch the DNX not to throw the exception (returning a dummy IRuntimeEnvironment instead) but all was in vain.

**Comment by davidfowl** [comment] 2015-10-05 16:43
If you can provide a repro project we can investigate

**Comment by borgdylan** [comment] 2015-10-05 17:07
I am writing a repro. Would code in a git repo  and a published image suffice?

**Comment by borgdylan** [comment] 2015-10-05 17:16
I am currently testing on azure.

**Comment by davidfowl** [comment] 2015-10-05 17:16
Sure git repo is fine, and we'll test on azure too. Just give us instructions.

**Comment by borgdylan** [comment] 2015-10-05 17:43
I managed to reproduce this with a ridiculously simple MVC project. The repo is https://github.com/borgdylan/aspnet5-repros. The bin/output dir has an image that is deployable to azure with proper settings for the platform handler. The DNX used in for the 64bit windows CLR. Going to api/Home should yield "Hello World" string but the exception triggers instead. I have tested the code on Linux via mono successfully.

**Comment by borgdylan** [comment] 2015-10-05 19:59
To clarify: aspnetrepro/bin/output is the directory to FTP over to azure (I did test it on azure myself)

**Comment by borgdylan** [comment] 2015-10-06 05:05
Ping

**Comment by davidfowl** [comment] 2015-10-06 05:51
What dnx version?

**Comment by borgdylan** [comment] 2015-10-06 06:38
Its published in teh repo ie. dnx-clr-win (x64) v. 1.0.0-rc1-15798 (from aspnetcidev) https://github.com/borgdylan/aspnet5-repros/tree/master/aspnetrepro/bin/output/approot

**Comment by borgdylan** [comment] 2015-10-06 06:38
The bug is also present in previous versions present the aspnetvnext feed as well.

**Comment by borgdylan** [comment] 2015-10-06 19:27
ping

**Comment by borgdylan** [comment] 2015-10-07 05:04
Is there any news on this bug?

**Comment by davidfowl** [comment] 2015-10-07 05:36
Does this even work locally? I don't know if this has anything to do with azure... 

Some suspicious things:

https://github.com/borgdylan/aspnet5-repros/blob/master/aspnetrepro/bin/output/approot/packages/aspnetrepro/1.0.1/root/project.json#L8

https://github.com/borgdylan/aspnet5-repros/blob/master/NowinServerFactory/NowinServerFactory.cs#L33

Are you even listening to the right port?

/cc @JunTaoLuo can you take a look at this?

**Comment by borgdylan** [comment] 2015-10-07 07:07
It works on Linux locally. Also in a more complex example, I logged incoming requests. All requests came in. The exception was triggered when I called into an MVC controller. Static Files works as expected. From this I concluded that the proxying was working as needed.

I am overriding port 5001 in web.config to use the one given by IIS: https://github.com/borgdylan/aspnet5-repros/blob/master/aspnetrepro/bin/output/wwwroot/web.config#L6

**Comment by borgdylan** [comment] 2015-10-07 07:08
N.B. The return code in 500. If the proxying failed a 502 would be returned by IIS instead.

**Comment by davidfowl** [comment] 2015-10-07 07:14
Do you have a windows machine?

**Comment by borgdylan** [comment] 2015-10-07 07:15
I am at work so I can try on our WIndows Server VM.

**Comment by borgdylan** [comment] 2015-10-07 07:21
I just installed the platform handler and will be testing shortly.

**Comment by borgdylan** [comment] 2015-10-07 07:25
I managed to repro the issue on IIS 8 with platform handler 1.0.

**Comment by borgdylan** [comment] 2015-10-07 07:30
To prove that the proxying worked again this time round, below I attach the output of the developer exception page middleware:
```
﻿
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title>Internal Server Error</title>
        <style>
            body {
    font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif;
    font-size: .813em;
    line-height: 1.4em;
    color: #222;
}

h1, h2, h3, h4, h5 {
    /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/
    font-weight: 100;
}

h1 {
    color: #44525e;
    margin: 15px 0 15px 0;
}

h2 {
    margin: 10px 5px 0 0;
}

h3 {
    color: #363636;
    margin: 5px 5px 0 0;
}

code {
    font-family: Consolas, "Courier New", courier, monospace;
}

body .titleerror {
    padding: 3px;
    display: block;
    font-size: 1.5em;
    font-weight: 100;
}

body .location {
    margin: 3px 0 10px 30px;
}

#header {
    font-size: 18px;
    padding: 15px 0;
    border-top: 1px #ddd solid;
    border-bottom: 1px #ddd solid;
    margin-bottom: 0;
}

    #header li {
        display: inline;
        margin: 5px;
        padding: 5px;
        color: #a0a0a0;
        cursor: pointer;
    }

        #header li:hover {
            background: #a9e4f9;
            color: #fff;
        }

        #header .selected {
            background: #44c5f2;
            color: #fff;
        }

#stackpage ul {
    list-style: none;
    padding-left: 0;
    margin: 0;
    /*border-bottom: 1px #ddd solid;*/
}

#stackpage .stackerror {
    padding: 5px;
    border-bottom: 1px #ddd solid;
}

    #stackpage .stackerror:hover {
        background-color: #f0f0f0;
    }

#stackpage .frame:hover {
    background-color: #f0f0f0;
    text-decoration: none;
}

#stackpage .frame {
    padding: 2px;
    margin: 0 0 0 30px;
    border-bottom: 1px #ddd solid;
    cursor: pointer;
}

    #stackpage .frame h3 {
        padding: 5px;
        margin: 0;
    }

#stackpage .source {
    padding: 0;
}

    #stackpage .source ol li {
        font-family: Consolas, "Courier New", courier, monospace;
        white-space: pre;
    }

#stackpage .frame:hover .source .highlight li span {
    color: #fff;
    background: #b20000;
}

#stackpage .source ol.collapsible li {
    color: #888;
}

    #stackpage .source ol.collapsible li span {
        color: #606060;
    }

.page table {
    border-collapse: separate;
    border-spacing: 0;
    margin: 0 0 20px;
}

.page th {
    vertical-align: bottom;
    padding: 10px 5px 5px 5px;
    font-weight: 400;
    color: #a0a0a0;
    text-align: left;
}

.page td {
    padding: 3px 10px;
}

.page th, .page td {
    border-right: 1px #ddd solid;
    border-bottom: 1px #ddd solid;
    border-left: 1px transparent solid;
    border-top: 1px transparent solid;
    box-sizing: border-box;
}

    .page th:last-child, .page td:last-child {
        border-right: 1px transparent solid;
    }

    .page .length {
        text-align: right;
    }

a {
    color: #1ba1e2;
    text-decoration: none;
}

    a:hover {
        color: #13709e;
        text-decoration: underline;
    }

        </style>
    </head>
    <body>
        <h1>An unhandled exception occurred while processing the request.</h1>
            <div class="titleerror">InvalidOperationException: Failed to resolve IRuntimeEnvironment</div>
                <p class="location">Microsoft.Dnx.Runtime.RuntimeEnvironmentHelper.GetRuntimeEnvironment()</p>
        <ul id="header">
            <li id="stack" tabindex="1" class="selected">
                Stack
            </li>
            <li id="query" tabindex="2">
                Query
            </li>
            <li id="cookies" tabindex="3">
                Cookies
            </li>
            <li id="headers" tabindex="4">
                Headers
            </li>
        </ul>

        <div id="stackpage" class="page">
            <ul>

                    <li>
                        <h2 class="stackerror">InvalidOperationException: Failed to resolve IRuntimeEnvironment</h2>
                        <ul>
                            <li class="frame" tabindex="6">

                                    <h3>Microsoft.Dnx.Runtime.RuntimeEnvironmentHelper.GetRuntimeEnvironment()</h3>

                            </li>
                            <li class="frame" tabindex="7">

                                    <h3>System.Lazy`1.CreateValue()</h3>

                            </li>
                            <li class="frame" tabindex="8">

                                    <h3>System.Lazy`1.LazyInitValue()</h3>

                            </li>
                            <li class="frame" tabindex="9">

                                    <h3>Microsoft.Dnx.Runtime.RuntimeEnvironmentHelper.&lt;&gt;c.&lt;.cctor&gt;b__10_0()</h3>

                            </li>
                            <li class="frame" tabindex="10">

                                    <h3>System.Lazy`1.CreateValue()</h3>

                            </li>
                            <li class="frame" tabindex="11">

                                    <h3>System.Lazy`1.LazyInitValue()</h3>

                            </li>
                            <li class="frame" tabindex="12">

                                    <h3>Microsoft.Dnx.Runtime.FrameworkReferenceResolver.GetReferenceAssembliesPath()</h3>

                            </li>
                            <li class="frame" tabindex="13">

                                    <h3>Microsoft.Dnx.Runtime.FrameworkReferenceResolver.GetFrameworkInformation(FrameworkName targetFramework)</h3>

                            </li>
                            <li class="frame" tabindex="14">

                                    <h3>System.Collections.Generic.DictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory)</h3>

                            </li>
                            <li class="frame" tabindex="15">

                                    <h3>Microsoft.Dnx.Runtime.FrameworkReferenceResolver.TryGetAssembly(String name, FrameworkName targetFramework, String&amp; path, Version&amp; version)</h3>

                            </li>
                            <li class="frame" tabindex="16">

                                    <h3>Microsoft.Dnx.Runtime.ReferenceAssemblyDependencyResolver.GetDescription(LibraryRange libraryRange, FrameworkName targetFramework)</h3>

                            </li>
                            <li class="frame" tabindex="17">

                                    <h3>Microsoft.Dnx.Runtime.ApplicationHostContext.Initialize(ApplicationHostContext context)</h3>

                            </li>
                            <li class="frame" tabindex="18">

                                    <h3>Microsoft.Dnx.ApplicationHost.RuntimeLibraryManager.&lt;&gt;c__DisplayClass1_0.&lt;.ctor&gt;b__0()</h3>

                            </li>
                            <li class="frame" tabindex="19">

                                    <h3>System.Lazy`1.CreateValue()</h3>

                            </li>
                            <li class="frame" tabindex="20">

                                    <h3>--- End of stack trace from previous location where exception was thrown ---</h3>

                            </li>
                            <li class="frame" tabindex="21">

                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" tabindex="22">

                                    <h3>System.Lazy`1.get_Value()</h3>

                            </li>
                            <li class="frame" tabindex="23">

                                    <h3>Microsoft.Dnx.ApplicationHost.RuntimeLibraryManager.GetReferencingLibraries(String name)</h3>

                            </li>
                            <li class="frame" tabindex="24">

                                    <h3>System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__14`2.MoveNext()</h3>

                            </li>
                            <li class="frame" tabindex="25">

                                    <h3>System.Linq.Enumerable.&lt;DistinctIterator&gt;d__81`1.MoveNext()</h3>

                            </li>
                            <li class="frame" tabindex="26">

                                    <h3>System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()</h3>

                            </li>
                            <li class="frame" tabindex="27">

                                    <h3>System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__14`2.MoveNext()</h3>

                            </li>
                            <li class="frame" tabindex="28">

                                    <h3>System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()</h3>

                            </li>
                            <li class="frame" tabindex="29">

                                    <h3>System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)</h3>

                            </li>
                            <li class="frame" tabindex="30">

                                    <h3>System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)</h3>

                            </li>
                            <li class="frame" tabindex="31">

                                    <h3>Microsoft.AspNet.Mvc.Controllers.DefaultControllerTypeProvider.get_ControllerTypes()</h3>

                            </li>
                            <li class="frame" tabindex="32">

                                    <h3>Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorProvider.BuildModel()</h3>

                            </li>
                            <li class="frame" tabindex="33">

                                    <h3>Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorProvider.GetDescriptors()</h3>

                            </li>
                            <li class="frame" tabindex="34">

                                    <h3>Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)</h3>

                            </li>
                            <li class="frame" tabindex="35">

                                    <h3>Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorsCollectionProvider.GetCollection()</h3>

                            </li>
                            <li class="frame" tabindex="36">

                                    <h3>Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorsCollectionProvider.get_ActionDescriptors()</h3>

                            </li>
                            <li class="frame" tabindex="37">

                                    <h3>Microsoft.AspNet.Mvc.Routing.AttributeRoute.GetInnerRoute()</h3>

                            </li>
                            <li class="frame" tabindex="38">

                                    <h3>Microsoft.AspNet.Mvc.Routing.AttributeRoute.RouteAsync(RouteContext context)</h3>

                            </li>
                            <li class="frame" tabindex="39">

                                    <h3>Microsoft.AspNet.Routing.RouteCollection.&lt;RouteAsync&gt;d__9.MoveNext()</h3>

                            </li>
                            <li class="frame" tabindex="40">

                                    <h3>--- End of stack trace from previous location where exception was thrown ---</h3>

                            </li>
                            <li class="frame" tabindex="41">

                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)</h3>

                            </li>
                            <li class="frame" tabindex="42">

                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" tabindex="43">

                                    <h3>Microsoft.AspNet.Builder.RouterMiddleware.&lt;Invoke&gt;d__4.MoveNext()</h3>

                            </li>
                            <li class="frame" tabindex="44">

                                    <h3>--- End of stack trace from previous location where exception was thrown ---</h3>

                            </li>
                            <li class="frame" tabindex="45">

                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)</h3>

                            </li>
                            <li class="frame" tabindex="46">

                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" tabindex="47">

                                    <h3>Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.&lt;Invoke&gt;d__6.MoveNext()</h3>

                            </li>
                        </ul>
                    </li>
            </ul>
        </div>

        <div id="querypage" class="page">
                <p>No QueryString data.</p>
        </div>

        <div id="cookiespage" class="page">
                <table>
                    <thead>
                        <tr>
                            <th>Variable</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                                <tr>
                                    <td>SohiCurrentSite</td>
                                    <td>1019</td>
                                </tr>
                    </tbody>
                </table>
        </div>
        <div id="headerspage" class="page">
                <table>
                    <thead>
                        <tr>
                            <th>Variable</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                                <tr>
                                    <td>Accept</td>
                                    <td>text/html,application/xhtml&#x2B;xml,application/xml;q=0.9,*/*;q=0.8</td>
                                </tr>
                                <tr>
                                    <td>Accept-Encoding</td>
                                    <td>gzip, deflate</td>
                                </tr>
                                <tr>
                                    <td>Accept-Language</td>
                                    <td>en,mt;q=0.5</td>
                                </tr>
                                <tr>
                                    <td>Connection</td>
                                    <td>Keep-Alive</td>
                                </tr>
                                <tr>
                                    <td>Cookie</td>
                                    <td>SohiCurrentSite=1019</td>
                                </tr>
                                <tr>
                                    <td>DNT</td>
                                    <td>1</td>
                                </tr>
                                <tr>
                                    <td>Host</td>
                                    <td>192.168.0.209:5010</td>
                                </tr>
                                <tr>
                                    <td>User-Agent</td>
                                    <td>Mozilla/5.0 (X11; Linux i686; rv:43.0) Gecko/20100101 Firefox/43.0</td>
                                </tr>
                                <tr>
                                    <td>X-Forwarded-For</td>
                                    <td>192.168.0.204:51962</td>
                                </tr>
                    </tbody>
                </table>
        </div>
        <script>
            //<!--
            (function (window, undefined) {
    "use strict";

    function $(selector, element) {
        return new NodeCollection(selector, element);
    }

    function NodeCollection(selector, element) {
        this.items = [];
        element = element || window.document;

        var nodeList;

        if (typeof (selector) === "string") {
            nodeList = element.querySelectorAll(selector);
            for (var i = 0, l = nodeList.length; i < l; i++) {
                this.items.push(nodeList.item(i));
            }
        } else if (selector.tagName) {
            this.items.push(selector);
        } else if (selector.splice) {
            this.items = this.items.concat(selector);
        }
    }

    NodeCollection.prototype = {
        each: function (callback) {
            for (var i = 0, l = this.items.length; i < l; i++) {
                callback(this.items[i], i);
            }
            return this;
        },

        children: function (selector) {
            var children = [];

            this.each(function (el) {
                children = children.concat($(selector, el).items);
            });

            return $(children);
        },

        hide: function () {
            this.each(function (el) {
                el.style.display = "none";
            });

            return this;
        },

        toggle: function () {
            this.each(function (el) {
                el.style.display = el.style.display === "none" ? "" : "none";
            });

            return this;
        },

        show: function () {
            this.each(function (el) {
                el.style.display = "";
            });

            return this;
        },

        addClass: function (className) {
            this.each(function (el) {
                var existingClassName = el.className,
                    classNames;
                if (!existingClassName) {
                    el.className = className;
                } else {
                    classNames = existingClassName.split(" ");
                    if (classNames.indexOf(className) < 0) {
                        el.className = existingClassName + " " + className;
                    }
                }
            });

            return this;
        },

        removeClass: function (className) {
            this.each(function (el) {
                var existingClassName = el.className,
                    classNames, index;
                if (existingClassName === className) {
                    el.className = "";
                } else if (existingClassName) {
                    classNames = existingClassName.split(" ");
                    index = classNames.indexOf(className);
                    if (index > 0) {
                        classNames.splice(index, 1);
                        el.className = classNames.join(" ");
                    }
                }
            });

            return this;
        },

        toggleClass: function (className) {
            this.each(function (el) {
                var classNames = el.className.split(" ");
                if (classNames.indexOf(className) >= 0) {
                    $(el).removeClass(className);
                } else {
                    $(el).addClass(className);
                }
            });

            return this;
        },

        attr: function (name) {
            if (this.items.length === 0) {
                return null;
            }

            return this.items[0].getAttribute(name);
        },

        on: function (eventName, handler) {
            this.each(function (el, idx) {
                var callback = function (e) {
                    e = e || window.event;
                    if (!e.which && e.keyCode) {
                        e.which = e.keyCode; // Normalize IE8 key events
                    }
                    handler.apply(el, [e]);
                };

                if (el.addEventListener) { // DOM Events
                    el.addEventListener(eventName, callback, false);
                } else if (el.attachEvent) { // IE8 events
                    el.attachEvent("on" + eventName, callback);
                } else {
                    el["on" + type] = callback;
                }
            });

            return this;
        },

        click: function (handler) {
            return this.on("click", handler);
        },

        keypress: function (handler) {
            return this.on("keypress", handler);
        }
    };

    function frame(el) {
        $(el).children(".source .collapsible").toggle();
    }

    function tab(el) {
        var unselected = $("#header .selected").removeClass("selected").attr("id");
        var selected = $(el).addClass("selected").attr("id");

        $("#" + unselected + "page").hide();
        $("#" + selected + "page").show();
    }

    $(".collapsible").hide();
    $(".page").hide();
    $("#stackpage").show();

    $(".frame")
        .click(function () {
            frame(this);
        })
        .keypress(function (e) {
            if (e.which === 13) {
                frame(this);
            }
        });

    $("#header li")
        .click(function () {
            tab(this);
        })
        .keypress(function (e) {
            if (e.which === 13) {
                tab(this);
            }
        });
})(window);
            //-->
        </script>
    </body>
</html>
```

**Comment by davidfowl** [comment] 2015-10-07 07:31
A screenshot would have been more useful than the html...

**Comment by davidfowl** [comment] 2015-10-07 07:32
@muratg We should investigate this one to see if there's a beta8 regression. I'm guessing it only happens with x64 (I've seen something similar with helios)

**Comment by borgdylan** [comment] 2015-10-07 07:32
![repro](https://cloud.githubusercontent.com/assets/7761010/10331510/4f16188a-6cd6-11e5-8f4d-5ba56142e8f8.png)

**Comment by borgdylan** [comment] 2015-10-07 07:32
Should I try without IIS, in self-host mode as well?

**Comment by davidfowl** [comment] 2015-10-07 07:33
Yes. Also try 32 bit.

**Comment by borgdylan** [comment] 2015-10-07 07:36
In self-host it fails as well. I do not have a 32-bit windows server to test with. Would using the 32-bit dnx on the x64 server suffice?

**Comment by davidfowl** [comment] 2015-10-07 07:38
Yep

**Comment by borgdylan** [comment] 2015-10-07 07:40
Also, the failure seems to occur if requesting a static file that does not exist i.e. when a 404 should be output. SO this may be routing related as well.

**Comment by borgdylan** [comment] 2015-10-07 07:43
The x86 DNX exhibits the same behaviour when tried in self-host mode. Another title change is in order.

**Comment by borgdylan** [comment] 2015-10-07 08:05
I think the issue resides with how the runtime environment information is being passed in by the native clr DNX bootsrappers.

**Comment by davidfowl** [comment] 2015-10-07 08:06
Not quite. The problem is that the call context is being lost by the time this method is executing. It could be caused by tons of different things but there's an easy way to make this reliable.

**Comment by davidfowl** [comment] 2015-10-07 08:07
Does it happen when you use kestrel?

**Comment by borgdylan** [comment] 2015-10-07 08:08
I haven't tried yet but I will. I tried using a purely managed approach as it usually has less bugs.

**Comment by davidfowl** [comment] 2015-10-07 08:20
I don't think Nowin is flowing the execution context by default. Can you try configuring the ServerBuilder to flow it always and see if it works?

**Comment by borgdylan** [comment] 2015-10-07 08:21
Does kestrel have an example of that?

**Comment by davidfowl** [comment] 2015-10-07 08:23
Kestrel does it by default. Nowin doesn't seem to preserve it by default.

**Comment by borgdylan** [comment] 2015-10-07 08:27
I tried kestrel locally to see if it works as well but it crashes on startup:
```
System.TypeLoadException: Could not load type 'Microsoft.AspNet.Server.Kestrel.Http.FrameHeaders' from assembly 'Microsoft.AspNet.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Microsoft.AspNet.Server.Kestrel.Http.FrameRequestHeaders+Enumerator' from assembly 'Microsoft.AspNet.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Microsoft.AspNet.Server.Kestrel.Http.FrameResponseHeaders+Enumerator' from assembly 'Microsoft.AspNet.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by davidfowl** [comment] 2015-10-07 08:28
Looks like a version mismatch. I'll try it locally with a simple example.

**Comment by borgdylan** [comment] 2015-10-07 08:30
Is the execution context in the feature collection? I am trying to fix the nowin server factory as you said.

**Comment by davidfowl** [comment] 2015-10-07 08:32
@borgdylan Nowin has a ServerBuilder option https://github.com/Bobris/Nowin/blob/master/Nowin/ServerBuilder.cs#L20

Try doing `builder.SetExecutionContextFlow(ExecutionContextFlow.Always)`

**Comment by borgdylan** [comment] 2015-10-07 08:49
The option is named ```Flow``` and you were right, it is working now using self-host. I will be trying IIS shortly.

**Comment by borgdylan** [comment] 2015-10-07 08:52
I had to use ```builder.SetExecutionContextFlow(ExecutionContextFlow.Flow)``` and it also works on th e platform handler.

**Comment by davidfowl** [comment] 2015-10-07 09:26
Use that as a workaround for now. We'll reduce the reliance on CallContext but some things will just break in general without it. IHttpContextAccessor also relies on it.

**Comment by borgdylan** [comment] 2015-10-08 07:12
In fact, I do need to access the HTTP context to read the client's IP etc. The workaround is working fine for now.

**Comment by victorhurdugaci** [comment] 2015-10-09 17:13
@borgdylan what's the simplest repro that you have? I'm not able to reproduce this with 1.0.0-rc1-15844

**Comment by borgdylan** [comment] 2015-10-09 17:25
The one in the repo I mentioned used to repro it. I applied teh workaround suggested by @davidfowl to that code since I needed a fix to keep on working and meet my deadlines.

**Comment by borgdylan** [comment] 2015-10-09 17:26
To repro you will need https://github.com/borgdylan/aspnet5-repros, with https://github.com/borgdylan/aspnet5-repros/blob/master/NowinServerFactory/NowinServerFactory.cs#L58 commented out. Its an execution context related bug.

**Comment by victorhurdugaci** [comment] 2015-10-09 20:47
Since beta8 hosting sets this as a HttpContext feature instead of thread local. Components should now depend on the feature instead of thread continuity. If there are remaining place that don't work, we can address them. 

https://github.com/aspnet/Hosting/commit/49520a2a73251a9f718743df4a43d26514021767#diff-212af5584d052a0246bb112580efc730R54

This doesn't look like a dnx bug.

**Comment by davidfowl** [comment] 2015-10-13 12:21
@victorhurdugaci closing this out. We're going to remove this type from the DNX https://github.com/aspnet/dnx/issues/2927

**Closed by davidfowl** 2015-10-13 12:21 UTC
Labels: 1 - Ready, bug
