### ISSUE TITLE
Localized resources from CSProj PCL P2P ref not resolved from XPROJ

### ISSUE THREAD

**Issue by onovotny** [aspnet/dnx#3190] opened 2015-11-22 19:10 UTC
I am in the middle of trying to get Humanizer tested under DNX. Humanizer is a regular PCL/Profile 259 as a CSPROJ. It has a ResX file with about 39 localized versions, so it generates about 39 `<locale>\Humanizer.resources.dll` files alongside its main library dll.

In the process, I created a DNX test library for Humanizer and added a reference to Humanizer. VS created a `wrap/Humanizer/project.json` file for it and am able to compile all of the tests. However, when I try to run them, I get tons of errors about `Humanizer.resources` not being found. This happens both in Test Explorer and the command line via `dnx test`.

You can repro this in the `device-runner` branch of Humanizer: https://github.com/Humanizr/Humanizer/tree/features/device-runner/src/Humanizer.Tests.Dnx

```
   YearsAgo(years: 2, expected: "för 2 år sedan") [FAIL]
      System.IO.FileNotFoundException : Could not find file 'Humanizer.resources'.
      Stack Trace:
           at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
           at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
           at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
           at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
           at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
           at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
        C:\Users\oren\Source\Git\Humanizer\src\Humanizer\Localisation\Resources.cs(22,0): at Humanizer.Localisation.Resources.GetResource(String resourceKey, CultureInfo culture)
        C:\Users\oren\Source\Git\Humanizer\src\Humanizer\Localisation\Formatters\DefaultFormatter.cs(97,0): at Humanizer.Localisation.Formatters.DefaultFormatter.Format(String resourceKey, Int32 number)
        C:\Users\oren\Source\Git\Humanizer\src\Humanizer\Localisation\Formatters\DefaultFormatter.cs(70,0): at Humanizer.Localisation.Formatters.DefaultFormatter.GetResourceForDate(TimeUnit unit, Tense timeUnitTense, Int32 count)
        C:\Users\oren\Source\Git\Humanizer\src\Humanizer\Localisation\Formatters\DefaultFormatter.cs(40,0): at Humanizer.Localisation.Formatters.DefaultFormatter.DateHumanize(TimeUnit timeUnit, Tense timeUnitTense, Int32 unit)
        C:\Users\oren\Source\Git\Humanizer\src\Humanizer\DateTimeHumanizeStrategy\DateTimeHumanizeAlgorithms.cs(113,0): at Humanizer.DateTimeHumanizeStrategy.DateTimeHumanizeAlgorithms.DefaultHumanize(DateTime input, DateTime comparisonBase, CultureInfo culture)
        C:\Users\oren\Source\Git\Humanizer\src\Humanizer\DateTimeHumanizeStrategy\DefaultDateTimeHumanizeStrategy.cs(16,0): at Humanizer.DateTimeHumanizeStrategy.DefaultDateTimeHumanizeStrategy.Humanize(DateTime input, DateTime comparisonBase, CultureInfo culture)
        C:\Users\oren\Source\Git\Humanizer\src\Humanizer\DateHumanizeExtensions.cs(27,0): at Humanizer.DateHumanizeExtensions.Humanize(DateTime input, Boolean utcDate, Nullable`1 dateToCompareAgainst, CultureInfo culture)
        C:\Users\oren\source\git\Humanizer\src\Humanizer.Tests.Shared\DateHumanize.cs(32,0): at Humanizer.Tests.DateHumanize.VerifyWithDate(String expectedString, TimeSpan deltaFromBase, CultureInfo culture, DateTime baseDate, DateTime baseDateUtc)
        C:\Users\oren\source\git\Humanizer\src\Humanizer.Tests.Shared\DateHumanize.cs(19,0): at Humanizer.Tests.DateHumanize.VerifyWithCurrentDate(String expectedString, TimeSpan deltaFromNow, CultureInfo culture)
        C:\Users\oren\source\git\Humanizer\src\Humanizer.Tests.Shared\DateHumanize.cs(79,0): at Humanizer.Tests.DateHumanize.Verify(String expectedString, Int32 unit, TimeUnit timeUnit, Tense tense, Nullable`1 precision, CultureInfo culture, Nullable`1 baseDate, Nullable`1 baseDateUtc)
        C:\Users\oren\source\git\Humanizer\src\Humanizer.Tests.Shared\Localisation\sv\DateHumanizeTests.cs(104,0): at Humanizer.Tests.Localisation.sv.DateHumanizeTests.YearsAgo(Int32 years, String expected)
```

**Comment by onovotny** [comment] 2015-11-23 13:13
So I can confirm that when I switch to a NuGet reference to the same project, the tests execute correctly. This appears to be a local P2P issue.

**Comment by kirthik** [comment] 2015-11-23 18:45
Yes this is a bug. Its a dupe of - https://github.com/aspnet/dnx/issues/3047

**Comment by muratg** [comment] 2015-12-18 15:54
This issue was moved to dotnet/cli#550

**Closed by muratg** 2015-12-18 15:54 UTC
Labels: Move to DotNet CLI
