### ISSUE TITLE
Adding reference to a class library project with a common (say, default) name in ASP.NET 5 can result it resolving that assembly from nuget instead

### ISSUE THREAD

**Issue by barrytang** [aspnet/dnx#2430] opened 2015-08-06 20:49 UTC
Affected Branch: 
Affected Build: 
Affected Product Language: 
Steps to reproduce:
1.  Create new ASP.NET 5 Console application
2. Add a default PCL targeting NET 4.6, UAP 10, and ASP.NET COre 5.0 to the solution.  Make sure its name is ClassLibrary1
3. Right click on References, Add Reference, add reference to the PCL from the console app.
4. Build the solution.
 
Expected:  Either it works, or gives me some errors.  I dunno.
Actual:  Holy wow, it ends up installing something named ClassLibrary1 from

**Comment by barrytang** [comment] 2015-08-06 20:50
![image](https://cloud.githubusercontent.com/assets/1648865/9123079/0a464726-3c42-11e5-868e-4cc81db5d0fe.png)

**Comment by davidfowl** [comment] 2015-08-07 02:50
Dupe of https://github.com/aspnet/dnx/issues/438

**Closed by davidfowl** 2015-08-07 02:50 UTC
