### ISSUE TITLE
Make `kpm` case-insensitive on Windows

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnx#1361] opened 2015-03-10 14:34 UTC
`kpm` commands are currently case-sensitive even on Windows.  For example,
1. build repo to ensure everything is restored and up-to-date
2. change the case of a folder used elsewhere e.g.
 - Microsoft.AspNet.Razor -> Microsoft.AspNet.Razor2
 - Microsoft.AspNet.Razor2 -> Microsoft.AspNET.Razor
3. (note `git status` shows nothing has changed at this point)
4. `kpm restore` in a project depending on the renamed one e.g. Microsoft.AspNet.Razor.Runtime
5. (note `project.lock.json` shows a dependency on downloaded .nupkg)
6. `kpm build` in step 4. project e.g. Microsoft.AspNet.Razor.Runtime
7. observe build failures if dependency contains changes the other project references

similar failures occur when dependencies are locked (i.e. `kpm restore --lock` before the rename and skip step 4) even when the projects are otherwise unchanged.

**Comment by glennc** [comment] 2015-03-13 17:05
In general case sensitivity is by design in order to provide some level of consistency across the platforms. Case sensitivity matters in non-windows platforms, and works on Windows. So we are case sensitive.

If I understand this you are saying that changing the case of a folder and then building fails, that would be by design as well given that we are case sensitive. Running `kpm restore` would presumably download the package again with the correct case. 

Does it break your workflow somehow?

**Comment by dougbu** [comment] 2015-03-13 18:16
@glennc main issue is that errors don't show up when I expect; `kpm restore` appears to work but `kpm build` fails when project.json and actual folder don't exactly match.

**Comment by davidfowl** [comment] 2015-03-28 11:01
See https://github.com/aspnet/dnx/pull/1511

**Comment by davidfowl** [comment] 2015-03-28 11:02
Closing this bug out. See https://github.com/aspnet/dnx/issues/1470

**Closed by davidfowl** 2015-03-28 11:02 UTC
