### ISSUE TITLE
beta6: manual restore fails to find package System.Reflection in the feed with 404

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2296] opened 2015-07-20 22:37 UTC
There is an exception in the dnu output:

Warning: FindPackagesById: System.Reflection
  Response status code does not indicate success: 404 (The specified blob does not exist.).
  GET https://api.nuget.org/v3/index.jsonFindPackagesById()?id='System.Reflection'

**Comment by ChengTian** [comment] 2015-07-20 22:42
@abpiskunov , could you please list all feeds you are using here? Please also attach your `project.json` if possible. Thanks!

**Comment by abpiskunov** [comment] 2015-07-20 22:45
Here is the full dnu output:
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\antonpis\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin\dnx.exe "C:\Users\antonpis\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll" restore "c:\users\antonpis\documents\visual studio 2015\Projects\ConsoleApp6\src\ConsoleApp6" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility CLR-x86-1.0.0-beta6-12254
Restoring packages for c:\users\antonpis\documents\visual studio 2015\Projects\ConsoleApp6\src\ConsoleApp6\project.json
  GET https://api.nuget.org/v3/index.json
  GET https://api.nuget.org/v3/index.jsonFindPackagesById()?id='System.Reflection'
Warning: FindPackagesById: System.Reflection
  Response status code does not indicate success: 404 (The specified blob does not exist.).
  GET https://api.nuget.org/v3/index.jsonFindPackagesById()?id='System.Reflection'
Warning: FindPackagesById: System.Reflection
  Response status code does not indicate success: 404 (The specified blob does not exist.).
  GET https://api.nuget.org/v3/index.jsonFindPackagesById()?id='System.Reflection'
Error: FindPackagesById: System.Reflection
  Response status code does not indicate success: 404 (The specified blob does not exist.).
----------
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (The specified blob does not exist.).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Framework.PackageManager.Restore.NuGet.HttpSource.<GetAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.NuGetv2Feed.<FindPackagesByIdAsyncCore>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass69_0.<<Execute>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<Execute>d__69.MoveNext()
----------
Restore failed
Response status code does not indicate success: 404 (The specified blob does not exist.).
NuGet Config files used:
    C:\Users\antonpis\AppData\Roaming\NuGet\NuGet.Config
    c:\users\antonpis\documents\visual studio 2015\Projects\ConsoleApp6\NuGet.Config
Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft Web Tools\DNU

**Comment by abpiskunov** [comment] 2015-07-20 22:45
Here is project.json:
{
  "version": "1.0.0-*",
  "description": "ConsoleApp8 Console Application",
  "authors": [ "antonpis" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
  },

  "commands": {
    "ConsoleApp8": "ConsoleApp8"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-23109",
        "System.Console": "4.0.0-beta-23109",
        "System.Linq": "4.0.0-beta-23109",
        "System.Threading": "4.0.10-beta-23109",
        "Microsoft.CSharp": "4.0.0-beta-23109"
      }
    }
  }
}

**Comment by ChengTian** [comment] 2015-07-20 22:45
One more thing, what's the version of DNX you are using?

**Comment by ChengTian** [comment] 2015-07-20 22:46
Never mind. I can see it is beta6 DNX in the output

**Comment by abpiskunov** [comment] 2015-07-20 22:47
Latest checked in to WTE Beta6 (dnx-clr-win-x86.1.0.0-beta6)

**Comment by ChengTian** [comment] 2015-07-20 23:22
Because there is an exception thrown during access to HTTP cache, “dnu restore” mistakenly recognized V3 feeds as V2 feeds. The root cause is https://github.com/aspnet/dnx/issues/2291 and I already pushed fix this morning. Please wait for next build of DNX available later.

**Closed by ChengTian** 2015-07-20 23:22 UTC

**Comment by ChengTian** [comment] 2015-07-20 23:32
Dup of https://github.com/aspnet/dnx/issues/2291
