### ISSUE TITLE
DNU has a nasty exception stack on failure to restore package due to timeouts

### ISSUE THREAD

**Issue by wholroyd** [aspnet/dnx#2389] opened 2015-07-31 23:11 UTC
As seen in the gist https://gist.github.com/wholroyd/00644841a8d5fc000beb for my https://github.com/wholroyd/fake-dnx project.

While I get there are so many retries you could do until it's just not worth it anymore, the exception stack is horrible and could use a better message in it's place. The number of packages it tries to download all at once I wish was smaller. Lower bandwidth, unreliable networks like traveling laptops make this situation happen much more often than I'd like to admit for the year 2015.

**Comment by davidfowl** [comment] 2015-07-31 23:14
What mono version?

**Comment by wholroyd** [comment] 2015-07-31 23:22
The one defined in the microsoft/aspnet docker image tagged latest for beta6 - appears to be based on mono:4.0.1.

Also if you notice in the gist, some of the packages that had timed out were previously and successfully retrieved, but it attempts to retrieve it again. For instance, look at the Microsoft.AspNet.Diagnostics* packages. I think it would be more efficient to use what was already retrieved, checking a local cache of some sort for the current session?

**Comment by davidfowl** [comment] 2015-07-31 23:30
This bug is a dupe of other bugs:
- https://github.com/aspnet/dnx/issues/452
- https://github.com/aspnet/dnx/issues/1590

> Also if you notice in the gist, some of the packages that had timed out were previously and successfully retrieved, but it attempts to retrieve it again. For instance, look at the Microsoft.AspNet.Diagnostics* packages. I think it would be more efficient to use what was already retrieved, checking a local cache of some sort for the current session?

If the versions are not wildcarded that that's the case. If you use * then it'll always try to hit your configured feeds to find the latest package.

**Closed** 2015-07-31 23:30 UTC

**Comment by wholroyd** [comment] 2015-07-31 23:36
I did not see those, thanks!
