### ISSUE TITLE
Wrapped 4.5 project with NuGet package reference cannot be published

### ISSUE THREAD

**Issue by glennc** [aspnet/dnx#2016] opened 2015-06-03 22:47 UTC
* Empty web application referencing a 4.5 csproj
* Add NuGet package (Tried with Moq as well as Microsoft.ServiceFabric.Actor package)

Resulting application can run, and build, but if you try and publish you get the error below. If you go to the wrapped projects project.json and run `dnu restore` to get a lock file then the publish will work.

Potentially related is that when you first create the csproj it targets net452 and initially I see errors resolving the packages. The problem appears to go away without me actually doing anything that should've resolved it if it was a problem. So it might be nothing, but I thought I would mention it.

```
Using Project dependency WrapRepro 1.0.0 for DNX,Version=v4.5.1
  Copying source code from Project dependency WrapRepro
    Source C:\code\WrapRepro\src\WrapRepro\project.json
    Target C:\code\WrapRepro\output\approot\src\WrapRepro

Using Project dependency ClassLibrary1 1.0.0 for .NETFramework,Version=v4.5
  Packing nupkg from Project dependency ClassLibrary1
    Source C:\code\WrapRepro\wrap\ClassLibrary1\project.json
    Target C:\code\WrapRepro\output\approot\packages\ClassLibrary1\1.0.0

Building ClassLibrary1 for .NETFramework,Version=v4.5
  Using Project dependency ClassLibrary1 1.0.0
    Source: C:\code\WrapRepro\wrap\ClassLibrary1\project.json

  Unable to resolve dependency Moq 4.2.1502.0911

  Using Assembly dependency framework/mscorlib 4.0.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll

  Using Assembly dependency framework/System 4.0.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll

  Using Assembly dependency framework/System.Core 4.0.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll

  Using Assembly dependency framework/Microsoft.CSharp 4.0.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll

C:\code\WrapRepro\wrap\ClassLibrary1\project.json(11,15): error: Dependency Moq >= 4.2.1502.0911 could not be resolved

Build failed.
    0 Warnings(s)
    1 Error(s)
```

@ChengTian @davidfowl

**Comment by ChengTian** [comment] 2015-06-05 06:50
I just found that
```
Resulting application can run, and build, but if you try and publish you get the error below.
```
is not true.

Looks like VS does not update wrapper project.json until you do some actions like build/publish. After adding NuGet dependency for your csproj, you should try **doing build several times**, after one or two successful build, you'll hit "dependency missing" error and you'll see Reference Error like
![capture](https://cloud.githubusercontent.com/assets/1383883/8000739/5f274192-0b13-11e5-9a14-063fb6f299be.PNG)

This is a complex bug caused by bugs in both DNX and Tooling. I filed a bug in Tooling repo https://github.com/aspnet/Tooling-Internal/issues/362

**Comment by muratg** [comment] 2015-06-08 15:55
This is approved for Beta 5.

**Comment by ChengTian** [comment] 2015-06-10 22:30
Fix on DNX side is checked in. I'll follow up with Tooling team and do some integration tests when the fix on their side is available.

**Comment by nguyenquyhy** [comment] 2015-06-11 02:22
Do we have any workaround for the moment?

**Comment by PradeepKadubandi** [comment] 2015-06-11 14:23
@ChengTian , I think the broken references you are seeing in your repro are probably because you have the csproj targeting .Net 4.5.2 whereas xproj targeting 4.5.1?

**Comment by ChengTian** [comment] 2015-06-11 16:59
Talked to @PradeepKadubandi offline and Tooling team should be able to make a simple fix on their side. I'll close this on DNX side because my fix was already checked in.

**Closed by ChengTian** 2015-06-11 16:59 UTC
Labels: 3 - Done, bug

**Comment by ChengTian** [comment] 2015-06-11 21:08
Talked to @loudej and he thinks we don't need to move local NuGet packages to DNX packages folder. We can just make project.json of wrapper project up-to-date and always call restore to install necessary packages. Will revert https://github.com/aspnet/dnx/commit/60de972dd41d1f4924fcb6fbc15d7e7d503c9555.

**Comment by Jonas82** [comment] 2015-07-26 20:23
Running beta5 I get the same issue when publishing.

**Comment by ChengTian** [comment] 2015-07-27 04:44
@Jonas82 , thanks for reporting. The issue was partially fixed and the remaining part is filed at: https://github.com/aspnet/dnx/issues/2352

**Comment by PradeepKadubandi** [comment] 2015-08-10 21:17
Hi @Jonas82,

I want to follow up to see if you are still seeing this issue after getting Visual Studio 2015 RTM, we believe we fixed that scenario there and want to see if you are still facing any issues, can you try with Visual Studio 2015 RTM and update us?

Thanks!

**Comment by jtdunlop** [comment] 2015-08-16 22:29
I have VS 2015 Professional REL with beta5 and am getting this issue. There are no errors reported in my references. I've also seen this issue mentioned with beta6, unknown version of VS: http://stackoverflow.com/questions/31750350/vnext-beta6-deployment-error-the-dependency-entityframework-6-1-2-could-not. The generated wrap project.json has the failing dependencies listed.

**Comment by Jonas82** [comment] 2015-08-17 07:57
Hi @PradeepKadubandi 

Issue is still the same in RTM also with beta6. Workaround is still good.

Jonas

**Comment by BrewDawg** [comment] 2015-09-27 02:59
I have this exact same problem with beta 7, none of my references under the DNX 4.5.1 or DNX Core 5.0 can be found. I just installed tonight, have power shell 2.0, did all the DMVM update stuff, it all works, I can see the files in C:\Users\Mike Griffin\.dnx but Visual studio cannot find any of them

**Comment by jtdunlop** [comment] 2015-09-27 04:10
A better workaround is to get involved in the wrap process in project.json. This fixes pretty much all downstream issues from dev all the way through deploy.

"scripts": {
        "prerestore": [
            "dnu wrap ../epm.dal/epm.dal.csproj",
            "dnu wrap ../epm.logic/epm.logic.csproj",
            "dnu wrap ../epm.ui/epm.ui.csproj"
        ]
    },

**Comment by JasonRowe** [comment] 2015-10-02 21:07
I had no problem with this in beta 5. Seems this problem is back in beta 6 and beta 7.

**Comment by JasonRowe** [comment] 2015-10-02 21:32
In beta 5 my wrapped project.json looked like this and worked:

    {
      "version": "1.0.0-*",
      "frameworks": {
        "net451": {
          "wrappedProject":      "../../src/example.csproj",
          "bin": {
            "assembly": "../../src/example/obj/{configuration}/example.dll",
            "pdb": "../../src/example/obj/{configuration}/example.pdb"
            }
           }
         }
       }

In beta 7 it needed to be this:

    {
      "version": "1.0.0-*",
      "frameworks": {
        "net451": {
          "wrappedProject": "../../src/example.csproj",
          "bin": {
            "assembly": "../../src/example/obj/{configuration}/example.dll",
            "pdb": "../../src/example/obj/{configuration}/example.pdb"
          }
        },
        "dnx451": {
          "bin": {
            "assembly": "bin/Release/net451/example.dll",
            "pdb": "bin/Release/net451/example.pdb"
          }
        }
      }
    }

**Comment by glennc** [comment] 2015-10-14 22:52
Are you guys hitting issue https://github.com/aspnet/dnx/issues/2954?

**Comment by arankun** [comment] 2015-12-22 11:53
can you generate the "dnu wrap..." statements in the project.json without typing it?

**Comment by mrcaron** [comment] 2016-04-19 11:48
I'm hitting this with 1.0.0-RC1-update2
