### ISSUE TITLE
Using "bin" dependency type in ASPNET*50 framework project.json node throws NRE, needs useful message

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnx#1149] opened 2015-01-29 19:01 UTC
Having content like this in a project.json is totally acceptable today:

    "frameworks": {
        "aspnet50": {
        },
        "net45": {
            "dependencies": {
                "bin": {
                    "assembly": "../../../ClassLibrary3/ClassLibrary3/bin/Debug/YourClassLibrary.dll",
                    "pdb": "../../../ClassLibrary3/ClassLibrary3/bin/Debug/YourClassLibrary.pdb"
                }
            }
        }
    }
However, we don't really provide users who want to have direct binary dependencies in their ASPNET*50 targeting with messaging, instructions, or a direct way to do this.  Thus, it's reasonable that many of them will try something like this, in a cut-and-paste self educating manner:

    "frameworks": {
        "aspnet50": {
            "dependencies": {
                "bin": {
                    "assembly": "../../../ClassLibrary3/ClassLibrary3/bin/Debug/YourClassLibrary.dll",
                    "pdb": "../../../ClassLibrary3/ClassLibrary3/bin/Debug/YourClassLibrary.pdb"
                }
            }
        },
        "net45": {       }

... which while I full accept is not going to be a supported scenario, should have a better experience than throwing a NullReferenceException and quitting:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Framework.Runtime.UnresolvedDependencyProvider.GetDescription(LibraryRange libraryRange, FrameworkName targetFramework)
   at Microsoft.Framework.Runtime.WalkContext.Resolve(Dictionary`2 resolvedItems, IEnumerable`1 providers, LibraryRange packageKey, FrameworkName frameworkName)
   at Microsoft.Framework.Runtime.WalkContext.<>c__DisplayClass1_0.<Walk>b__0(Node node)
   at Microsoft.Framework.Runtime.WalkContext.<>c__DisplayClass4_0.<ForEach>b__0(Node node, Int32 _)
   at Microsoft.Framework.Runtime.WalkContext.ForEach[TState](Node root, TState state, Func`3 visitor)
   at Microsoft.Framework.Runtime.WalkContext.ForEach(Node root, Action`1 visitor)
   at Microsoft.Framework.Runtime.WalkContext.Walk(IEnumerable`1 dependencyResolvers, String name, SemanticVersion version, FrameworkName frameworkName)
   at Microsoft.Framework.Runtime.DependencyWalker.Walk(String name, SemanticVersion version, FrameworkName targetFramework)
   at Microsoft.Framework.Runtime.DefaultHost.Initialize()
   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
Press any key to continue . . .

**Comment by davidfowl** [comment] 2015-01-31 18:06
Yah, any null ref is bad.

**Comment by gulbanana** [comment] 2015-02-02 06:57
If the second scenario is not going to be supported, does that mean that the transitive closure of aspnet50 dependencies must all themselves be vnext/k projects?

**Comment by davidfowl** [comment] 2015-02-02 06:59
The second scenario doesn't make any sense. When you make an ASP.NET 5.0 project you use the new project type.

**Comment by gulbanana** [comment] 2015-02-02 07:13
Doesn't having a net45 dependency prevent you from running on the core clr?

I'm trying to write code that can be consumed either from an aspnetcore5 application running on .net core, as well as from a desktop application running on .net 4.5 or 4.6. In particular, I'm trying to understand the restrictions I'll have to follow in doing so. If the transitive dependencies must all use new project types, for example, then that would mean that I can't use C++/CLI or VB in those dependencies.

**Comment by davidfowl** [comment] 2015-02-02 07:20
Thats why the project contains more than one target framework by default, it cross compiles. This gives you the greatest flexibility when targeting multiple platforms. Don't conflate the project system with the target framework. 

Look at the project system like a nuget package. Today a nuget package can target multiple platforms, and depending on what project you choose (you can even target a PCL), you get a reference to the most compatible platform within that package. This is no different.

**Comment by davidfowl** [comment] 2015-02-02 07:27
@gulbanana  BTW if you want to have a conversation about the new project system in real time you can ask questions on https://jabbr.net/#/rooms/AspNetvNext.

**Comment by gulbanana** [comment] 2015-02-02 07:30
I think my conflation stems from not knowing whether the new project system is the *only* way to target certain frameworks. In particular, msbuild based projects do not seem to offer a way to build for core CLR. Therefore, building for core CLR requires using the new project system (and eschewing other languages, etc).

Have I just missed a way to have a csproj target .NET Core?

**Comment by gulbanana** [comment] 2015-02-02 07:31
Oh, thanks for the jabbr suggestion - I'll join it some time soon and ask there instead.

**Comment by anurse** [comment] 2015-07-24 18:12
I'm not seeing an exception (at least not any more), when I do the following

```json
{
    "frameworks": {
        "dnx451": {
            "bin": {
                "assembly": "[path/to/dll]",
                "pdb": "[path/to/pdb]"
            }
        }
    }
}
```

Note that unlike the original example, the `bin` property actually has to be a **peer** to `dependencies`, not a child node.

I'm going to close this since it looks like it has been fixed or isn't reproducible any more. Feel free to re-open if you're still encountering this issue!

**Closed by anurse** 2015-07-24 18:12 UTC
Labels: 1 - Ready, bug

**Comment by MattGal** [comment] 2015-07-24 21:27
It definitely fails much more nicely now.
