### ISSUE TITLE
beta6: when dnu can not find package in the feed, restore fails but there no errors sent via DTH and all references are resolved

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/dnx#2297] opened 2015-07-20 22:38 UTC
-	When I manually trigger restore for just created Console app I can see:
Warning: FindPackagesById: System.Reflection
  Response status code does not indicate success: 404 (The specified blob does not exist.).
  GET https://api.nuget.org/v3/index.jsonFindPackagesById()?id='System.Reflection'
What is wrong with that package? Why it is not in the feed?

-	Dnu returns error exist code, however there no unresolved dependencies and errors sent from DTH which results in valid Refernces node and empgy error list, however restore output shows error and asks user to check Error List. Why we don’t receive unresolved references and errors? (If I delete project.lock.json and restore I would receive unresolved references and errors as expected)

**Comment by ChengTian** [comment] 2015-07-20 23:25
Root cause is explained in https://github.com/aspnet/dnx/issues/2296. When `dnu restore` fails because of an exception, it doesn't get a chance to update lock file, so you still have leftover from previous restore and it gives DTH the illusion that all dependencies are correctly resolved.

All those issues should be fixed after next build of DNX is available.

**Closed by ChengTian** 2015-07-20 23:25 UTC

**Comment by ChengTian** [comment] 2015-07-20 23:32
Dup of https://github.com/aspnet/dnx/issues/2291
