### ISSUE TITLE
dnu cache broken

### ISSUE THREAD

**Issue by ggrnd0** [aspnet/dnx#1848] opened 2015-05-12 19:42 UTC
I use dnx-clr-win-x86-1.0.0-beta5-11672
________
I updated dependency versions before packages was published.
First restore said 404. 
After packages was uploaded `dnu restore` did not send any requests for repositories, allways said 404.

There 2 questions:
1) What is the reason for 2 caches `.dnx/packages` and `AppData/dnu/`?
2) Why dnu caches 404 responces?! WTF?!

**Comment by davidfowl** [comment] 2015-05-12 19:45
> 1) What is the reason for 2 caches .dnx/packages and AppData/dnu/?

AppData/dnu is the http response cache. It's used to avoid making http requests over and over (the TTL is configurable) between calls to dnu. The `~/.dnx/packages` is not a cache. It's where packages are located.

> 2) Why dnu caches 404 responces?! WTF?!

We don't cache 404s. You must be running a very old version of dnu or the server isn't sending back an actual 404 status code. We're fixing the issue where the response sent back from the server is 2XX but the response is invalid.

**Comment by ggrnd0** [comment] 2015-05-12 19:49
`dnx-clr-win-x86-1.0.0-beta5-11672` about 10 days old. Is it too old?

Fiddler do not show any http requests on dnu restore.
After `AppData/dnu` was removed all packages downloaded.

Can someone try to reproduce?

**Comment by ggrnd0** [comment] 2015-05-12 19:59
> `AppData/dnu` is the http response cache

Why does not download full repo index on command like `dnu upgrade $gallery`.
This is popular practice. For example, linux package managers.
And there would be separate package and gallery caches, and guarantied way to force updates.

**Comment by davidfowl** [comment] 2015-05-12 20:01
Because that's not how NuGet works today. Maybe one day we'll get there

**Comment by davidfowl** [comment] 2015-05-12 20:04
> dnx-clr-win-x86-1.0.0-beta5-11672 about 10 days old. Is it too old?

We haven't cached non 200 responses since beta3 and I'm pretty sure we still don't :smile: .

> Fiddler do not show any http requests on dnu restore.
> After AppData/dnu was removed all packages downloaded.
> Can someone try to reproduce?

Maybe you just had a corrupt cache from a bad nuget server. The latest build avoids caching any type of response and will likely fix issues like this in the future https://github.com/aspnet/dnx/commit/5b81f64409e4d4aac121a5b66fd58d787a827808

**Comment by ggrnd0** [comment] 2015-05-12 20:13
> Maybe you just had a corrupt cache from a bad nuget server.

`myget.com`

Scenario:
- close all VS
- delete `.dnx/packages` and `AppData/Local/dnu`
- add corr

**Comment by davidfowl** [comment] 2015-05-12 20:14
MyGet.org did have a bug that they fixed recently where they were returning bad status codes.

**Comment by ggrnd0** [comment] 2015-05-12 20:18
> MyGet.org did have a bug that they fixed recently where they were returning bad status codes.

fiddler indicate correct 404 status

**Comment by ggrnd0** [comment] 2015-05-12 20:26
Seriously?
Why one-second-action-delete-`AppData/Local/dnu` repair ~45minute bug?
Is it normal, what bug in myget.com hides any time i delete `AppData/Local/dnu`?

**Comment by ggrnd0** [comment] 2015-05-12 20:28
Can github move this issue to nuget/home/issues? Or i must copy it to?

**Comment by davidfowl** [comment] 2015-05-12 20:32
OK I'll get somebody to try and reproduce this bug with the latest changes we made and your repro steps.

Scenario (i use dnx-clr-win-x86-1.0.0-beta5-11672):

> 1. close all VS
> 2. delete .dnx/packages and AppData/Local/dnu
> 3. add package what not in any galleries in your project
> 4. dnu restore (fiddler indicate correct 404 status)
> 5. upload package to gallery
> 6. dnu restore - still 'not found'
> 7. delete AppData/Local/dnu
> 8. dnu restore - it works!

I assume you made a custom myget feed and you manually uploaded packages to it, tha'ts what step 5 is right?

@ChengTian can you try to reproduce this with your latest changes and see if it still happens?

**Comment by ggrnd0** [comment] 2015-05-12 20:35
yes, my private feed. upload from cmd. simplest way.

**Comment by davidfowl** [comment] 2015-05-12 20:35
Great @ChengTian will verify that this works.

**Comment by ggrnd0** [comment] 2015-05-12 20:36
>4 dnu restore
mistake. Fiddler do not catch dnu requests. That was got from VS2015RC. But result in VS and dnu is same.

**Comment by ggrnd0** [comment] 2015-05-12 20:41
Somethink strange.
`AppData/Local/dnu` look good - correct data is cached. But `dnu` and VS still said package

**Comment by davidfowl** [comment] 2015-05-12 20:43
Don't worry, @ChengTian will run through your repro steps and see if he sees the same thing. If not we'll close the bug and if you get better repro steps we'll try again.

**Comment by ChengTian** [comment] 2015-05-12 20:44
Yeah, I am trying @ggrnd0 's repro steps. Will give feedback shortly.

**Comment by ggrnd0** [comment] 2015-05-12 20:58
I have some result on latest `dnx-coreclr-win-x64.1.0.0-beta5-11756`

**Comment by ChengTian** [comment] 2015-05-12 21:47
Just did some experiments and myget always returns 200 status code. Even you are doing `FindPackagesById` with a non-existent package ID, it returns a empty result along with 200 status code.

@ggrnd0 , could you please try accessing the your package query URI directly with your browser?

For my own test, it's `https://www.myget.org/F/for-test/api/v2/FindPackagesById()?id='TestCacheWithMyGet'`. My browser shows an XML along with 200 code in Fiddler.

If you are seeing 404 instead, your myget feed is probably having some issues.

**Comment by ChengTian** [comment] 2015-05-12 21:49
Except for the 404 status code, all other behaviors in @ggrnd0 's repro steps are expected. We always cache a package query result for 30min, even it's an empty result (for non-existent package ID).

If you make changes to your feed and want to use the new packages instantly (within 30min), please use `dnu restore --no-cache`

**Comment by ChengTian** [comment] 2015-05-12 21:49
Cannot reproduce, closing this.

**Closed by ChengTian** 2015-05-12 21:49 UTC
