### ISSUE TITLE
Building Portable111 target fails

### ISSUE THREAD

**Issue by pemari-msft** [aspnet/dnx#1653] opened 2015-04-14 22:15 UTC
I'd like build a PCL target for our library so we can use it on Xamarin.iOS and Xamarin.Android. Using -beta1, our dll built for aspnet50 (not core) works fine with Xamarin. However, from what I understand, I need to use one of the Portable targets in order for the Xamarin/Nuget scenario to be supported. 

I add the following to my project.json: 
//// under the portable include the aspnetcore50 and aspnet50 targets
```json
 "frameworks": {
        ".NETPortable,Version=v4.5.1,Profile=Profile111": {
            "dependencies": {
            }
```

but when I run dnu build, the other two targets build fine and the portable produces: 

```
Building Microsoft.WindowsAzure.Storage for .NETPortable,Version=v4.5.1,Profile=Profile111
  Using Project dependency Microsoft.WindowsAzure.Storage 4.3.2.0    Source: :\Users\pemari\Documents\GitHub\StorageClientPrivate\Lib\AspNet\Microsoft.WindowsAzure.Storage\project.json

  Using Package dependency Microsoft.Data.OData 5.6.3
    Source: C:\Users\pemari\.dnx\packages\Microsoft.Data.OData\5.6.3
    File: lib\portable-net45+wp8+win8+wpa\Microsoft.Data.OData.dll

  Using Package dependency Microsoft.Data.Services.Client 5.6.3
    Source: C:\Users\pemari\.dnx\packages\Microsoft.Data.Services.Client\5.6.3
    File: lib\portable-net45+wp8+win8+wpa\Microsoft.Data.Services.Client.dll

  Using Package dependency System.Spatial 5.6.3
    Source: C:\Users\pemari\.dnx\packages\System.Spatial\5.6.3
    File: lib\portable-net45+wp8+win8+wpa\System.Spatial.dll

  Using Package dependency Microsoft.Data.Edm 5.6.3
    Source: C:\Users\pemari\.dnx\packages\Microsoft.Data.Edm\5.6.3
    File: lib\portable-net45+wp8+win8+wpa\Microsoft.Data.Edm.dll

error CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
```

Any ideas as to what I should be doing here?

**Comment by Eilon** [comment] 2015-04-15 05:43
Do you need to add a package reference to `System.Runtime`? I'm wondering if this is the issue where historically PCL projects had an implicit reference to the entire framework, but in `project.json` all references are explicit...

**Comment by davidfowl** [comment] 2015-04-15 06:24
Yes you need to add the references manually

**Comment by pemari-msft** [comment] 2015-04-16 16:58
Yep, that fixed it. Sorry, thanks for the help!

**Comment by pemari-msft** [comment] 2015-04-16 22:16
Reopening because of a lack of understanding on my part -- here's my confusion.

When I said "that fixed it" before, I was finally able to get it to compile by adding this to my project.json:

        ".NETPortable,Version=v4.5.1,Profile=Profile111": {
            "dependencies": {
                "System.Collections": "4.0.10-beta-*",
                "System.Collections.Concurrent": "4.0.0-beta-*",
                "System.Collections.Specialized": "4.0.0-beta-*",
                "System.Diagnostics.Debug": "4.0.10-beta-*",
                "System.Diagnostics.Tools": "4.0.0-beta-*",
                "System.Diagnostics.TraceSource": "4.0.0-beta-*",
                "System.Diagnostics.Tracing": "4.0.10-beta-*",
                "System.Dynamic.Runtime": "4.0.0-beta-*",
                "System.Globalization": "4.0.10-beta-*",
                "System.IO": "4.0.10-beta-*",
                "System.IO.FileSystem": "4.0.0-beta-*",
                "System.IO.FileSystem.Primitives": "4.0.0-beta-*",
                "System.Linq": "4.0.0-beta-*",
                "System.Linq.Expressions": "4.0.0-beta-*",
                "System.Linq.Queryable": "4.0.0-beta-*",
                "System.Net.Http": "4.0.0-beta-*",
                "System.Net.Primitives": "4.0.10-beta-*",
                "System.Reflection": "4.0.10-beta-*",
                "System.Reflection.Extensions": "4.0.0-beta-*",
                "System.Reflection.TypeExtensions": "4.0.0-beta-*",
                "System.Runtime": "4.0.20-beta-*",
                "System.Runtime.Extensions": "4.0.10-beta-*",
                "System.Runtime.InteropServices": "4.0.20-beta-*",
                "System.Runtime.Serialization.Primitives": "4.0.0-beta-*",
                "System.Runtime.Serialization.Xml": "4.0.10-beta-*",
                "System.Security.Cryptography.Encoding": "4.0.0-beta-*",
                "System.Security.Cryptography.Encryption": "4.0.0-beta-*",
                "System.Security.Cryptography.Hashing": "4.0.0-beta-*",
                "System.Security.Cryptography.Hashing.Algorithms": "4.0.0-beta-*",
                "System.Text.Encoding": "4.0.10-beta-*",
                "System.Text.Encoding.Extensions": "4.0.10-beta-*",
                "System.Text.RegularExpressions": "4.0.10-beta-*",
                "System.Threading": "4.0.0-beta-*",
                "System.Threading.Tasks": "4.0.10-beta-*",
                "System.Threading.Thread": "4.0.0-beta-*",
                "System.Threading.ThreadPool": "4.0.10-beta-*",
                "System.Threading.Timer": "4.0.0-beta-*",
                "System.Xml.ReaderWriter": "4.0.10-beta-*",
                "System.Xml.XDocument": "4.0.0-beta-*",
                "System.Xml.XmlSerializer": "4.0.0-beta-*"
            }, 


That is, adding all the dependencies from aspnetcore50 to my portable target. Adding just the ones from my aspnet50 section produces hundreds of "missing assembly reference" errors. 

Great, now I have a dll that's built, but doing anything with it on xamarin now fails. The most basic of operations has a "warning: Missing method System.Array.Empty<[1]>() in assembly...." exception and crashes. I'd guess that's because I'd need to add the above references to the project somehow, but I don't see how that's even possible using Xamarin. 

Something doesn't feel right with the need to add all of the above references and not just the ones from my aspnet50 section though. I've tested the "ASPNET50" dll, NOT core, and that works fine with Xamarin and is compatible. 

Honestly these are fundamental knowledge questions that I'm just not understanding, so can someone explain why I can't make a dll that behaves like the aspnet50 dll with a "portable" target that will allow my customers to download via nuget for Xamarin? Or rather, how to accomplish that goal? I thought with ProjK I got PCL for free and everything would "just work".

Thanks.

**Comment by Eilon** [comment] 2015-04-16 23:48
Running on Mono currently uses DLLs built for "aspnet50" and not "aspnetcore50" because Mono is based on the API set of .NET Framework, not .NET Core (Core CLR).

Also adding @ericstj to see if he knows more about the relationship between these packages and Portable111.

**Comment by pemari-msft** [comment] 2015-04-17 00:13
Yep, agreed -- hence my confusion as to why it would require all the aspnetcore50 dependencies. Thanks! Hopefully @ericstj can help.

**Comment by ericstj** [comment] 2015-04-17 00:23
Profile111 is Net45 + NetCore45 + WinPhone.  It's effectively a subset of aspnetcore50.

Normally PCL will add-ref everything in the profile, however I don't think DNX does this.  That's why you have to add all the packages.  Some of those packages you are adding are not even in Profile111 so you're library would fail if it happened to use types from them. Have a look at "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile111\RedistList\FrameworkList.xml" to see the assemblies that are part of profile111.

I can't say I condone using DNX to build a PCL.  DNX might make it look kinda-like a PCL but it doesn't go through all of the build targets and doesn't have the grantees in place that the library will indeed run there.

**Comment by davidfowl** [comment] 2015-04-17 04:38
The logic to produce a managed assembly is the same regardless of what framework you build against. Some frameworks have reference assemblies and some don't. The DNX takes the framework name and it computes the set of  reference assemblies to compile against. It also understands how to produce a nuget package from that profile name.

Today PCL project types add the entire framework behind the scenes so users dont have to. DNX projects don't do it (by design) and that's the biggest difference.

**Comment by muratg** [comment] 2015-09-11 17:47
Closing since there wasn't a lot of recent discussion on this one.

**Closed by muratg** 2015-09-11 17:47 UTC
Labels: discussion
