### ISSUE TITLE
NodeJS fails to call "dnu restore" with CoreCLR

### ISSUE THREAD

**Issue by MartinJohns** [aspnet/dnx#2763] opened 2015-09-20 19:39 UTC
I created a very simply script `test.js`:

    var exec = require('child_process').exec;
    exec('dnu restore', function(err, stdout, stderr) {
        console.log('stdout: ' + stdout);
        console.log('stderr: ' + stderr);
        console.log('err: ' + JSON.stringify(err, null, 4));
    });

Now calling this code like this:

    node test.js

Results in this output:

    stdout:
    stderr:
    err: {
        "killed": false,
        "code": 6,
        "signal": null,
        "cmd": "/bin/sh -c dnu restore"
    }

I tested this with `dnx-coreclr-linux-x64.1.0.0-beta7` and `dnx-coreclr-linux-x64.1.0.0-beta8-15618`, both not working. Executing this script works with `dnx-mono.1.0.0-beta`. This script also works with `dnx-clr-win-x64.1.0.0-beta7` on Windows.

Executing `/bin/sh -c 'dnu restore'` on the shell works, only when calling from NodeJS not.

After a bit of testing I tried calling `DNX_TRACE=1 dnu restore` and got the following output:

    stdout:
    Loaded module: dnx.coreclr.so
    Found export: CallApplicationMain
    
    stderr:
    Unhandled Exception: System.IO.IOException: No such device or address
       at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
       at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
       at System.ConsolePal.UnixConsoleStream..ctor(String devPath, FileAccess access)
       at System.Console.<>c.<get_Out>b__11_0()
       at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
       at System.Console.WriteLine(String format, Object[] arg)
       at Microsoft.Dnx.Runtime.Logger.TraceInformation(String message, Object[] args)
       at DomainManager.Execute(Int32 argc, Char** argv)

Related code line is most likely this? https://github.com/dotnet/corefx/blob/b6dda6a964dbdd35ef40b8a285222ec4c7838464/src/Common/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs#L46

Since I'm not familiar with Linux I don't know if this command is correct, but I'm trying to provide more information on the issue. When I call my script with `strace -f -e trace=open bash -c 'node test.js'`, I get the following output:

    open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libtinfo.so.5", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    open("/dev/tty", O_RDWR|O_NONBLOCK)     = 3
    open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
    open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 3
    open("/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 3
    open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
    open("/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 9
    Process 4080 attached
    Process 4079 attached
    Process 4078 attached
    Process 4077 attached
    [pid  4076] open("/root/test/test.js", O_RDONLY) = 9
    [pid  4076] open("/etc/resolv.conf", O_RDONLY) = 9
    [pid  4076] open("/etc/nsswitch.conf", O_RDONLY) = 9
    [pid  4076] open("/dev/urandom", O_RDONLY) = 9
    [pid  4076] open("/dev/null", O_RDONLY|O_CLOEXEC) = 9
    Process 4081 attached
    [pid  4081] open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    [pid  4081] open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    Process 4082 attached
    [pid  4082] open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/libtinfo.so.5", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/dev/tty", O_RDWR|O_NONBLOCK) = 3
    [pid  4082] open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 3
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/dnu", O_RDONLY) = 3
    Process 4083 attached
    Process 4084 attached
    Process 4085 attached
    [pid  4085] open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    [pid  4085] open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    [pid  4085] open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
    [pid  4085] +++ exited with 0 +++
    [pid  4084] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4085, si_status=0, si_utime=0, si_stime=0} ---
    [pid  4084] +++ exited with 0 +++
    [pid  4083] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4084, si_status=0, si_utime=0, si_stime=0} ---
    [pid  4083] +++ exited with 0 +++
    [pid  4082] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4083, si_status=0, si_utime=0, si_stime=0} ---
    [pid  4082] open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/dnx.coreclr.so", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/libcoreclr.so", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/usr/lib/x86_64-linux-gnu/libunwind.so.8", O_RDONLY|O_CLOEXEC) = 3
    [pid  4082] open("/lib/x86_64-linux-gnu/liblzma.so.5", O_RDONLY|O_CLOEXEC) = 3
    Process 4086 attached
    Process 4087 attached
    [pid  4082] open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 10
    Process 4088 attached
    [pid  4088] open("/tmp/clr-debug-pipe-4082-in", O_RDONLYProcess 4089 attached
     <unfinished ...>
    [pid  4082] open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 13
    [pid  4082] open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 13
    [pid  4082] open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 13
    [pid  4082] open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 13
    Process 4090 attached
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/mscorlib.ni.dll", O_RDONLY) = -1 ENOENT (No such file or directory)
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/mscorlib.dll", O_RDONLY) = 13
    [pid  4082] open("/dev/zero", O_RDWR)   = 15
    [pid  4082] open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 11
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/libcoreclr", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/libcoreclr", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/Microsoft.Dnx.Host.CoreClr.dll", O_RDONLY) = 11
    [pid  4082] open("/dev/zero", O_RDWR)   = 14
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Runtime.dll", O_RDONLY) = 12
    [pid  4082] open("/dev/zero", O_RDWR)   = 17
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Runtime.Extensions.dll", O_RDONLY) = 16
    [pid  4082] open("/dev/zero", O_RDWR)   = 19
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/Microsoft.Dnx.Host.dll", O_RDONLY) = 18
    [pid  4082] open("/dev/zero", O_RDWR)   = 21
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Console.dll", O_RDONLY) = 20
    [pid  4082] open("/dev/zero", O_RDWR)   = 23
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.IO.dll", O_RDONLY) = 22
    [pid  4082] open("/dev/zero", O_RDWR)   = 25
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Threading.dll", O_RDONLY) = 24
    [pid  4082] open("/dev/zero", O_RDWR)   = 27
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.IO.FileSystem.Primitives.dll", O_RDONLY) = 26
    [pid  4082] open("/dev/zero", O_RDWR)   = 29
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Runtime.Handles.dll", O_RDONLY) = 28
    [pid  4082] open("/dev/zero", O_RDWR)   = 31
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Runtime.InteropServices.dll", O_RDONLY) = 30
    [pid  4082] open("/dev/zero", O_RDWR)   = 33
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Native.so", O_RDONLY|O_CLOEXEC) = 32
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Native.so", O_RDONLY|O_CLOEXEC) = 32
    [pid  4082] open("/dev/stdout", O_WRONLY) = -1 ENXIO (No such device or address)
    [pid  4082] open("/root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Threading.Tasks.dll", O_RDONLY) = 32
    [pid  4082] open("/dev/zero", O_RDWR)   = 35
    [pid  4082] open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 34
    [pid  4082] open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 34
    [pid  4082] open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 34
    [pid  4082] open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 34
    [pid  4082] open("/proc/self/status", O_RDONLY) = 34
    [pid  4088] <... open resumed> )        = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
    [pid  4088] --- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_TKILL, si_pid=4082, si_uid=0} ---
    [pid  4086] --- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_TKILL, si_pid=4082, si_uid=0} ---
    [pid  4090] +++ exited with 6 +++
    [pid  4089] +++ exited with 6 +++
    [pid  4088] +++ exited with 6 +++
    [pid  4087] +++ exited with 6 +++
    [pid  4086] +++ exited with 6 +++
    [pid  4082] +++ exited with 6 +++
    [pid  4081] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4082, si_status=6, si_utime=21, si_stime=3} ---
    [pid  4081] +++ exited with 6 +++
    [pid  4076] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4081, si_status=6, si_utime=0, si_stime=0} ---
    [pid  4076] open("/dev/tty", O_RDWR|O_CLOEXEC) = 11
    [pid  4076] open("/dev/tty", O_RDWR|O_CLOEXEC) = 10

The critical call seems to be this:

    open("/dev/stdout", O_WRONLY) = -1 ENXIO (No such device or address)

**Comment by stephentoub** [comment] 2015-09-21 00:41
Thanks for the details, @MartinJohns.  I have as hunch what the issue is and that it's manifesting due to how node is redirecting the standard descriptors. I'll try to repro what you're seeing and get back to you.

**Comment by MartinJohns** [comment] 2015-09-21 07:18
@stephentoub Great to hear, thanks!

In the meanwhile, if anyone runs across this issue, this is my temporary solution:

    var exec = require('child_process').exec;
    var spawn = require('child_process').spawn;
    var fs = require('fs');
    var tmp = require('tmp');
    
    var myExec = function (command, params, callback) {
        var isWin = /win/.test(process.platform);
        if (isWin) {
            var cmd = command + ' ' + params.join(' ');
            exec(cmd, callback);
        } else {
            var stdoutFile = tmp.fileSync();
            var stderrFile = tmp.fileSync();
    
            var child = spawn(command, params, { stdio: [null, stdoutFile, stderrFile] });
            child.on('close', function (errCode) {
                var stdout = fs.readFileSync(stdoutFile.name, 'utf8');
                var stderr = fs.readFileSync(stderrFile.name, 'utf8');
                var err = errCode ? { code: errCode, cmd: command + ' ' + params.join(' ') } : null;
    
                stdoutFile.removeCallback();
                stderrFile.removeCallback();
    
                callback(err, stdout, stderr);
            });
        }
    };

This needs the `tmp` package from NPM. I need two different calls for Windows and Linux, because `exec` fails on Linux but works on Windows, and `spawn` fails on Windows but works on Linux.

**Comment by stephentoub** [comment] 2015-09-22 00:32
This should be fixed with https://github.com/dotnet/corefx/pull/3352

**Closed** 2015-09-22 04:54 UTC
